import 'package:cloud_firestore/cloud_firestore.dart';

/// Seeds the Firestore `partners` collection with complete partner profiles.
/// This is the template structure for real-time partner onboarding via admin panel.
/// Safe to run multiple times — uses merge so existing data is not overwritten.
class PartnerSeedService {
  final _db = FirebaseFirestore.instance;

  static const List<Map<String, dynamic>> _demoPartners = [
    {
      // ── Identity ─────────────────────────────────────────────────────────
      'name': 'Monmouth Coffee Co.',
      'slug': 'monmouth_coffee_co',
      'category': 'Café',
      'type': 'Café',
      'iconKey': 'coffee',
      'desc': 'One of London\'s most celebrated independent coffee roasters, '
          'beloved for its single-origin brews served in a rustic Borough Market setting.',

      // ── Contact & Location ────────────────────────────────────────────────
      'address': '2 Park St, Borough Market, SE1 9AB',
      'city': 'London',
      'postcode': 'SE1 9AB',
      'country': 'United Kingdom',
      'phone': '020 7232 3010',
      'email': 'info@monmouthcoffee.co.uk',
      'website': 'https://www.monmouthcoffee.co.uk',
      'lat': 51.5055,
      'lng': -0.0909,

      // ── GoOuts Cashback ───────────────────────────────────────────────────
      'cashbackPct': 12,
      'cashback': '12%',
      'isActive': true,
      'isQrPartner': false,
      'merchantId': 'MNMTH001',

      // ── Stats (updated by system) ─────────────────────────────────────────
      'rating': 4.9,
      'reviews': '3.1k',
      'visits': '18.4k+ visits',
      'distance': '0.3 mi',

      // ── Media ─────────────────────────────────────────────────────────────
      'imageUrl': 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&q=75',

      // ── Amenities ─────────────────────────────────────────────────────────
      'hasWifi': true,
      'hasSeating': true,
      'hasCharging': false,
      'allowsPets': false,

      // ── Dietary ───────────────────────────────────────────────────────────
      'isHalal': false,
      'isVegetarian': true,
      'isVegan': true,

      // ── Opening Hours ─────────────────────────────────────────────────────
      'openingHours': {
        'monday': '7:30 AM – 5:30 PM',
        'tuesday': '7:30 AM – 5:30 PM',
        'wednesday': '7:30 AM – 5:30 PM',
        'thursday': '7:30 AM – 5:30 PM',
        'friday': '7:30 AM – 5:30 PM',
        'saturday': '8:00 AM – 5:30 PM',
        'sunday': 'Closed',
      },

      // ── Admin ─────────────────────────────────────────────────────────────
      'commissionRate': 0.0,
      'onboardedBy': 'GoOuts Demo Seed',
      'status': 'active',
    },

    {
      'name': 'Dishoom Covent Garden',
      'slug': 'dishoom_covent_garden',
      'category': 'Indian Restaurant',
      'type': 'Restaurant',
      'iconKey': 'restaurant',
      'desc': 'Inspired by the iconic Irani cafés of Bombay, Dishoom serves '
          'extraordinary food all day long in a stunning Covent Garden setting.',
      'address': '12 Upper St Martin\'s Lane, WC2H 9FB',
      'city': 'London',
      'postcode': 'WC2H 9FB',
      'country': 'United Kingdom',
      'phone': '020 7420 9320',
      'email': 'coventgarden@dishoom.com',
      'website': 'https://www.dishoom.com',
      'lat': 51.5121,
      'lng': -0.1254,
      'cashbackPct': 10,
      'cashback': '10%',
      'isActive': true,
      'isQrPartner': false,
      'merchantId': 'DSHM001',
      'rating': 4.8,
      'reviews': '8.4k',
      'visits': '32.5k+ visits',
      'distance': '0.7 mi',
      'imageUrl': 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400&q=75',
      'hasWifi': true,
      'hasSeating': true,
      'hasCharging': false,
      'allowsPets': false,
      'isHalal': true,
      'isVegetarian': true,
      'isVegan': false,
      'openingHours': {
        'monday': '8:00 AM – 11:00 PM',
        'tuesday': '8:00 AM – 11:00 PM',
        'wednesday': '8:00 AM – 11:00 PM',
        'thursday': '8:00 AM – 11:00 PM',
        'friday': '8:00 AM – 11:30 PM',
        'saturday': '8:00 AM – 11:30 PM',
        'sunday': '8:00 AM – 11:00 PM',
      },
      'commissionRate': 0.0,
      'onboardedBy': 'GoOuts Demo Seed',
      'status': 'active',
    },

    {
      'name': 'The Churchill Arms',
      'slug': 'the_churchill_arms',
      'category': 'Historic Pub',
      'type': 'Pub',
      'iconKey': 'bar',
      'desc': 'A legendary Kensington pub draped in hanging flower baskets '
          'and festive lights — a true London institution.',
      'address': '119 Kensington Church St, W8 7LN',
      'city': 'London',
      'postcode': 'W8 7LN',
      'country': 'United Kingdom',
      'phone': '020 7727 4242',
      'email': 'info@churchillarmskensington.co.uk',
      'website': 'https://www.churchillarmskensington.co.uk',
      'lat': 51.5052,
      'lng': -0.1935,
      'cashbackPct': 15,
      'cashback': '15%',
      'isActive': true,
      'isQrPartner': false,
      'merchantId': 'CHRCHL001',
      'rating': 4.8,
      'reviews': '2.6k',
      'visits': '24.6k+ visits',
      'distance': '1.1 mi',
      'imageUrl': 'https://images.unsplash.com/photo-1525268323446-0505b6fe7778?w=400&q=75',
      'hasWifi': true,
      'hasSeating': true,
      'hasCharging': false,
      'allowsPets': true,
      'isHalal': false,
      'isVegetarian': true,
      'isVegan': false,
      'openingHours': {
        'monday': '11:00 AM – 11:00 PM',
        'tuesday': '11:00 AM – 11:00 PM',
        'wednesday': '11:00 AM – 11:00 PM',
        'thursday': '11:00 AM – 11:00 PM',
        'friday': '11:00 AM – 11:30 PM',
        'saturday': '11:00 AM – 11:30 PM',
        'sunday': '12:00 PM – 10:30 PM',
      },
      'commissionRate': 0.0,
      'onboardedBy': 'GoOuts Demo Seed',
      'status': 'active',
    },

    {
      'name': 'Fabric',
      'slug': 'fabric',
      'category': 'Nightclub',
      'type': 'Nightclub',
      'iconKey': 'nightlife',
      'desc': 'One of the world\'s most respected nightclubs, a cornerstone '
          'of London\'s electronic music scene since 1999.',
      'address': '77a Charterhouse St, Farringdon, EC1M 6HJ',
      'city': 'London',
      'postcode': 'EC1M 6HJ',
      'country': 'United Kingdom',
      'phone': '020 7336 8898',
      'email': 'info@fabriclondon.com',
      'website': 'https://www.fabriclondon.com',
      'lat': 51.5203,
      'lng': -0.1016,
      'cashbackPct': 8,
      'cashback': '8%',
      'isActive': true,
      'isQrPartner': true,
      'merchantId': 'FABRIC001',
      'rating': 4.7,
      'reviews': '5.2k',
      'visits': '42.1k+ visits',
      'distance': '1.4 mi',
      'imageUrl': 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?w=400&q=75',
      'hasWifi': false,
      'hasSeating': true,
      'hasCharging': true,
      'allowsPets': false,
      'isHalal': false,
      'isVegetarian': false,
      'isVegan': false,
      'openingHours': {
        'monday': 'Closed',
        'tuesday': 'Closed',
        'wednesday': 'Closed',
        'thursday': '11:00 PM – 8:00 AM',
        'friday': '11:00 PM – 8:00 AM',
        'saturday': '11:00 PM – 8:00 AM',
        'sunday': '11:00 PM – 6:00 AM',
      },
      'commissionRate': 0.0,
      'onboardedBy': 'GoOuts Demo Seed',
      'status': 'active',
    },

    {
      'name': 'Sketch',
      'slug': 'sketch',
      'category': 'Restaurant & Bar',
      'type': 'Restaurant & Bar',
      'iconKey': 'restaurant',
      'desc': 'A spectacular collection of restaurants and bars housed in '
          'an 18th-century Mayfair townhouse. Art, food, and atmosphere.',
      'address': '9 Conduit St, Mayfair, W1S 2XG',
      'city': 'London',
      'postcode': 'W1S 2XG',
      'country': 'United Kingdom',
      'phone': '020 7659 4500',
      'email': 'info@sketch.london',
      'website': 'https://sketch.london',
      'lat': 51.5125,
      'lng': -0.1432,
      'cashbackPct': 12,
      'cashback': '12%',
      'isActive': true,
      'isQrPartner': false,
      'merchantId': 'SKTCH001',
      'rating': 4.7,
      'reviews': '4.9k',
      'visits': '14.8k+ visits',
      'distance': '1.8 mi',
      'imageUrl': 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&q=75',
      'hasWifi': true,
      'hasSeating': true,
      'hasCharging': true,
      'allowsPets': false,
      'isHalal': false,
      'isVegetarian': true,
      'isVegan': true,
      'openingHours': {
        'monday': '12:00 PM – 2:00 AM',
        'tuesday': '12:00 PM – 2:00 AM',
        'wednesday': '12:00 PM – 2:00 AM',
        'thursday': '12:00 PM – 2:00 AM',
        'friday': '12:00 PM – 2:00 AM',
        'saturday': '12:00 PM – 2:00 AM',
        'sunday': 'Closed',
      },
      'commissionRate': 0.0,
      'onboardedBy': 'GoOuts Demo Seed',
      'status': 'active',
    },

    {
      'name': 'Poppies Fish & Chips',
      'slug': 'poppies_fish_chips',
      'category': 'Fast Food',
      'type': 'Fast Food',
      'iconKey': 'fastfood',
      'desc': 'London\'s most celebrated fish and chips restaurant. '
          'Fresh fish, hand-cut chips, classic British seaside food done right.',
      'address': '6-8 Hanbury St, Spitalfields, E1 6QR',
      'city': 'London',
      'postcode': 'E1 6QR',
      'country': 'United Kingdom',
      'phone': '020 7247 0892',
      'email': 'info@poppiesfishandchips.co.uk',
      'website': 'https://www.poppiesfishandchips.co.uk',
      'lat': 51.5200,
      'lng': -0.0726,
      'cashbackPct': 10,
      'cashback': '10%',
      'isActive': true,
      'isQrPartner': true,
      'merchantId': 'PPPS001',
      'rating': 4.6,
      'reviews': '2.1k',
      'visits': '11.2k+ visits',
      'distance': '0.9 mi',
      'imageUrl': 'https://images.unsplash.com/photo-1585325701956-60dd9c8553bc?w=400&q=75',
      'hasWifi': false,
      'hasSeating': true,
      'hasCharging': false,
      'allowsPets': false,
      'isHalal': false,
      'isVegetarian': false,
      'isVegan': false,
      'openingHours': {
        'monday': '11:00 AM – 10:00 PM',
        'tuesday': '11:00 AM – 10:00 PM',
        'wednesday': '11:00 AM – 10:00 PM',
        'thursday': '11:00 AM – 10:00 PM',
        'friday': '11:00 AM – 10:30 PM',
        'saturday': '11:00 AM – 10:30 PM',
        'sunday': '11:00 AM – 10:00 PM',
      },
      'commissionRate': 0.0,
      'onboardedBy': 'GoOuts Demo Seed',
      'status': 'active',
    },

    {
      'name': 'Bleecker Burger',
      'slug': 'bleecker_burger',
      'category': 'Fast Food',
      'type': 'Fast Food',
      'iconKey': 'burger',
      'desc': 'Award-winning burgers made from dry-aged beef, '
          'served in a no-fuss setting in the heart of the City.',
      'address': '3 Bloomberg Arcade, EC4N 8AR',
      'city': 'London',
      'postcode': 'EC4N 8AR',
      'country': 'United Kingdom',
      'phone': '020 3146 4500',
      'email': 'hello@bleeckerburger.co.uk',
      'website': 'https://bleeckerburger.co.uk',
      'lat': 51.5124,
      'lng': -0.0889,
      'cashbackPct': 8,
      'cashback': '8%',
      'isActive': true,
      'isQrPartner': true,
      'merchantId': 'BLCKR001',
      'rating': 4.7,
      'reviews': '1.8k',
      'visits': '9.8k+ visits',
      'distance': '1.2 mi',
      'imageUrl': 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&q=75',
      'hasWifi': true,
      'hasSeating': true,
      'hasCharging': false,
      'allowsPets': false,
      'isHalal': false,
      'isVegetarian': false,
      'isVegan': false,
      'openingHours': {
        'monday': '11:30 AM – 9:00 PM',
        'tuesday': '11:30 AM – 9:00 PM',
        'wednesday': '11:30 AM – 9:00 PM',
        'thursday': '11:30 AM – 9:00 PM',
        'friday': '11:30 AM – 9:00 PM',
        'saturday': '11:30 AM – 9:00 PM',
        'sunday': 'Closed',
      },
      'commissionRate': 0.0,
      'onboardedBy': 'GoOuts Demo Seed',
      'status': 'active',
    },

    {
      'name': 'Attendant Coffee',
      'slug': 'attendant_coffee',
      'category': 'Café',
      'type': 'Café',
      'iconKey': 'coffee',
      'desc': 'A unique café housed in a restored Victorian underground '
          'public toilet. Exceptional specialty coffee in a truly one-of-a-kind setting.',
      'address': '74 Great Titchfield St, Fitzrovia, W1W 7QP',
      'city': 'London',
      'postcode': 'W1W 7QP',
      'country': 'United Kingdom',
      'phone': '020 7580 6089',
      'email': 'info@the-attendant.com',
      'website': 'https://the-attendant.com',
      'lat': 51.5200,
      'lng': -0.1395,
      'cashbackPct': 15,
      'cashback': '15%',
      'isActive': true,
      'isQrPartner': false,
      'merchantId': 'ATTND001',
      'rating': 4.8,
      'reviews': '1.9k',
      'visits': '7.3k+ visits',
      'distance': '0.6 mi',
      'imageUrl': 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=400&q=75',
      'hasWifi': true,
      'hasSeating': true,
      'hasCharging': true,
      'allowsPets': false,
      'isHalal': false,
      'isVegetarian': true,
      'isVegan': true,
      'openingHours': {
        'monday': '8:00 AM – 5:00 PM',
        'tuesday': '8:00 AM – 5:00 PM',
        'wednesday': '8:00 AM – 5:00 PM',
        'thursday': '8:00 AM – 5:00 PM',
        'friday': '8:00 AM – 5:00 PM',
        'saturday': '9:00 AM – 5:00 PM',
        'sunday': 'Closed',
      },
      'commissionRate': 0.0,
      'onboardedBy': 'GoOuts Demo Seed',
      'status': 'active',
    },

    {
      'name': 'Ronnie Scott\'s',
      'slug': 'ronnie_scotts',
      'category': 'Music Venue',
      'type': 'Music',
      'iconKey': 'music',
      'desc': 'The legendary Soho jazz club. World-class live music every night '
          'in an intimate setting that has hosted the greatest musicians of all time.',
      'address': '47 Frith St, Soho, W1D 4HT',
      'city': 'London',
      'postcode': 'W1D 4HT',
      'country': 'United Kingdom',
      'phone': '020 7439 0747',
      'email': 'info@ronniescotts.co.uk',
      'website': 'https://www.ronniescotts.co.uk',
      'lat': 51.5133,
      'lng': -0.1313,
      'cashbackPct': 10,
      'cashback': '10%',
      'isActive': true,
      'isQrPartner': true,
      'merchantId': 'RNNSC001',
      'rating': 4.8,
      'reviews': '3.4k',
      'visits': '18.9k+ visits',
      'distance': '0.8 mi',
      'imageUrl': 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=400&q=75',
      'hasWifi': true,
      'hasSeating': true,
      'hasCharging': false,
      'allowsPets': false,
      'isHalal': false,
      'isVegetarian': false,
      'isVegan': false,
      'openingHours': {
        'monday': '5:00 PM – 3:00 AM',
        'tuesday': '5:00 PM – 3:00 AM',
        'wednesday': '5:00 PM – 3:00 AM',
        'thursday': '5:00 PM – 3:00 AM',
        'friday': '5:00 PM – 3:00 AM',
        'saturday': '5:00 PM – 3:00 AM',
        'sunday': '5:00 PM – 3:00 AM',
      },
      'commissionRate': 0.0,
      'onboardedBy': 'GoOuts Demo Seed',
      'status': 'active',
    },

    {
      'name': 'Workshop Coffee',
      'slug': 'workshop_coffee',
      'category': 'Café',
      'type': 'Café',
      'iconKey': 'coffee',
      'desc': 'Specialty coffee roasters and café with a focus on '
          'quality, sustainability, and exceptional espresso.',
      'address': '1 Barrett St, Marylebone, W1U 1AX',
      'city': 'London',
      'postcode': 'W1U 1AX',
      'country': 'United Kingdom',
      'phone': '020 7253 5754',
      'email': 'hello@workshopcoffee.com',
      'website': 'https://www.workshopcoffee.com',
      'lat': 51.5148,
      'lng': -0.1496,
      'cashbackPct': 12,
      'cashback': '12%',
      'isActive': true,
      'isQrPartner': false,
      'merchantId': 'WRKSH001',
      'rating': 4.7,
      'reviews': '2.3k',
      'visits': '12.1k+ visits',
      'distance': '1.0 mi',
      'imageUrl': 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=400&q=75',
      'hasWifi': true,
      'hasSeating': true,
      'hasCharging': true,
      'allowsPets': false,
      'isHalal': false,
      'isVegetarian': true,
      'isVegan': true,
      'openingHours': {
        'monday': '7:30 AM – 5:00 PM',
        'tuesday': '7:30 AM – 5:00 PM',
        'wednesday': '7:30 AM – 5:00 PM',
        'thursday': '7:30 AM – 5:00 PM',
        'friday': '7:30 AM – 5:00 PM',
        'saturday': '8:30 AM – 5:00 PM',
        'sunday': '9:00 AM – 5:00 PM',
      },
      'commissionRate': 0.0,
      'onboardedBy': 'GoOuts Demo Seed',
      'status': 'active',
    },

    {
      'name': 'XOYO',
      'slug': 'xoyo',
      'category': 'Nightclub',
      'type': 'Nightclub',
      'iconKey': 'nightlife',
      'desc': 'East London\'s premier nightclub. A Shoreditch institution '
          'hosting the best electronic music acts from around the world.',
      'address': '32-37 Cowper St, EC2A 4AP',
      'city': 'London',
      'postcode': 'EC2A 4AP',
      'country': 'United Kingdom',
      'phone': '020 7608 2878',
      'email': 'info@xoyo.co.uk',
      'website': 'https://xoyo.co.uk',
      'lat': 51.5253,
      'lng': -0.0845,
      'cashbackPct': 10,
      'cashback': '10%',
      'isActive': true,
      'isQrPartner': true,
      'merchantId': 'XOYO001',
      'rating': 4.6,
      'reviews': '3.7k',
      'visits': '28.4k+ visits',
      'distance': '1.3 mi',
      'imageUrl': 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?w=400&q=75',
      'hasWifi': false,
      'hasSeating': true,
      'hasCharging': false,
      'allowsPets': false,
      'isHalal': false,
      'isVegetarian': false,
      'isVegan': false,
      'openingHours': {
        'monday': 'Closed',
        'tuesday': 'Closed',
        'wednesday': 'Closed',
        'thursday': '10:00 PM – 6:00 AM',
        'friday': '10:00 PM – 7:00 AM',
        'saturday': '10:00 PM – 7:00 AM',
        'sunday': 'Closed',
      },
      'commissionRate': 0.0,
      'onboardedBy': 'GoOuts Demo Seed',
      'status': 'active',
    },

    {
      'name': 'Jazz Cafe',
      'slug': 'jazz_cafe',
      'category': 'Music Venue',
      'type': 'Music',
      'iconKey': 'music',
      'desc': 'Camden\'s iconic jazz, soul, and hip-hop venue. '
          'Live music every night in an intimate candlelit setting.',
      'address': '5 Parkway, Camden, NW1 7PG',
      'city': 'London',
      'postcode': 'NW1 7PG',
      'country': 'United Kingdom',
      'phone': '020 7485 6834',
      'email': 'info@jazzcafelondon.com',
      'website': 'https://www.jazzcafelondon.com',
      'lat': 51.5393,
      'lng': -0.1426,
      'cashbackPct': 10,
      'cashback': '10%',
      'isActive': true,
      'isQrPartner': true,
      'merchantId': 'JZCAF001',
      'rating': 4.5,
      'reviews': '2.8k',
      'visits': '15.6k+ visits',
      'distance': '1.9 mi',
      'imageUrl': 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=400&q=75',
      'hasWifi': true,
      'hasSeating': true,
      'hasCharging': false,
      'allowsPets': false,
      'isHalal': false,
      'isVegetarian': false,
      'isVegan': false,
      'openingHours': {
        'monday': '7:00 PM – 2:00 AM',
        'tuesday': '7:00 PM – 2:00 AM',
        'wednesday': '7:00 PM – 2:00 AM',
        'thursday': '7:00 PM – 2:00 AM',
        'friday': '7:00 PM – 3:00 AM',
        'saturday': '7:00 PM – 3:00 AM',
        'sunday': '7:00 PM – 1:00 AM',
      },
      'commissionRate': 0.0,
      'onboardedBy': 'GoOuts Demo Seed',
      'status': 'active',
    },

    {
      'name': 'Aqua Shard',
      'slug': 'aqua_shard',
      'category': 'Restaurant',
      'type': 'Restaurant',
      'iconKey': 'restaurant',
      'desc': 'Stunning all-day dining at The Shard with breathtaking panoramic '
          'views over London. Modern British cuisine at its finest.',
      'address': '31 St Thomas St, London Bridge, SE1 9RY',
      'city': 'London',
      'postcode': 'SE1 9RY',
      'country': 'United Kingdom',
      'phone': '020 3011 1256',
      'email': 'aquashard@aqua-london.com',
      'website': 'https://aqua-london.com/aqua-shard',
      'lat': 51.5045,
      'lng': -0.0865,
      'cashbackPct': 12,
      'cashback': '12%',
      'isActive': true,
      'isQrPartner': false,
      'merchantId': 'AQSRD001',
      'rating': 4.6,
      'reviews': '3.2k',
      'visits': '19.7k+ visits',
      'distance': '1.5 mi',
      'imageUrl': 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&q=75',
      'hasWifi': true,
      'hasSeating': true,
      'hasCharging': false,
      'allowsPets': false,
      'isHalal': false,
      'isVegetarian': true,
      'isVegan': false,
      'openingHours': {
        'monday': '12:00 PM – 1:00 AM',
        'tuesday': '12:00 PM – 1:00 AM',
        'wednesday': '12:00 PM – 1:00 AM',
        'thursday': '12:00 PM – 1:00 AM',
        'friday': '12:00 PM – 2:00 AM',
        'saturday': '12:00 PM – 2:00 AM',
        'sunday': '12:00 PM – 12:00 AM',
      },
      'commissionRate': 0.0,
      'onboardedBy': 'GoOuts Demo Seed',
      'status': 'active',
    },
  ];

  /// Seeds merchants only if not already seeded.
  /// Checks for a `_meta/seed` document — skips if found.
  Future<void> seedOnce() async {
    try {
      final meta = await _db.collection('merchants').doc('_meta').get();
      if (meta.exists && meta.data()?['seeded'] == true) return;
      await seedPartners();
      await _db.collection('merchants').doc('_meta').set({
        'seeded': true,
        'seededAt': FieldValue.serverTimestamp(),
        'count': _demoPartners.length,
      });
    } catch (_) {}
  }

  /// Seeds all demo partners to Firestore `merchants` collection.
  /// Separate from `businesses` (driver/admin app) to avoid conflicts.
  /// Uses slug as document ID. Safe to run multiple times (merge).
  Future<void> seedPartners() async {
    final batch = _db.batch();
    for (final partner in _demoPartners) {
      final slug = partner['slug'] as String;
      final ref = _db.collection('merchants').doc(slug);
      batch.set(ref, {
        ...partner,
        'seededAt': FieldValue.serverTimestamp(),
      }, SetOptions(merge: true));
    }
    await batch.commit();
  }

  /// Checks if a merchant name exists in the Firestore `merchants` collection.
  /// This is GoOuts' own partner registry — separate from driver app `businesses`.
  Future<bool> isPartnerInFirestore(String merchantName) async {
    if (merchantName.isEmpty) return false;
    try {
      final q = merchantName.toLowerCase();
      final all = await _db.collection('merchants').get();
      return all.docs.any((d) {
        final data = d.data();
        final name = (data['name'] as String? ?? '').toLowerCase();
        return name.contains(q) || q.contains(name);
      });
    } catch (_) {
      return false;
    }
  }
}
