// Generated by Google Stitch, 3 August 2026. Source folder: 1-home_screen
// Cleaned and consolidated by the pass described in
// goouts/design/SHORT_STAY_WIRING_PLAN.md part 1.
// NOT WIRED. Every handler in this file is still empty. See part 2.
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import '../theme/stay_colors.dart';

class HomeScreenData {
  static const List<Map<String, dynamic>> partnersNearby = [
    {
      'town': 'Richmond',
      'price': '£112',
      'rating': '4.9',
      'partners': '18 partners nearby',
      'image': 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=400'
    },
    {
      'town': 'Bath',
      'price': '£95',
      'rating': '4.8',
      'partners': '22 partners nearby',
      'image': 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&q=80&w=400'
    },
  ];

  static const List<Map<String, dynamic>> weekendBreaks = [
    {
      'town': 'Cotswolds',
      'price': '£140',
      'rating': '4.7',
      'partners': '12 partners nearby',
      'image': 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&q=80&w=400'
    },
    {
      'town': 'Oxford',
      'price': '£88',
      'rating': '4.6',
      'partners': '15 partners nearby',
      'image': 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=400'
    },
  ];
}

class ShortStayHomeScreen extends StatefulWidget {
  const ShortStayHomeScreen({super.key});

  @override
  State<ShortStayHomeScreen> createState() => _ShortStayHomeScreenState();
}

class _ShortStayHomeScreenState extends State<ShortStayHomeScreen> {
  // The search bar was a static Text and the two pills were plain Containers
  // with no tap handler at all. Rebuilt 3 August 2026.
  final _whereCtrl = TextEditingController();
  DateTimeRange? _dates;
  int _adults = 2;
  int _children = 0;
  int _infants = 0;

  @override
  void dispose() {
    _whereCtrl.dispose();
    super.dispose();
  }

  int get _countedGuests => _adults + _children; // infants do not count

  String get _datesLabel {
    final d = _dates;
    if (d == null) return 'Add dates';
    const m = [
      'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
      'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
    ];
    final a = '${d.start.day} ${m[d.start.month - 1]}';
    final b = '${d.end.day} ${m[d.end.month - 1]}';
    return '$a to $b';
  }

  String get _guestsLabel {
    final parts = <String>[
      '$_adults ${_adults == 1 ? 'adult' : 'adults'}',
      if (_children > 0) '$_children ${_children == 1 ? 'child' : 'children'}',
      if (_infants > 0) '$_infants ${_infants == 1 ? 'infant' : 'infants'}',
    ];
    return parts.join(', ');
  }

  Future<void> _pickDates() async {
    final now = DateTime.now();
    final picked = await showDateRangePicker(
      context: context,
      firstDate: DateTime(now.year, now.month, now.day),
      lastDate: now.add(const Duration(days: 365 * 2)),
      initialDateRange: _dates,
      helpText: 'When are you going',
      saveText: 'Done',
    );
    if (!mounted) return;
    if (picked != null) setState(() => _dates = picked);
  }

  Future<void> _pickGuests() async {
    await showModalBottomSheet<void>(
      context: context,
      backgroundColor: GoOutsColors.cardSurface,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (sheetContext) => StatefulBuilder(
        builder: (sheetContext, setSheetState) => Padding(
          padding: const EdgeInsets.fromLTRB(20, 20, 20, 32),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Text('Guests',
                  style: GoogleFonts.inter(
                    fontSize: 18,
                    fontWeight: FontWeight.w700,
                    color: GoOutsColors.deepNavy,
                  )),
              const SizedBox(height: 8),
              _guestRow('Adults', _adults, 1, 16, (v) {
                setSheetState(() => _adults = v);
                setState(() {});   // crash_scan: ok - tap callback, not async flow
              }),
              _guestRow('Children', _children, 0, 10, (v) {
                setSheetState(() => _children = v);
                setState(() {});   // crash_scan: ok - tap callback, not async flow
              }, note: 'Age 2 to 12'),
              _guestRow('Infants', _infants, 0, 5, (v) {
                setSheetState(() => _infants = v);
                setState(() {});   // crash_scan: ok - tap callback, not async flow
              }, note: 'Under 2, and they do not count towards the limit'),
            ],
          ),
        ),
      ),
    );
  }

  Widget _guestRow(String label, int value, int min, int max,
      ValueChanged<int> onChange, {String? note}) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 10),
      child: Row(
        children: [
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(label,
                    style: GoogleFonts.inter(
                      fontSize: 15,
                      fontWeight: FontWeight.w600,
                      color: GoOutsColors.deepNavy,
                    )),
                if (note != null)
                  Text(note,
                      style: GoogleFonts.inter(
                          fontSize: 12, color: GoOutsColors.bodyText)),
              ],
            ),
          ),
          IconButton(
            onPressed: value <= min ? null : () => onChange(value - 1),
            icon: const Icon(Icons.remove_circle_outline),
            color: GoOutsColors.primaryBlue,
            disabledColor: GoOutsColors.outlineVariant,
          ),
          SizedBox(
            width: 28,
            child: Text('$value',
                textAlign: TextAlign.center,
                style: GoogleFonts.inter(
                  fontSize: 16,
                  fontWeight: FontWeight.w600,
                  color: GoOutsColors.deepNavy,
                )),
          ),
          IconButton(
            onPressed: value >= max ? null : () => onChange(value + 1),
            icon: const Icon(Icons.add_circle_outline),
            color: GoOutsColors.primaryBlue,
            disabledColor: GoOutsColors.outlineVariant,
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: GoOutsColors.pageBackground,
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0.5,
        leading: const Icon(Icons.arrow_back, color: GoOutsColors.primaryBlue),
        title: Text(
          'Short Stay',
          style: GoogleFonts.inter(
            fontSize: 20,
            fontWeight: FontWeight.w700,
            color: GoOutsColors.deepNavy,
          ),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _buildSearchField(),
            const SizedBox(height: 12),
            _buildPillSelectors(),
            const SizedBox(height: 20),
            _buildSectionHeader('Places with the most GoOuts partners nearby'),
            const SizedBox(height: 8),
            _buildHorizontalList(HomeScreenData.partnersNearby),
            const SizedBox(height: 20),
            _buildSectionHeader('Weekend breaks'),
            const SizedBox(height: 8),
            _buildHorizontalList(HomeScreenData.weekendBreaks),
            const SizedBox(height: 20),
            _buildSectionHeader('Recently viewed'),
            const SizedBox(height: 8),
            _buildHorizontalList(HomeScreenData.partnersNearby),
          ],
        ),
      ),
    );
  }

  Widget _buildSearchField() {
    return Container(
      height: 52,
      padding: const EdgeInsets.symmetric(horizontal: 16),
      decoration: BoxDecoration(
        color: GoOutsColors.cardSurface,
        borderRadius: BorderRadius.circular(12),
      ),
      child: Row(
        children: [
          const Icon(Icons.search, color: GoOutsColors.primaryBlue),
          const SizedBox(width: 12),
          Expanded(
            child: TextField(
              controller: _whereCtrl,
              textInputAction: TextInputAction.search,
              onChanged: (_) => setState(() {}),
              onSubmitted: (_) => _search(),
              decoration: InputDecoration(
                isDense: true,
                border: InputBorder.none,
                hintText: 'Where are you going',
                hintStyle: GoogleFonts.inter(
                  fontSize: 16,
                  color: GoOutsColors.bodyText,
                ),
              ),
              style: GoogleFonts.inter(
                fontSize: 16,
                color: GoOutsColors.deepNavy,
              ),
            ),
          ),
          if (_whereCtrl.text.isNotEmpty)
            IconButton(
              icon: const Icon(Icons.close, size: 18),
              color: GoOutsColors.bodyText,
              onPressed: () {
                _whereCtrl.clear();
                setState(() {});
              },
            ),
        ],
      ),
    );
  }

  /// TODO wiring, task 116. Pushes StayRoutes.results with the criteria.
  void _search() {}

  Widget _buildPillSelectors() {
    return Row(
      children: [
        _buildPill(_datesLabel, Icons.calendar_today_outlined, _pickDates,
            active: _dates != null),
        const SizedBox(width: 8),
        _buildPill(_guestsLabel, Icons.person_outline, _pickGuests,
            active: _countedGuests != 2 || _infants > 0),
      ],
    );
  }

  Widget _buildPill(String text, IconData icon, VoidCallback onTap,
      {bool active = false}) {
    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(20),
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 9),
        decoration: BoxDecoration(
          color: active
              ? GoOutsColors.paleBlueTint
              : GoOutsColors.cardSurface,
          borderRadius: BorderRadius.circular(20),
        ),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(icon,
                size: 15,
                color: active
                    ? GoOutsColors.primaryBlue
                    : GoOutsColors.bodyText),
            const SizedBox(width: 6),
            Text(
              text,
              style: GoogleFonts.inter(
                fontSize: 13.5,
                fontWeight: active ? FontWeight.w600 : FontWeight.w400,
                color: active
                    ? GoOutsColors.primaryBlue
                    : GoOutsColors.bodyText,
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildSectionHeader(String title) {
    return Text(
      title,
      style: GoogleFonts.inter(
        fontSize: 15,
        fontWeight: FontWeight.w700,
        color: GoOutsColors.primaryBlue,
      ),
    );
  }

  Widget _buildHorizontalList(List<Map<String, dynamic>> items) {
    return SizedBox(
      height: 240,
      child: ListView.separated(
        scrollDirection: Axis.horizontal,
        itemCount: items.length,
        separatorBuilder: (context, index) => const SizedBox(width: 8),
        itemBuilder: (context, index) {
          final item = items[index];
          return Container(
            width: 200,
            decoration: BoxDecoration(
              color: GoOutsColors.cardSurface,
              borderRadius: BorderRadius.circular(12),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                ClipRRect(
                  borderRadius: const BorderRadius.vertical(top: Radius.circular(12)),
                  child: Image.network(
                    item['image'],
                    height: 120,
                    width: double.infinity,
                    fit: BoxFit.cover,
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.all(12),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Text(
                            item['town'],
                            style: GoogleFonts.inter(
                              fontSize: 14,
                              fontWeight: FontWeight.w600,
                              color: GoOutsColors.deepNavy,
                            ),
                          ),
                          Row(
                            children: [
                              const Icon(Icons.star, size: 14, color: GoOutsColors.warning),
                              const SizedBox(width: 4),
                              Text(
                                item['rating'],
                                style: GoogleFonts.inter(fontSize: 12, fontWeight: FontWeight.w500),
                              ),
                            ],
                          ),
                        ],
                      ),
                      const SizedBox(height: 4),
                      Text(
                        '${item['price']} per night',
                        style: GoogleFonts.inter(
                          fontSize: 13.5,
                          color: GoOutsColors.bodyText,
                        ),
                      ),
                      const SizedBox(height: 8),
                      Container(
                        padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                        decoration: BoxDecoration(
                          color: GoOutsColors.primaryBlue,
                          borderRadius: BorderRadius.circular(20),
                        ),
                        child: Text(
                          item['partners'],
                          style: GoogleFonts.inter(
                            fontSize: 11,
                            fontWeight: FontWeight.w600,
                            color: Colors.white,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),
          );
        },
      ),
    );
  }
}
