// Screen 03 of 29. Generated by Google Stitch, source folder 3-search_filters.
// Rebuilt 3 August 2026. The generated version was a StatelessWidget with
// `value: false, onChanged: (val) {}` on every tick box, a fixed RangeSlider
// and an Apply button that did nothing. Nothing could be selected.
//
// Money is in PENCE throughout. The slider works in pounds for display and
// converts at the edge, because a price filter that drifts by a penny produces
// a listing that appears and disappears from results for no visible reason.
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import '../models/stay_amenities.dart';
import '../models/stay_property_types.dart';
import '../services/stay_availability_service.dart';
import '../theme/stay_colors.dart';

/// Returns a [StaySearchCriteria] through `Navigator.pop`, or null if closed
/// without applying. The caller keeps the previous criteria in that case.
class SearchFiltersSheet extends StatefulWidget {
  const SearchFiltersSheet({super.key, this.initial});

  final StaySearchCriteria? initial;

  @override
  State<SearchFiltersSheet> createState() => _SearchFiltersSheetState();
}

class _SearchFiltersSheetState extends State<SearchFiltersSheet> {
  // Display bounds in pounds. Anything above the ceiling is treated as no
  // upper limit, so a £2,000 a night listing is not silently excluded.
  static const double _minPounds = 20;
  static const double _maxPounds = 500;
  static const int _maxPartners = 25;

  // ⚠ FIXED 16 August 2026. This used to be:
  //
  //   static const _propertyTypes = ['Apartment', 'House', 'Room', 'Hotel'];
  //
  // Hosts store slugs — flat, house, annexe, room, cottage, other — and
  // stay_availability_service runs a SERVER-side equality filter:
  //
  //   q.where('propertyType', isEqualTo: criteria.propertyType)
  //
  // so every one of the four returned nothing. 'House' and 'Room' were case
  // mismatches; 'Apartment' and 'Hotel' were values the host wizard cannot
  // produce at all. 'Annexe' and 'Cottage', which hosts DO create, could not
  // be filtered for.
  //
  // See models/stay_property_types.dart.
  static Map<String, String> get _propertyTypes => stayPropertyTypes;

  // ⚠ FIXED 16 August 2026. This used to be a private list of LABELS:
  //
  //   'Internet and office': ['Fast WiFi', 'Dedicated workspace'],
  //   'Kitchen and dining':  ['Kitchen', 'Cooking basics', 'Dining table'],
  //   ...
  //
  // Hosts store SLUGS — 'wifi', 'workspace', 'kitchen'. The service filters
  // client-side with `criteria.amenities.every(l.amenities.contains)`, so a
  // label could never be found in a list of slugs and `.every` returned false
  // for every listing. Ticking ANY single amenity emptied the results, and it
  // read as "no properties match" rather than as a fault.
  //
  // The groups now come from models/stay_amenities.dart, which mirrors the
  // host wizard. Do not reintroduce a local list here — that is the bug.
  static Map<String, List<StayAmenity>> get _amenityGroups =>
      stayAmenityGroups;

  late RangeValues _price;
  String? _propertyType;
  int _bedrooms = 0; // 0 means any
  double _minPartners = 0;
  final Set<String> _amenities = <String>{};

  @override
  void initState() {
    super.initState();
    final i = widget.initial;
    _price = RangeValues(
      ((i?.minPricePence ?? (_minPounds * 100).round()) / 100)
          .clamp(_minPounds, _maxPounds),
      ((i?.maxPricePence ?? (_maxPounds * 100).round()) / 100)
          .clamp(_minPounds, _maxPounds),
    );
    _propertyType = i?.propertyType;
    _bedrooms = i?.minBedrooms ?? 0;
    _minPartners = (i?.minPartnersHalfMile ?? 0).toDouble();
    _amenities.addAll(i?.amenities ?? const []);
  }

  bool get _priceIsDefault =>
      _price.start <= _minPounds && _price.end >= _maxPounds;

  int get _activeCount =>
      (_priceIsDefault ? 0 : 1) +
      (_propertyType == null ? 0 : 1) +
      (_bedrooms == 0 ? 0 : 1) +
      (_minPartners == 0 ? 0 : 1) +
      _amenities.length;

  void _reset() => setState(() {
        _price = const RangeValues(_minPounds, _maxPounds);
        _propertyType = null;
        _bedrooms = 0;
        _minPartners = 0;
        _amenities.clear();
      });

  void _apply() {
    final base = widget.initial ?? const StaySearchCriteria();
    Navigator.of(context).pop(
      base.copyWith(
        // Leave price null when untouched, so the query is not narrowed by a
        // filter the guest never set.
        minPricePence: _price.start <= _minPounds
            ? null
            : (_price.start * 100).round(),
        maxPricePence:
            _price.end >= _maxPounds ? null : (_price.end * 100).round(),
        propertyType: _propertyType,
        minBedrooms: _bedrooms == 0 ? null : _bedrooms,
        minPartnersHalfMile: _minPartners.round(),
        amenities: _amenities.toList()..sort(),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: GoOutsColors.pageBackground,
      appBar: AppBar(
        backgroundColor: GoOutsColors.cardSurface,
        elevation: 0.5,
        leading: IconButton(
          icon: const Icon(Icons.close, color: GoOutsColors.primaryBlue),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: Text(
          'Filters',
          style: GoogleFonts.inter(
            fontSize: 20,
            fontWeight: FontWeight.w700,
            color: GoOutsColors.deepNavy,
          ),
        ),
        actions: [
          TextButton(
            onPressed: _activeCount == 0 ? null : _reset,
            child: Text(
              'Reset',
              style: GoogleFonts.inter(
                fontSize: 14,
                fontWeight: FontWeight.w600,
                color: _activeCount == 0
                    ? GoOutsColors.outlineVariant
                    : GoOutsColors.primaryBlue,
              ),
            ),
          ),
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.fromLTRB(16, 16, 16, 120),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _header('Price range'),
            Text(
              _priceIsDefault
                  ? 'Any price'
                  : '£${_price.start.round()} to '
                      '£${_price.end.round()}${_price.end >= _maxPounds ? ' or more' : ''} a night',
              style: GoogleFonts.inter(
                  fontSize: 13, color: GoOutsColors.bodyText),
            ),
            RangeSlider(
              values: _price,
              min: _minPounds,
              max: _maxPounds,
              divisions: 48,
              activeColor: GoOutsColors.primaryBlue,
              inactiveColor: GoOutsColors.surfaceBlue,
              labels: RangeLabels(
                '£${_price.start.round()}',
                '£${_price.end.round()}',
              ),
              onChanged: (v) => setState(() => _price = v),
            ),

            _header('Property type'),
            Wrap(
              spacing: 8,
              children: [
                // Selects the slug, shows the label. Selecting the label is
                // the bug this section used to have.
                for (final t in _propertyTypes.entries)
                  ChoiceChip(
                    label: Text(t.value),
                    selected: _propertyType == t.key,
                    onSelected: (sel) =>
                        setState(() => _propertyType = sel ? t.key : null),
                    selectedColor: GoOutsColors.paleBlueTint,
                    labelStyle: GoogleFonts.inter(
                      fontSize: 13.5,
                      fontWeight: FontWeight.w600,
                      color: _propertyType == t.key
                          ? GoOutsColors.primaryBlue
                          : GoOutsColors.bodyText,
                    ),
                  ),
              ],
            ),

            _header('Bedrooms'),
            Row(
              children: [
                _stepButton(
                    Icons.remove,
                    _bedrooms == 0
                        ? null
                        : () => setState(() => _bedrooms--)),
                Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 20),
                  child: Text(
                    _bedrooms == 0 ? 'Any' : '$_bedrooms or more',
                    style: GoogleFonts.inter(
                      fontSize: 15,
                      fontWeight: FontWeight.w600,
                      color: GoOutsColors.deepNavy,
                    ),
                  ),
                ),
                _stepButton(
                    Icons.add,
                    _bedrooms >= 8
                        ? null
                        : () => setState(() => _bedrooms++)),
              ],
            ),

            // The differentiator. Nobody else can offer this filter, because
            // nobody else has a merchant network.
            _header('GoOuts partners nearby'),
            Text(
              _minPartners == 0
                  ? 'Any number of partners'
                  : 'At least ${_minPartners.round()} within half a mile',
              style: GoogleFonts.inter(
                  fontSize: 13, color: GoOutsColors.bodyText),
            ),
            Slider(
              value: _minPartners,
              min: 0,
              max: _maxPartners.toDouble(),
              divisions: _maxPartners,
              activeColor: GoOutsColors.primaryBlue,
              inactiveColor: GoOutsColors.surfaceBlue,
              label: _minPartners.round().toString(),
              onChanged: (v) => setState(() => _minPartners = v),
            ),

            for (final entry in _amenityGroups.entries)
              _amenityGroup(entry.key, entry.value),
          ],
        ),
      ),
      bottomNavigationBar: Container(
        padding: const EdgeInsets.fromLTRB(16, 12, 16, 28),
        decoration: const BoxDecoration(
          color: GoOutsColors.cardSurface,
          border: Border(top: BorderSide(color: GoOutsColors.dividerGray)),
        ),
        child: ElevatedButton(
          onPressed: _apply,
          style: ElevatedButton.styleFrom(
            backgroundColor: GoOutsColors.primaryBlue,
            foregroundColor: GoOutsColors.cardSurface,
            minimumSize: const Size(double.infinity, 52),
            elevation: 0,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
          child: Text(
            _activeCount == 0 ? 'Show all places' : 'Apply $_activeCount filters',
            style: GoogleFonts.inter(
                fontSize: 16, fontWeight: FontWeight.w700),
          ),
        ),
      ),
    );
  }

  Widget _header(String title) => Padding(
        padding: const EdgeInsets.only(top: 20, bottom: 4),
        child: Text(
          title,
          style: GoogleFonts.inter(
            fontSize: 15,
            fontWeight: FontWeight.w700,
            color: GoOutsColors.primaryBlue,
          ),
        ),
      );

  Widget _stepButton(IconData icon, VoidCallback? onTap) => IconButton(
        onPressed: onTap,
        icon: Icon(icon),
        color: GoOutsColors.primaryBlue,
        disabledColor: GoOutsColors.outlineVariant,
        style: IconButton.styleFrom(
          backgroundColor: GoOutsColors.cardSurface,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(10),
          ),
        ),
      );

  Widget _amenityGroup(String title, List<StayAmenity> items) => Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Padding(
            padding: const EdgeInsets.only(top: 16, bottom: 4),
            child: Text(
              title,
              style: GoogleFonts.inter(
                fontSize: 14,
                fontWeight: FontWeight.w600,
                color: GoOutsColors.deepNavy,
              ),
            ),
          ),
          // The checkbox stores item.slug, which is what Firestore holds, and
          // shows item.label, which is what a guest reads. Storing the label
          // is the bug this file used to have.
          for (final item in items)
            CheckboxListTile(
              value: _amenities.contains(item.slug),
              onChanged: (on) => setState(() {
                if (on ?? false) {
                  _amenities.add(item.slug);
                } else {
                  _amenities.remove(item.slug);
                }
              }),
              title: Text(
                item.label,
                style: GoogleFonts.inter(
                  fontSize: 13.5,
                  color: GoOutsColors.bodyText,
                ),
              ),
              contentPadding: EdgeInsets.zero,
              controlAffinity: ListTileControlAffinity.leading,
              activeColor: GoOutsColors.primaryBlue,
              dense: true,
            ),
        ],
      );
}
