// Generated by Google Stitch, 3 August 2026. Source folder: 5-listing_detail
// Cleaned and consolidated by the pass described in
// goouts/design/SHORT_STAY_WIRING_PLAN.md part 1.
// NOT WIRED. Every handler in this file is still empty. See part 2.
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import '../theme/stay_colors.dart';

class ListingDetailScreen extends StatelessWidget {
  const ListingDetailScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: Stack(
        children: [
          SingleChildScrollView(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                _buildPhotoGallery(),
                Padding(
                  padding: const EdgeInsets.all(16),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      _buildHeader(),
                      const SizedBox(height: 16),
                      _buildHostRow(),
                      const Divider(height: 32),
                      _buildAboutSection(),
                      const Divider(height: 32),
                      _buildAmenitiesSection(),
                      const Divider(height: 32),
                      _buildGettingAroundSection(),
                      const SizedBox(height: 20),
                      _buildPartnerHighlightCard(),
                      const Divider(height: 32),
                      _buildReviewsSection(),
                      const SizedBox(height: 100), // Space for bottom bar
                    ],
                  ),
                ),
              ],
            ),
          ),
          _buildTopButtons(context),
          _buildBottomBar(),
        ],
      ),
    );
  }

  Widget _buildPhotoGallery() {
    return Container(
      height: 300,
      width: double.infinity,
      color: Colors.grey.shade200,
      child: Image.network(
        'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800',
        fit: BoxFit.cover,
      ),
    );
  }

  Widget _buildTopButtons(BuildContext context) {
    return SafeArea(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            CircleAvatar(
              backgroundColor: Colors.white,
              child: IconButton(
                icon: const Icon(Icons.arrow_back, color: GoOutsColors.primaryBlue),
                onPressed: () {},
              ),
            ),
            CircleAvatar(
              backgroundColor: Colors.white,
              child: IconButton(
                icon: const Icon(Icons.share, color: GoOutsColors.primaryBlue),
                onPressed: () {},
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildHeader() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          'The Riverside Apartment',
          style: GoogleFonts.inter(
            fontSize: 24,
            fontWeight: FontWeight.w700,
            color: GoOutsColors.deepNavy,
          ),
        ),
        const SizedBox(height: 8),
        Row(
          children: [
            const Icon(Icons.star, size: 18, color: GoOutsColors.warning),
            const SizedBox(width: 4),
            Text(
              '4.9',
              style: GoogleFonts.inter(fontSize: 16, fontWeight: FontWeight.w600),
            ),
            const SizedBox(width: 8),
            Text(
              'Richmond, London',
              style: GoogleFonts.inter(fontSize: 16, color: GoOutsColors.bodyText),
            ),
          ],
        ),
      ],
    );
  }

  Widget _buildHostRow() {
    return Row(
      children: [
        const CircleAvatar(
          radius: 24,
          backgroundImage: NetworkImage('https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200'),
        ),
        const SizedBox(width: 12),
        Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Hosted by Sarah',
              style: GoogleFonts.inter(
                fontSize: 16,
                fontWeight: FontWeight.w600,
                color: GoOutsColors.deepNavy,
              ),
            ),
            Text(
              'Superhost • 5 years experience',
              style: GoogleFonts.inter(fontSize: 14, color: GoOutsColors.bodyText),
            ),
          ],
        ),
      ],
    );
  }

  Widget _buildAboutSection() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          'About this place',
          style: GoogleFonts.inter(
            fontSize: 18,
            fontWeight: FontWeight.w700,
            color: GoOutsColors.deepNavy,
          ),
        ),
        const SizedBox(height: 12),
        Text(
          'A quiet two bedroom apartment overlooking the Thames. It is fully equipped for long or short stays and it is within walking distance of the historic town centre. All rooms are recently decorated and it is professionally cleaned between guests.',
          style: GoogleFonts.inter(
            fontSize: 15,
            height: 1.5,
            color: GoOutsColors.bodyText,
          ),
        ),
      ],
    );
  }

  Widget _buildAmenitiesSection() {
    final List<Map<String, dynamic>> amenities = [
      {'icon': Icons.wifi, 'label': 'Fast WiFi'},
      {'icon': Icons.kitchen, 'label': 'Kitchen'},
      {'icon': Icons.local_laundry_service, 'label': 'Washer'},
      {'icon': Icons.workspace_premium, 'label': 'Workspace'},
      {'icon': Icons.tv, 'label': 'Smart TV'},
      {'icon': Icons.ac_unit, 'label': 'Heating'},
    ];

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          'What this place offers',
          style: GoogleFonts.inter(
            fontSize: 18,
            fontWeight: FontWeight.w700,
            color: GoOutsColors.deepNavy,
          ),
        ),
        const SizedBox(height: 16),
        GridView.builder(
          shrinkWrap: true,
          physics: const NeverScrollableScrollPhysics(),
          gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
            crossAxisCount: 2,
            mainAxisExtent: 40,
            crossAxisSpacing: 16,
            mainAxisSpacing: 16,
          ),
          itemCount: amenities.length,
          itemBuilder: (context, index) {
            return Row(
              children: [
                Icon(amenities[index]['icon'], color: GoOutsColors.tealSecondary, size: 24),
                const SizedBox(width: 12),
                Text(
                  amenities[index]['label'],
                  style: GoogleFonts.inter(fontSize: 15, color: GoOutsColors.bodyText),
                ),
              ],
            );
          },
        ),
        const SizedBox(height: 24),
        OutlinedButton(
          onPressed: () {},
          style: OutlinedButton.styleFrom(
            minimumSize: const Size(double.infinity, 52),
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
            side: const BorderSide(color: GoOutsColors.deepNavy),
          ),
          child: Text(
            'Show all 34 amenities',
            style: GoogleFonts.inter(color: GoOutsColors.deepNavy, fontWeight: FontWeight.w600),
          ),
        ),
      ],
    );
  }

  Widget _buildGettingAroundSection() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          'Getting around',
          style: GoogleFonts.inter(
            fontSize: 18,
            fontWeight: FontWeight.w700,
            color: GoOutsColors.deepNavy,
          ),
        ),
        const SizedBox(height: 12),
        Text(
          '4.2 miles from central London',
          style: GoogleFonts.inter(fontSize: 15, color: GoOutsColors.bodyText),
        ),
        const SizedBox(height: 16),
        _buildStationItem('Richmond Station', 'District and Overground lines', '0.4 miles walking'),
        _buildStationItem('Kew Gardens', 'District line', '0.8 miles walking'),
        _buildStationItem('North Sheen', 'South Western Railway', '1.1 miles walking'),
        const SizedBox(height: 8),
        Text(
          'Distances are calculated from the property address',
          style: GoogleFonts.inter(fontSize: 12, fontStyle: FontStyle.italic, color: GoOutsColors.bodyText),
        ),
      ],
    );
  }

  Widget _buildStationItem(String name, String lines, String distance) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 12),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Icon(Icons.train, color: GoOutsColors.primaryBlue, size: 20),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(name, style: GoogleFonts.inter(fontSize: 15, fontWeight: FontWeight.w600)),
                Text(lines, style: GoogleFonts.inter(fontSize: 13, color: GoOutsColors.bodyText)),
                Text(distance, style: GoogleFonts.inter(fontSize: 13, fontWeight: FontWeight.w500)),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildPartnerHighlightCard() {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: GoOutsColors.primaryBlue,
        borderRadius: BorderRadius.circular(12),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            '18 GoOuts partners within half a mile',
            style: GoogleFonts.inter(
              fontSize: 18,
              fontWeight: FontWeight.w700,
              color: Colors.white,
            ),
          ),
          const SizedBox(height: 12),
          Text(
            '6 restaurants, 3 pubs, 2 cafes, 3 shops',
            style: GoogleFonts.inter(fontSize: 15, color: Colors.white.withValues(alpha: 0.9)),
          ),
          const SizedBox(height: 12),
          Text(
            'Earn cashback at every one',
            style: GoogleFonts.inter(
              fontSize: 15,
              fontWeight: FontWeight.w600,
              color: Colors.white,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildReviewsSection() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            const Icon(Icons.star, color: GoOutsColors.warning, size: 20),
            const SizedBox(width: 8),
            Text(
              '4.9 • 124 reviews',
              style: GoogleFonts.inter(fontSize: 18, fontWeight: FontWeight.w700),
            ),
          ],
        ),
        const SizedBox(height: 16),
        // Mock review
        ListTile(
          contentPadding: EdgeInsets.zero,
          leading: const CircleAvatar(backgroundColor: GoOutsColors.paleBlueTint),
          title: Text('Emma • July 2024', style: GoogleFonts.inter(fontWeight: FontWeight.w600)),
          subtitle: Text(
            'It is a beautiful place and it is so close to everything. We loved the river views.',
            style: GoogleFonts.inter(color: GoOutsColors.bodyText),
          ),
        ),
      ],
    );
  }

  Widget _buildBottomBar() {
    return Align(
      alignment: Alignment.bottomCenter,
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 20),
        decoration: BoxDecoration(
          color: Colors.white,
          border: Border(top: BorderSide(color: Colors.grey.shade300, width: 0.5)),
        ),
        child: SafeArea(
          top: false,
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    '£112 nightly',
                    style: GoogleFonts.inter(fontSize: 18, fontWeight: FontWeight.w700),
                  ),
                  Text(
                    '12 to 14 July',
                    style: GoogleFonts.inter(fontSize: 14, color: GoOutsColors.bodyText),
                  ),
                ],
              ),
              ElevatedButton(
                onPressed: () {},
                style: ElevatedButton.styleFrom(
                  backgroundColor: GoOutsColors.primaryBlue,
                  minimumSize: const Size(180, 52),
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                ),
                child: Text(
                  'Check availability',
                  style: GoogleFonts.inter(fontSize: 16, fontWeight: FontWeight.w600, color: Colors.white),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
