// Generated by Google Stitch, 3 August 2026. Source folder: 5-listing_detail
//
// WIRED 16 August 2026, task #116.
//
// ── WHAT CHANGED AND WHY ─────────────────────────────────────────────────
//
// Reported as "no listing is opening". The listing WAS opening. Screen 02
// pushed StayRoutes.listing with the id, stay_routes.dart parsed the id, and
// then built `const ListingDetailScreen()` and threw the id away. This screen
// took no id and could not have used one — it was a StatelessWidget with a
// hardcoded two bedroom flat in Richmond, 4.9 stars, 124 reviews, Emma's
// review from July 2024.
//
// So every property in the search results opened the same flat. Tapping a
// £95 cottage in Whitby showed £112 nightly and three London stations. That
// reads as broken rather than unfinished, which is why it was reported as
// nothing opening at all.
//
// It now takes a listingId, loads the real listing, and renders what is
// actually stored. Nothing on this screen is invented any more:
//
//   title, rating, town           listing
//   about                         listing.description
//   amenities                     listing.amenities via the shared catalogue
//   distance, stations            listing.locationContext
//   partners within half a mile   listing.locationContext.partnerCounts
//   reviews                       StayListingService.reviews()
//   nightly price                 listing.nightlyRate
//
// ── THE SECTIONS THAT CAN BE ABSENT ──────────────────────────────────────
//
// locationContext is computed by a Cloud Function after the listing is
// approved, so a brand new property has none for a short while. Both sections
// that depend on it are HIDDEN when it is null rather than shown with zeroes.
// "0 GoOuts partners within half a mile" is a worse thing to say than nothing,
// and it would not be true — it is not known yet.
//
// Same for reviews: a listing with none shows the section with an honest
// "No reviews yet" instead of a fabricated one.
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import '../widgets/desktop_top_nav.dart';
import '../models/money.dart';
import '../models/stay_amenities.dart';
// Days out, shown BEFORE booking as of 29 August 2026. Until today the whole
// attractions pipeline was reachable only from the trip screen, which needs a
// booking to exist.
import '../models/stay_attraction.dart';
// CancellationPolicy, for the section this screen never had.
import '../models/stay_enums.dart';
import '../services/stay_attractions_service.dart';
import '../models/stay_listing.dart';
import '../models/stay_property_types.dart';
import '../services/stay_booking_service.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import '../services/stay_listing_service.dart';
import '../services/stay_recently_viewed.dart';
// ⚠ ONE READER FOR REVIEWS, 29 August 2026. StayListingService.reviews() also
// read this subcollection, returning raw maps; both are gone and this is the
// only way in. Two readers of one collection is how "rating shows in one place
// and not another" starts, and this codebase has paid for that pattern before.
import '../services/stay_review_service.dart';
import '../stay_routes.dart';
import '../theme/stay_colors.dart';

class ListingDetailScreen extends StatefulWidget {
  const ListingDetailScreen({super.key, required this.listingId});

  final String listingId;

  @override
  State<ListingDetailScreen> createState() => _ListingDetailScreenState();
}

class _ListingDetailScreenState extends State<ListingDetailScreen> {
  final StayListingService _service = StayListingService.instance;

  late Future<StayListing?> _listing;
  late Future<List<StayReview>> _reviews;

  /// The guest's own rate. Cached in the service, so this costs one call the
  /// first time Short Stay is opened and nothing after that.
  StayCashbackRate _rate = StayCashbackRate.unknown;

  // ⚠ ADDED 30 September 2026, per Mian — "how do the 4 or 5 pictures
  // display, in demo listing it is only showing 1". The gallery below was
  // already a swipeable PageView over every photo in listing.photos, but it
  // had no dots or any other hint that there was more than one photo to see
  // — so even a listing with several photos read as having just one. This
  // tracks which page the gallery is on so dots can be drawn under it.
  //
  // A ValueNotifier, not setState: setState here would rebuild the WHOLE
  // listing page — map, reviews, days out — on every swipe. Only the dots
  // listen to this.
  final ValueNotifier<int> _photoPage = ValueNotifier<int>(0);

  // ── ⚠ DAYS OUT WERE INVISIBLE UNTIL AFTER YOU BOOKED. 29 August 2026. ─────
  //
  //  StayRoutes.daysOut was pushed from exactly ONE place in the whole app:
  //  15_trip_detail_screen, which a guest reaches only once a booking exists.
  //
  //  So the entire attractions pipeline — the Overpass build, the clustering,
  //  the partner counts, the photographs somebody is now choosing by hand —
  //  was reserved for people who had already committed. The one thing that
  //  answers "why book through GoOuts rather than anywhere else" was being
  //  shown only to people who had already decided.
  //
  //  It belongs here, on the screen where somebody is deciding.
  //
  //  ⚠ COSTS NOTHING EXTRA. forProperty is cached per grid cell in the service,
  //  and a cell covers about 28km by 32km: the second property somebody opens
  //  in Birmingham reads no document at all.
  StayAttractions? _attractions;
  String? _attractionsFor;

  /// ⚠ KEYED ON THE PROPERTY, NOT THE TOWN. It used to be the town name, which
  /// meant two properties in different parts of one city looked identical to
  /// this guard even though they now read different grid cells.
  ///
  /// ⚠ AND IT TAKES THE LISTING, NOT THE ADDRESS. lat and lng live on
  /// StayListing; StayAddress holds only line1, town, postcode and country.
  /// Reaching for listing.address.lat is the obvious guess and it is wrong.
  void _ensureAttractions(StayListing listing) {
    final String key =
        '${listing.lat ?? ''}|${listing.lng ?? ''}|${listing.address.town}';
    if (key == '||') return;
    if (_attractionsFor == key) return;
    _attractionsFor = key;
    StayAttractionsService.instance
        .forProperty(
      lat: listing.lat,
      lng: listing.lng,
      town: listing.address.town,
    )
        .then((StayAttractions? a) {
      if (!mounted) return;
      setState(() => _attractions = a);
    }).catchError((_) {
      // A day out panel that cannot load is a missing panel, not an error on a
      // screen somebody is trying to book from.
      return null;
    });
  }

  @override
  void dispose() {
    _photoPage.dispose();
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
    _listing = _service.byId(widget.listingId);
    _reviews = StayReviewService.instance.forListing(widget.listingId);
    _loadRate();

    // ── ⚠ THE ONLY PLACE A VIEW IS RECORDED. Added 27 August 2026. ──────────
    //
    // "Recently viewed" came back to the home screen when it became real. The
    // obvious place to record was the home screen's own onTap — and that would
    // have been wrong, because it is not the only door.
    //
    // Listings open from the home screen AND from search results. Recording at
    // the tap site means a property found by searching never appears in the
    // history, so the section shows only what was already on the front page —
    // which is the least useful possible version of it.
    //
    // This screen is where a listing is actually looked at, whatever route
    // reached it. Deep links and state restoration land here too.
    //
    // Never awaited and never throws: a browsing convenience must not be able
    // to delay or break opening a property.
    StayRecentlyViewed.instance.record(widget.listingId);
  }

  Future<void> _loadRate() async {
    final StayCashbackRate r =
        await StayBookingService.instance.cashbackRate();
    if (!mounted) return;
    setState(() => _rate = r);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: FutureBuilder<StayListing?>(
        future: _listing,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Center(child: CircularProgressIndicator());
          }

          // An id that does not resolve. Reached by a stale saved listing, a
          // property the host has since removed, or a deep link. Says so
          // rather than showing an empty page with a back button.
          final StayListing? listing = snapshot.data;
          if (snapshot.hasError || listing == null) {
            return const _MessageState(
              icon: Icons.search_off,
              title: 'This property is not available',
              message:
                  'It may have been removed by the host. Please go back and '
                  'choose another one.',
            );
          }

          // ── DESKTOP WEB SPLIT. Added 9 September 2026, same pattern as
          //    01_short_stay_home_screen.dart and food_delivery_screen.dart:
          //    a genuinely separate desktop layout gated on kIsWeb + width,
          //    the mobile layout below is untouched.
          final bool desktop =
              kIsWeb && MediaQuery.of(context).size.width >= 900;
          return desktop
              ? _buildDesktopBody(context, listing)
              : _buildMobileBody(context, listing);
        },
      ),
    );
  }

  // ⚠ ADDED 24 September 2026, per Mian — "listing is not showing properly".
  // Reproduced live: a guest opens a real listing and sees only the price
  // and Check availability button, nothing else — no title, no photos, no
  // description, nothing. There was no visible error anywhere: not in the
  // browser console, not on screen. This screen builds ~15 sections as
  // direct synchronous calls inside one Column's children list
  // (_buildHeader(listing), _buildAboutSection(listing), etc.) — if ANY ONE
  // of them throws for something specific to one listing's data (a field
  // shaped differently than the others, for instance), that single
  // exception takes the WHOLE Column down with it, and a release web build
  // shows nothing at all where debug mode would show Flutter's red error
  // screen. That silence is exactly why this was hard to pin down from the
  // live site.
  //
  // This wraps every section in its own guard. One section failing now
  // costs that section, not the entire page — everything else a guest
  // could still read and still book from keeps working. It also does the
  // one thing that was missing before: logs the label and the real error to
  // the browser console (debugPrint, not swallowed), so if this happens
  // again the exact section and exception are visible in DevTools instead
  // of a page that just looks empty.
  Widget _safe(String label, Widget Function() build) {
    try {
      return build();
    } catch (e, st) {
      debugPrint('ListingDetailScreen: "$label" section failed to build: $e');
      debugPrintStack(stackTrace: st, label: 'ListingDetailScreen/$label');
      return const SizedBox.shrink();
    }
  }

  Widget _buildMobileBody(BuildContext context, StayListing listing) {
    return Stack(
      children: [
        SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              _safe('photoGallery', () => _buildPhotoGallery(listing)),
              Padding(
                padding: const EdgeInsets.all(16),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    _safe('header', () => _buildHeader(listing)),
                    // Stitch puts the host directly under the title,
                    // before the property facts. Hides itself when the
                    // listing carries no host name.
                    _safe('hostRow', () => _buildHostRow(listing)),
                    const SizedBox(height: 16),
                    _safe('factsRow', () => _buildFactsRow(listing)),
                    if (_rate.isKnown) ...[
                      const SizedBox(height: 16),
                      _safe('cashbackRow', () => _buildCashbackRow(listing)),
                    ],
                    const Divider(height: 32),
                    _safe('about', () => _buildAboutSection(listing)),
                    if (listing.amenities.isNotEmpty) ...[
                      const Divider(height: 32),
                      _safe('amenities',
                          () => _buildAmenitiesSection(context, listing)),
                    ],
                    // Hidden entirely until the location engine has run.
                    if (listing.locationContext != null) ...[
                      const Divider(height: 32),
                      _safe(
                          'gettingAround',
                          () => _buildGettingAroundSection(
                              listing.locationContext!)),
                      const SizedBox(height: 20),
                      _safe(
                          'partnerHighlight',
                          () => _buildPartnerHighlightCard(
                              listing.locationContext!)),
                    ],
                    // ⚠ AFTER GETTING AROUND, BEFORE REVIEWS. Transport
                    // then "and here is where you would go" is the order
                    // somebody actually thinks in when planning a trip.
                    // Reviews are about the property; this is about the
                    // days either side of it.
                    _safe('daysOut', () => _buildDaysOutSection(listing)),
                    const Divider(height: 32),
                    _safe('reviews', () => _buildReviewsSection(listing)),
                    // ⚠ ADDED 29 August 2026. It was not on this screen
                    // at all. See the note on the method.
                    _safe('cancellation',
                        () => _buildCancellationSection(listing)),
                    _safe('houseRules', () => _buildHouseRules(listing)),
                    _safe('whereYoullBe', () => _buildWhereYoullBe(listing)),
                    const SizedBox(height: 100), // Space for bottom bar
                  ],
                ),
              ),
            ],
          ),
        ),
        _buildTopButtons(context),
        _buildBottomBar(context, listing),
      ],
    );
  }

  // ── Desktop web ──────────────────────────────────────────────────────────
  //
  // Same content, same section methods, wrapped with a top nav (replacing the
  // mobile back-arrow overlay) and held to a centred 1100px reading column —
  // narrower than the 1400px home pages, because this is a page of prose and
  // photos, not a grid; a full 1400px width would stretch text into
  // unreadably long lines. The sticky booking bar stays full-width along the
  // bottom, its content centred to the same column, matching the "GoOuts is
  // as polished as Airbnb/booking.com" instruction this whole pass is for.
  Widget _buildDesktopBody(BuildContext context, StayListing listing) {
    return Column(
      children: [
        const DesktopTopNav(current: DesktopNavTab.stay),
        Expanded(
          child: Stack(
            children: [
              SingleChildScrollView(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    _safe('photoGallery', () => _buildPhotoGallery(listing)),
                    const SizedBox(height: 8),
                    DesktopCenter(
                      maxWidth: 1100,
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          _safe('header', () => _buildHeader(listing)),
                          _safe('hostRow', () => _buildHostRow(listing)),
                          const SizedBox(height: 16),
                          _safe('factsRow', () => _buildFactsRow(listing)),
                          if (_rate.isKnown) ...[
                            const SizedBox(height: 16),
                            _safe('cashbackRow',
                                () => _buildCashbackRow(listing)),
                          ],
                          const Divider(height: 32),
                          _safe('about', () => _buildAboutSection(listing)),
                          if (listing.amenities.isNotEmpty) ...[
                            const Divider(height: 32),
                            _safe(
                                'amenities',
                                () =>
                                    _buildAmenitiesSection(context, listing)),
                          ],
                          if (listing.locationContext != null) ...[
                            const Divider(height: 32),
                            _safe(
                                'gettingAround',
                                () => _buildGettingAroundSection(
                                    listing.locationContext!)),
                            const SizedBox(height: 20),
                            _safe(
                                'partnerHighlight',
                                () => _buildPartnerHighlightCard(
                                    listing.locationContext!)),
                          ],
                          _safe('daysOut', () => _buildDaysOutSection(listing)),
                          const Divider(height: 32),
                          _safe('reviews', () => _buildReviewsSection(listing)),
                          _safe('cancellation',
                              () => _buildCancellationSection(listing)),
                          _safe('houseRules', () => _buildHouseRules(listing)),
                          _safe('whereYoullBe',
                              () => _buildWhereYoullBe(listing)),
                          const SizedBox(height: 120),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
              // Save (heart) button only — the back-arrow is redundant with
              // the nav bar above, so it is dropped rather than duplicated.
              Positioned(
                top: 20,
                right: 0,
                child: DesktopCenter(
                  maxWidth: 1100,
                  child: Align(
                    alignment: Alignment.topRight,
                    child: StreamBuilder<bool>(
                      stream: _service.watchSaved(widget.listingId),
                      builder: (context, snap) {
                        final bool saved = snap.data ?? false;
                        return CircleAvatar(
                          backgroundColor: Colors.white,
                          child: IconButton(
                            tooltip: saved ? 'Saved' : 'Save this property',
                            icon: Icon(
                              saved ? Icons.favorite : Icons.favorite_border,
                              color: saved
                                  ? GoOutsColors.error
                                  : GoOutsColors.primaryBlue,
                            ),
                            onPressed: () =>
                                _service.setSaved(widget.listingId, !saved),
                          ),
                        );
                      },
                    ),
                  ),
                ),
              ),
              _buildBottomBar(context, listing, desktop: true),
            ],
          ),
        ),
      ],
    );
  }

  // ── Photos ───────────────────────────────────────────────────────────────
  //
  // Was a fixed Unsplash URL. Now the host's own photos, in the order they
  // ordered them, swipeable when there is more than one.
  Widget _buildPhotoGallery(StayListing listing) {
    final List<StayPhoto> photos = List<StayPhoto>.from(listing.photos)
      ..sort((a, b) => a.order.compareTo(b.order));

    if (photos.isEmpty) {
      return Container(
        height: 300,
        width: double.infinity,
        color: GoOutsColors.paleBlueTint,
        child: const Center(
          child: Icon(Icons.home_outlined,
              size: 64, color: GoOutsColors.primaryBlue),
        ),
      );
    }

    return SizedBox(
      height: 300,
      width: double.infinity,
      child: Stack(
        alignment: Alignment.bottomCenter,
        children: [
          PageView.builder(
            itemCount: photos.length,
            onPageChanged: (i) => _photoPage.value = i,
            itemBuilder: (context, i) => Image.network(
              photos[i].url,
              fit: BoxFit.cover,
              // A photo that fails to load must not leave a broken-image glyph
              // across the top of the page.
              errorBuilder: (_, __, ___) => Container(
                color: GoOutsColors.paleBlueTint,
                child: const Center(
                  child: Icon(Icons.image_not_supported_outlined,
                      size: 48, color: GoOutsColors.primaryBlue),
                ),
              ),
              loadingBuilder: (context, child, progress) => progress == null
                  ? child
                  : Container(
                      color: GoOutsColors.paleBlueTint,
                      child: const Center(child: CircularProgressIndicator()),
                    ),
            ),
          ),
          // ⚠ ADDED 30 September 2026. Without this, a multi-photo listing
          // looked identical to a single-photo one — nothing on screen hinted
          // that swiping would reveal more. Only shown when there IS more
          // than one photo, so single-photo listings are unchanged.
          if (photos.length > 1)
            Padding(
              padding: const EdgeInsets.only(bottom: 12),
              child: ValueListenableBuilder<int>(
                valueListenable: _photoPage,
                builder: (context, page, _) => Row(
                  mainAxisSize: MainAxisSize.min,
                  children: List.generate(photos.length, (i) {
                    final bool active = i == page;
                    return AnimatedContainer(
                      duration: const Duration(milliseconds: 200),
                      margin: const EdgeInsets.symmetric(horizontal: 3),
                      width: active ? 18 : 6,
                      height: 6,
                      decoration: BoxDecoration(
                        color: active
                            ? Colors.white
                            : Colors.white.withValues(alpha: 0.5),
                        borderRadius: BorderRadius.circular(3),
                      ),
                    );
                  }),
                ),
              ),
            ),
        ],
      ),
    );
  }

  // ── Back and save ────────────────────────────────────────────────────────
  //
  // The back button had `onPressed: () {}` and the second button was a share
  // icon that did nothing.
  //
  // Share is now save. setSaved/watchSaved already existed on the service and
  // nothing in the app called them, so saving a property was built and
  // unreachable. Sharing needs a link scheme and a landing page that do not
  // exist yet — putting a working control where a dead one was is worth more
  // than keeping the icon.
  Widget _buildTopButtons(BuildContext context) {
    return SafeArea(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            CircleAvatar(
              backgroundColor: Colors.white,
              child: IconButton(
                icon: const Icon(Icons.arrow_back,
                    color: GoOutsColors.primaryBlue),
                onPressed: () => Navigator.of(context).pop(),
              ),
            ),
            StreamBuilder<bool>(
              stream: _service.watchSaved(widget.listingId),
              builder: (context, snap) {
                final bool saved = snap.data ?? false;
                return CircleAvatar(
                  backgroundColor: Colors.white,
                  child: IconButton(
                    tooltip: saved ? 'Saved' : 'Save this property',
                    icon: Icon(
                      saved ? Icons.favorite : Icons.favorite_border,
                      color: saved
                          ? GoOutsColors.error
                          : GoOutsColors.primaryBlue,
                    ),
                    onPressed: () =>
                        _service.setSaved(widget.listingId, !saved),
                  ),
                );
              },
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildHeader(StayListing listing) {
    final String town = listing.address.town;
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          listing.title,
          style: GoogleFonts.inter(
            fontSize: 20,
            fontWeight: FontWeight.w700,
            color: GoOutsColors.deepNavy,
          ),
        ),
        const SizedBox(height: 8),
        Row(
          children: [
            // A new listing has no rating. Showing "0.0" next to a star reads
            // as a bad property rather than an unrated one.
            if (listing.ratingCount > 0) ...[
              const Icon(Icons.star, size: 18, color: GoOutsColors.warning),
              const SizedBox(width: 4),
              Text(
                listing.ratingAvg.toStringAsFixed(1),
                style: GoogleFonts.inter(
                    fontSize: 14, fontWeight: FontWeight.w600),
              ),
              const SizedBox(width: 8),
            ] else ...[
              Text(
                'New',
                style: GoogleFonts.inter(
                    fontSize: 14,
                    fontWeight: FontWeight.w600,
                    color: GoOutsColors.tealSecondary),
              ),
              const SizedBox(width: 8),
            ],
            Expanded(
              child: Text(
                town,
                style: GoogleFonts.inter(
                    fontSize: 13.5, color: GoOutsColors.bodyText),
                overflow: TextOverflow.ellipsis,
              ),
            ),
          ],
        ),
      ],
    );
  }

  // ── Who you are staying with ──────────────────────────────────────────────
  //
  // ⚠ THIS ROW IS BACK. Added 27 August 2026: "host profile is missing
  // completely".
  //
  // It was removed on 3 August for a good reason, recorded below in the
  // occupancy note: the listing carried no host name and the guest cannot read
  // /stay_hosts, because that record holds KYC evidence and payout details and
  // the rule correctly says owner or admin only.
  //
  // The fix was not to relax that rule. createStayListing now copies a first
  // name and a joining year onto the listing itself, on the server, where a
  // client cannot forge them. See StayListing.host.
  //
  // ⚠ HIDES ITSELF WHEN THERE IS NO NAME. Every listing created before today
  // has no host block, and "Hosted by" above a blank space is worse than no
  // row at all.
  //
  // ⚠ NO "SUPERHOST" AND NO "5 YEARS EXPERIENCE". Stitch drew both. Neither is
  // computed anywhere, and a badge nobody can earn is worse than no badge.
  Widget _buildHostRow(StayListing listing) {
    final StayHostSummary h = listing.host;
    if (!h.hasName) return const SizedBox.shrink();

    return Padding(
      padding: const EdgeInsets.only(top: 16),
      child: Row(
        children: <Widget>[
          CircleAvatar(
            radius: 20,
            backgroundColor: GoOutsColors.paleBlueTint,
            backgroundImage:
                h.photoUrl.isEmpty ? null : NetworkImage(h.photoUrl),
            child: h.photoUrl.isEmpty
                ? Text(h.initial,
                    style: GoogleFonts.inter(
                        fontSize: 15,
                        fontWeight: FontWeight.w700,
                        color: GoOutsColors.primaryBlue))
                : null,
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                Text('Hosted by ${h.name}',
                    style: GoogleFonts.inter(
                        fontSize: 14,
                        height: 20 / 14,
                        fontWeight: FontWeight.w600,
                        color: GoOutsColors.deepNavy)),
                // Only when the year is real. Nothing here guesses a tenure.
                if (h.hasSince)
                  Text('Host since ${h.since}',
                      style: GoogleFonts.inter(
                          fontSize: 12,
                          height: 16 / 12,
                          color: GoOutsColors.bodyText)),
              ],
            ),
          ),
        ],
      ),
    );
  }

  // ── Occupancy ────────────────────────────────────────────────────────────
  //
  // Replaced the "Hosted by Sarah, Superhost, 5 years experience" row when the
  // host name was unavailable. The occupancy facts stay because they are what
  // a booking actually turns on; the host row above now sits alongside them.
  Widget _buildFactsRow(StayListing listing) {
    // Via the catalogue, not by capitalising the slug: that would print
    // "Flat" and "Annexe" where a guest should read "Flat or apartment" and
    // "Annexe or outbuilding".
    final String propertyType = stayPropertyTypeLabel(listing.propertyType);

    return Wrap(
      spacing: 16,
      runSpacing: 8,
      children: [
        _fact(Icons.home_outlined, propertyType),
        _fact(Icons.person_outline, _plural(listing.maxGuests, 'guest')),
        _fact(Icons.meeting_room_outlined,
            _plural(listing.bedrooms, 'bedroom')),
        _fact(Icons.bed_outlined, _plural(listing.beds, 'bed')),
        _fact(Icons.bathtub_outlined,
            _plural(listing.bathrooms, 'bathroom')),
      ],
    );
  }

  Widget _fact(IconData icon, String label) => Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(icon, size: 18, color: GoOutsColors.tealSecondary),
          const SizedBox(width: 6),
          Text(label,
              style: GoogleFonts.inter(
                  fontSize: 14, color: GoOutsColors.bodyText)),
        ],
      );

  static String _plural(int n, String word) =>
      '$n $word${n == 1 ? '' : 's'}';

  // ── Cashback ─────────────────────────────────────────────────────────────
  //
  // Shown per NIGHT, not as a total, because no dates have been chosen yet and
  // a total would have to invent a length of stay. The exact figure for the
  // real dates comes from getStayQuote on the checkout screen.
  //
  // "at least" because Plus members earn more, and because the quote is the
  // authority. Understating here and settling up at checkout is the safe
  // direction to be wrong in.
  Widget _buildCashbackRow(StayListing listing) {
    final int perNightPence =
        ((listing.nightlyRate.value * _rate.pct) / 100).round();
    if (perNightPence <= 0) return const SizedBox.shrink();

    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
      decoration: BoxDecoration(
        color: GoOutsColors.tealSecondary.withValues(alpha: 0.10),
        borderRadius: BorderRadius.circular(10),
      ),
      child: Row(
        children: [
          const Icon(Icons.savings_outlined,
              size: 20, color: GoOutsColors.tealSecondary),
          const SizedBox(width: 10),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'Earn ${_rate.label} back — about '
                  '${Pence(perNightPence).compact} a night',
                  style: GoogleFonts.inter(
                    fontSize: 14,
                    fontWeight: FontWeight.w600,
                    color: GoOutsColors.deepNavy,
                  ),
                ),
                if (_rate.note.isNotEmpty)
                  Text(
                    _rate.note,
                    style: GoogleFonts.inter(
                        fontSize: 12, color: GoOutsColors.bodyText),
                  ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildAboutSection(StayListing listing) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          'About this place',
          style: GoogleFonts.inter(
            fontSize: 15,
            fontWeight: FontWeight.w700,
            color: GoOutsColors.deepNavy,
          ),
        ),
        const SizedBox(height: 12),
        Text(
          listing.description.trim().isEmpty
              ? 'The host has not added a description yet.'
              : listing.description,
          style: GoogleFonts.inter(
            fontSize: 15,
            height: 1.5,
            color: GoOutsColors.bodyText,
          ),
        ),
      ],
    );
  }

  // ── Amenities ────────────────────────────────────────────────────────────
  //
  // Was six hardcoded rows and a button reading "Show all 34 amenities" that
  // did nothing. Now the property's own amenities, capped at six with the
  // button appearing only when there are more, and the count comes from the
  // catalogue rather than being typed in.
  Widget _buildAmenitiesSection(BuildContext context, StayListing listing) {
    final List<StayAmenity> shown = listing.amenities
        .take(6)
        .map(stayAmenityFor)
        .toList(growable: false);

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // ⚠ "Amenities", not "What this place offers". Corrected 27 Aug 2026.
        //
        // Stitch labels this section "Amenities" and the full list screen it
        // opens is "All amenities". Renaming it in the build gave the guest
        // three different words for one thing across two screens, and the
        // button underneath still says "Show all 34 amenities", which read as
        // though it opened something else.
        Text(
          'Amenities',
          style: GoogleFonts.inter(
            fontSize: 15,
            height: 20 / 15,
            fontWeight: FontWeight.w700,
            letterSpacing: 0.3,
            color: GoOutsColors.deepNavy,
          ),
        ),
        const SizedBox(height: 16),
        GridView.builder(
          shrinkWrap: true,
          physics: const NeverScrollableScrollPhysics(),
          gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
            crossAxisCount: 2,
            mainAxisExtent: 40,
            crossAxisSpacing: 16,
            mainAxisSpacing: 16,
          ),
          itemCount: shown.length,
          itemBuilder: (context, index) {
            return Row(
              children: [
                // Stitch draws these at roughly 20px against body text. Ours
                // were 24px icons against 15px labels, which made the grid
                // read as six buttons rather than a list of facts.
                Icon(shown[index].icon,
                    color: GoOutsColors.tealSecondary, size: 20),
                const SizedBox(width: 12),
                Expanded(
                  child: Text(
                    shown[index].label,
                    style: GoogleFonts.inter(
                        fontSize: 13.5,
                        height: 20 / 13.5,
                        color: GoOutsColors.deepNavy),
                    overflow: TextOverflow.ellipsis,
                  ),
                ),
              ],
            );
          },
        ),
        if (listing.amenities.length > 6) ...[
          const SizedBox(height: 24),
          OutlinedButton(
            onPressed: () => Navigator.of(context).pushNamed(
              StayRoutes.amenities,
              arguments: <String, dynamic>{'listingId': listing.id},
            ),
            style: OutlinedButton.styleFrom(
              minimumSize: const Size(double.infinity, 52),
              shape:
                  RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
              side: const BorderSide(color: GoOutsColors.deepNavy),
            ),
            child: Text(
              'Show all ${listing.amenities.length} amenities',
              style: GoogleFonts.inter(
                  color: GoOutsColors.deepNavy, fontWeight: FontWeight.w600),
            ),
          ),
        ],
      ],
    );
  }

  // ── Getting around ───────────────────────────────────────────────────────
  //
  // Every figure here comes from the location engine (task #114), which
  // computes it from the property's real postcode.
  Widget _buildGettingAroundSection(StayLocationContext ctx) {
    final List<StayStation> stations = ctx.stations.take(3).toList();

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          'Getting around',
          style: GoogleFonts.inter(
            fontSize: 15,
            fontWeight: FontWeight.w700,
            color: GoOutsColors.deepNavy,
          ),
        ),
        const SizedBox(height: 12),
        if (ctx.centreName.isNotEmpty)
          Text(
            '${_miles(ctx.distanceToCentreMi)} from ${ctx.centreName}',
            style:
                GoogleFonts.inter(fontSize: 15, color: GoOutsColors.bodyText),
          ),
        if (stations.isNotEmpty) ...[
          const SizedBox(height: 16),
          for (final s in stations) _buildStationItem(s),
          const SizedBox(height: 8),
          Text(
            'Distances are calculated from the property address',
            style: GoogleFonts.inter(
                fontSize: 12,
                fontStyle: FontStyle.italic,
                color: GoOutsColors.bodyText),
          ),
        ],
      ],
    );
  }

  static String _miles(double mi) =>
      '${mi.toStringAsFixed(1)} ${mi == 1.0 ? 'mile' : 'miles'}';

  Widget _buildStationItem(StayStation station) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 12),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Icon(Icons.train, color: GoOutsColors.primaryBlue, size: 20),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(station.name,
                    style: GoogleFonts.inter(
                        fontSize: 15, fontWeight: FontWeight.w600)),
                if (station.lines.isNotEmpty)
                  Text(station.lines.join(', '),
                      style: GoogleFonts.inter(
                          fontSize: 13.5, color: GoOutsColors.bodyText)),
                Text('${_miles(station.walkMi)} walking',
                    style: GoogleFonts.inter(
                        fontSize: 13.5, fontWeight: FontWeight.w500)),
              ],
            ),
          ),
        ],
      ),
    );
  }

  // ── The GoOuts difference ────────────────────────────────────────────────
  //
  // The one thing on this screen no competitor can show, so it must be true.
  // Counts come from partnerCounts, and the breakdown is built from the
  // categories actually present rather than the fixed "6 restaurants, 3 pubs,
  // 2 cafes, 3 shops" that used to be printed under every property.
  Widget _buildPartnerHighlightCard(StayLocationContext ctx) {
    final int half = ctx.partnerCounts.halfMile;
    if (half <= 0) return const SizedBox.shrink();

    final List<MapEntry<String, int>> byCategory =
        ctx.partnerCounts.byCategory.entries.where((e) => e.value > 0).toList()
          ..sort((a, b) => b.value.compareTo(a.value));

    final String breakdown = byCategory
        .take(4)
        .map((e) => '${e.value} ${e.key}')
        .join(', ');

    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: GoOutsColors.primaryBlue,
        borderRadius: BorderRadius.circular(12),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            '$half GoOuts ${half == 1 ? 'partner' : 'partners'} '
            'within half a mile',
            style: GoogleFonts.inter(
              fontSize: 15,
              fontWeight: FontWeight.w700,
              color: Colors.white,
            ),
          ),
          if (breakdown.isNotEmpty) ...[
            const SizedBox(height: 12),
            Text(
              breakdown,
              style: GoogleFonts.inter(
                  fontSize: 15, color: Colors.white.withValues(alpha: 0.9)),
            ),
          ],
          const SizedBox(height: 12),
          Text(
            'Earn cashback at every one',
            style: GoogleFonts.inter(
              fontSize: 15,
              fontWeight: FontWeight.w600,
              color: Colors.white,
            ),
          ),
        ],
      ),
    );
  }

  // ── Reviews ──────────────────────────────────────────────────────────────
  //
  // Was one invented review from "Emma • July 2024" shown on every property.
  //
  // ⚠ REAL AS OF 29 August 2026. Reviews are now written by real guests after
  // a stay, through screen 25 and functions/stay_reviews.js. Until that day
  // NOTHING ON THE PLATFORM COULD CREATE ONE — this section, the rating chip
  // on screen 02 and the "Rating" sort order were all reading a subcollection
  // that only the demo seed had ever written to, so every genuinely listed
  // property was going to sit at zero stars for ever.
  // ── Cancellation ─────────────────────────────────────────────────────────
  //
  //  ⚠ THIS SCREEN DID NOT MENTION CANCELLATION AT ALL until 29 August 2026.
  //
  //  Every listing carries a cancellationPolicy, the host chooses it in step 7
  //  of the wizard, there is a whole refund engine behind it — quoteStayCancellation,
  //  cancelStayBooking, screens 28 and 29 — and a guest deciding to spend £165
  //  a night could not find out whether they could get any of it back. They
  //  learned the policy AFTER booking, on the cancel screen.
  //
  //  ⚠ NO PERCENTAGES AND NO DATES HERE, DELIBERATELY. The tiers live in
  //  platform_config/short_stay and are read SERVER side; the enum's own
  //  comment says "a refund amount is NEVER computed on the client". Printing
  //  "free until 48 hours before" from a client that does not hold the numbers
  //  is how a screen ends up contradicting the refund it later gives.
  //
  //  So this names the policy and says where the real figure comes from. The
  //  exact amount appears on screen 28, quoted by the server, before anybody
  //  confirms anything.

  Widget _buildCancellationSection(StayListing listing) {
    final CancellationPolicy p = listing.cancellationPolicy;
    final (IconData icon, String meaning) = switch (p) {
      CancellationPolicy.flexible => (
          Icons.event_available_outlined,
          'The most forgiving of the three. Cancel well before you arrive and '
              'you get the most back.',
        ),
      CancellationPolicy.moderate => (
          Icons.event_note_outlined,
          'A middle tier. How much comes back depends on how close to arrival '
              'you cancel.',
        ),
      CancellationPolicy.strict => (
          Icons.event_busy_outlined,
          'The firmest of the three. Cancelling close to arrival returns '
              'little or nothing.',
        ),
    };

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const Divider(height: 32),
        Text(
          'Cancellation',
          style: GoogleFonts.inter(
              fontSize: 15,
              height: 20 / 15,
              fontWeight: FontWeight.w700,
              letterSpacing: 0.3,
              color: GoOutsColors.deepNavy),
        ),
        const SizedBox(height: 12),
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Icon(icon, size: 20, color: GoOutsColors.tealSecondary),
            const SizedBox(width: 12),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    '${p.label} cancellation',
                    style: GoogleFonts.inter(
                        fontSize: 14,
                        height: 20 / 14,
                        fontWeight: FontWeight.w600,
                        color: GoOutsColors.deepNavy),
                  ),
                  const SizedBox(height: 2),
                  Text(
                    meaning,
                    style: GoogleFonts.inter(
                        fontSize: 13.5,
                        height: 1.45,
                        color: GoOutsColors.bodyText),
                  ),
                  const SizedBox(height: 6),
                  Text(
                    // ⚠ SAYS WHERE THE REAL NUMBER COMES FROM rather than
                    // guessing at it. See the note above.
                    'You will see exactly what is refundable, to the penny, '
                    'before you confirm anything.',
                    style: GoogleFonts.inter(
                        fontSize: 12,
                        height: 1.45,
                        color: GoOutsColors.bodyText),
                  ),
                ],
              ),
            ),
          ],
        ),
      ],
    );
  }

  // ── Days out ─────────────────────────────────────────────────────────────
  //
  //  See the note on _attractions. This was reachable only after booking.
  //
  //  ⚠ RENDERS NOTHING AT ALL WHEN THE CITY IS NOT BUILT, rather than an empty
  //  "Days out" heading. On a screen somebody is deciding to spend money from,
  //  a section that announces itself and then has nothing in it reads as a
  //  broken app, and a plain absence reads as nothing.
  Widget _buildDaysOutSection(StayListing listing) {
    _ensureAttractions(listing);

    final StayAttractions? a = _attractions;
    if (a == null || a.clusters.isEmpty) return const SizedBox.shrink();

    final List<StayCluster> nearest = StayAttractionsService.nearest(
      a.clusters,
      listing.lat,
      listing.lng,
    ).take(3).toList();
    if (nearest.isEmpty) return const SizedBox.shrink();

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const Divider(height: 32),
        Row(
          children: [
            Expanded(
              child: Text(
                'Days out from here',
                style: GoogleFonts.inter(
                    fontSize: 15,
                    fontWeight: FontWeight.w700,
                    color: GoOutsColors.deepNavy),
              ),
            ),
            if (a.clusters.length > nearest.length)
              TextButton(
                onPressed: () => Navigator.of(context).pushNamed(
                  StayRoutes.daysOut,
                  arguments: <String, dynamic>{
                    'listingId': listing.id,
                    // Browsing, not travelling. Lights Search rather than
                    // Trips on the bottom bar of the screens beyond this one.
                    'fromListing': true,
                  },
                ),
                style: TextButton.styleFrom(
                  padding: const EdgeInsets.symmetric(horizontal: 8),
                  minimumSize: const Size(0, 32),
                ),
                child: Text('See all ${a.clusters.length}',
                    style: GoogleFonts.inter(
                        fontSize: 13.5,
                        fontWeight: FontWeight.w600,
                        color: GoOutsColors.primaryBlue)),
              ),
          ],
        ),
        const SizedBox(height: 4),
        Text(
          // ⚠ MILES, NEVER MINUTES. Same rule as screens 07, 08 and 09: we
          // have no routing API, so a journey time would be invented on a
          // screen somebody plans an afternoon around.
          'Grouped by what you can do in one trip, nearest first.',
          style: GoogleFonts.inter(
              fontSize: 13.5, height: 1.4, color: GoOutsColors.bodyText),
        ),
        const SizedBox(height: 12),
        SizedBox(
          height: 176,
          child: ListView.separated(
            scrollDirection: Axis.horizontal,
            itemCount: nearest.length,
            separatorBuilder: (_, __) => const SizedBox(width: 12),
            itemBuilder: (_, i) => _daysOutCard(listing, nearest[i]),
          ),
        ),
      ],
    );
  }

  Widget _daysOutCard(StayListing listing, StayCluster c) {
    final double? mi = (listing.lat != null && listing.lng != null)
        ? StayAttractionsService.milesBetween(
            listing.lat!, listing.lng!, c.lat, c.lng)
        : null;

    return SizedBox(
      width: 208,
      child: Material(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
        clipBehavior: Clip.antiAlias,
        child: InkWell(
          onTap: () => Navigator.of(context).pushNamed(
            StayRoutes.cluster,
            arguments: <String, dynamic>{
              'listingId': listing.id,
              'clusterId': c.id,
              'fromListing': true,
            },
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              SizedBox(
                height: 96,
                width: double.infinity,
                child: c.photo == null
                    ? Container(
                        color: GoOutsColors.dividerGray,
                        child: const Icon(Icons.museum_outlined,
                            color: GoOutsColors.outlineVariant),
                      )
                    : Image.network(
                        c.photo!.url,
                        fit: BoxFit.cover,
                        cacheWidth: 440,
                        errorBuilder: (_, __, ___) => Container(
                          color: GoOutsColors.dividerGray,
                          child: const Icon(Icons.museum_outlined,
                              color: GoOutsColors.outlineVariant),
                        ),
                      ),
              ),
              Padding(
                padding: const EdgeInsets.all(10),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      c.name,
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                      style: GoogleFonts.inter(
                          fontSize: 14,
                          fontWeight: FontWeight.w600,
                          color: GoOutsColors.deepNavy),
                    ),
                    const SizedBox(height: 2),
                    Text(
                      <String>[
                        if (mi != null) '${mi.toStringAsFixed(1)} miles',
                        if (c.partnerCount > 0)
                          '${c.partnerCount} partners',
                      ].join('  ·  '),
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                      style: GoogleFonts.inter(
                          fontSize: 12, color: GoOutsColors.bodyText),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildReviewsSection(StayListing listing) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            const Icon(Icons.star, color: GoOutsColors.warning, size: 20),
            const SizedBox(width: 8),
            Text(
              listing.ratingCount > 0
                  ? '${listing.ratingAvg.toStringAsFixed(1)} • '
                      '${_plural(listing.ratingCount, 'review')}'
                  : 'Reviews',
              style:
                  GoogleFonts.inter(fontSize: 15, fontWeight: FontWeight.w700),
            ),
          ],
        ),
        _categoryBreakdown(listing),
        const SizedBox(height: 8),
        FutureBuilder<List<StayReview>>(
          future: _reviews,
          builder: (context, snap) {
            if (snap.connectionState == ConnectionState.waiting) {
              return const Padding(
                padding: EdgeInsets.symmetric(vertical: 16),
                child: Center(child: CircularProgressIndicator()),
              );
            }
            final List<StayReview> reviews =
                snap.data ?? const <StayReview>[];
            if (reviews.isEmpty) {
              return Padding(
                padding: const EdgeInsets.symmetric(vertical: 8),
                child: Text(
                  'No reviews yet. Be the first to stay here.',
                  style: GoogleFonts.inter(
                      fontSize: 15, color: GoOutsColors.bodyText),
                ),
              );
            }
            return Column(
              children: [
                for (final r in reviews) _reviewTile(r),
              ],
            );
          },
        ),
      ],
    );
  }

  /// The six category averages, as bars.
  ///
  /// ⚠ THIS EXISTS BECAUSE THE DATA DOES. submitStayReview aggregates the six
  /// sub scores onto the listing, and screen 25 asks a guest for all six. Had
  /// nothing displayed them, this would have been the fourth thing in Short
  /// Stay collected from a person and then never shown to anybody — which is
  /// the pattern the whole review loop was found by.
  ///
  /// ⚠ SKIPS A CATEGORY WITH TOO FEW ANSWERS rather than showing it at zero.
  /// The scores are optional; one guest who disliked the parking must not put
  /// "Location 2.0" under a property nobody else remarked on.
  Widget _categoryBreakdown(StayListing listing) {
    final Map<String, StayCategoryRating> cats = listing.ratingCategories;
    final List<MapEntry<String, String>> shown = _categoryLabels.entries
        .where((e) => cats[e.key]?.hasEnough == true)
        .toList();
    if (shown.isEmpty) return const SizedBox.shrink();

    return Padding(
      padding: const EdgeInsets.only(top: 12),
      child: Column(
        children: [
          for (final MapEntry<String, String> e in shown)
            Padding(
              padding: const EdgeInsets.symmetric(vertical: 3),
              child: Row(
                children: [
                  SizedBox(
                    width: 110,
                    child: Text(e.value,
                        style: GoogleFonts.inter(
                            fontSize: 13.5, color: GoOutsColors.bodyText)),
                  ),
                  Expanded(
                    child: ClipRRect(
                      borderRadius: BorderRadius.circular(3),
                      child: LinearProgressIndicator(
                        value: cats[e.key]!.avg / 5,
                        minHeight: 5,
                        backgroundColor: GoOutsColors.dividerGray,
                        valueColor: const AlwaysStoppedAnimation<Color>(
                            GoOutsColors.primaryBlue),
                      ),
                    ),
                  ),
                  const SizedBox(width: 10),
                  SizedBox(
                    width: 26,
                    child: Text(
                      cats[e.key]!.avg.toStringAsFixed(1),
                      textAlign: TextAlign.right,
                      style: GoogleFonts.inter(
                          fontSize: 13.5,
                          fontWeight: FontWeight.w600,
                          color: GoOutsColors.deepNavy),
                    ),
                  ),
                ],
              ),
            ),
        ],
      ),
    );
  }

  /// ⚠ THE KEYS MATCH stay_reviews.js CATEGORIES AND screen 25's
  /// kReviewCategories. Three places, one list. A seventh category added to
  /// the form without being added here is collected and never shown.
  static const Map<String, String> _categoryLabels = <String, String>{
    'cleanliness': 'Cleanliness',
    'accuracy': 'Accuracy',
    'checkIn': 'Check in',
    'communication': 'Communication',
    'location': 'Location',
    'value': 'Value',
  };

  /// ⚠ NOW SHOWS THE STARS. This tile rendered a name, a month and the text
  /// and never once drew the rating, on the screen whose whole heading is
  /// "4.8 · 12 reviews". A reader could see the average and could read the
  /// words, and could not tell which review was the two.
  Widget _reviewTile(StayReview r) {
    final String subtitle = r.createdAt == null
        ? r.guestName
        : '${r.guestName} • ${_monthYear(r.createdAt!)}';

    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 10),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const CircleAvatar(
              radius: 18, backgroundColor: GoOutsColors.paleBlueTint),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(subtitle,
                    style: GoogleFonts.inter(
                        fontSize: 14,
                        fontWeight: FontWeight.w600,
                        color: GoOutsColors.deepNavy)),
                const SizedBox(height: 2),
                Row(
                  children: [
                    for (int i = 1; i <= 5; i++)
                      Icon(
                        i <= r.rating
                            ? Icons.star_rounded
                            : Icons.star_border_rounded,
                        size: 14,
                        color: i <= r.rating
                            ? GoOutsColors.warning
                            : GoOutsColors.starGray,
                      ),
                  ],
                ),
                if (r.hasComment) ...[
                  const SizedBox(height: 4),
                  Text(r.comment,
                      style: GoogleFonts.inter(
                          fontSize: 13.5,
                          height: 20 / 13.5,
                          color: GoOutsColors.bodyText)),
                ],
              ],
            ),
          ),
        ],
      ),
    );
  }

  static const List<String> _months = <String>[
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December',
  ];

  static String _monthYear(DateTime d) =>
      '${_months[d.month - 1]} ${d.year}';

  // ── House rules, check-in and check-out ───────────────────────────────────
  //
  // ⚠ ADDED 27 August 2026: "there is no rules shows to consumer check in and
  // check out".
  //
  // Nothing anywhere in the product carried these. The Stitch GUEST screens
  // displayed them — trip detail draws "Check in 15:00 / Check out 11:00" and a
  // House rules row — but no Stitch HOST screen ever asked for them. Stitch's
  // host step 7 is called "pricing_rules" and its rules are the CANCELLATION
  // policy. So the design showed guest data the design never collected, and
  // 15_trip_detail_screen.dart recorded exactly that on 17 August and left the
  // section out rather than invent a check-in time for somebody's holiday.
  //
  // Fixed at the source: host wizard step 7 now captures it, createStayListing
  // validates and stores it, StayListing parses it with the UK norm as the
  // default for every listing written before today.
  //
  // ⚠ SHOWN BEFORE BOOKING, ON PURPOSE. "No pets" is something a guest needs
  // while they are deciding, not an unpleasant surprise on the confirmation.
  //
  // ⚠ arrivalInstructions IS DELIBERATELY NOT HERE. Door codes and key safe
  // locations belong to a confirmed booking, not to a public listing page that
  // anybody can open.
  Widget _buildHouseRules(StayListing listing) {
    final StayHouseRules r = listing.houseRules;

    TextStyle head() => GoogleFonts.inter(
        fontSize: 15,
        height: 20 / 15,
        fontWeight: FontWeight.w700,
        letterSpacing: 0.3,
        color: GoOutsColors.deepNavy);

    Widget row(IconData icon, String label, String value, {Color? tone}) =>
        Padding(
          padding: const EdgeInsets.only(bottom: 10),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Icon(icon, size: 18, color: tone ?? GoOutsColors.primaryBlue),
              const SizedBox(width: 12),
              Expanded(
                child: Text(label,
                    style: GoogleFonts.inter(
                        fontSize: 13.5,
                        height: 20 / 13.5,
                        color: GoOutsColors.bodyText)),
              ),
              Text(value,
                  style: GoogleFonts.inter(
                      fontSize: 14,
                      height: 20 / 14,
                      fontWeight: FontWeight.w600,
                      color: tone ?? GoOutsColors.deepNavy)),
            ],
          ),
        );

    // A permission the host has NOT granted is the ordinary case and is drawn
    // plainly. Only what they HAVE allowed is worth colouring, because that is
    // the surprising, useful information.
    Widget permission(IconData icon, String label, bool allowed) => row(
          icon,
          label,
          allowed ? 'Allowed' : 'Not allowed',
          tone: allowed ? GoOutsColors.success : GoOutsColors.bodyText,
        );

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        const Divider(height: 32),
        Text('House rules', style: head()),
        const SizedBox(height: 12),

        // Always shown. Every listing has these two, defaulted to the UK norm
        // when the host left the step alone, so there is no empty state.
        row(Icons.login_rounded, 'Check-in from', listing.checkInTime),
        row(Icons.logout_rounded, 'Check-out by', listing.checkOutTime),

        // Hidden entirely when the host said nothing beyond the defaults.
        // Printing three "Not allowed" lines a host never actually chose would
        // put words in their mouth.
        if (!r.isUnset) ...<Widget>[
          const SizedBox(height: 2),
          permission(Icons.smoking_rooms_outlined, 'Smoking',
              r.smokingAllowed),
          permission(Icons.pets_outlined, 'Pets', r.petsAllowed),
          permission(Icons.celebration_outlined, 'Parties or events',
              r.partiesAllowed),
          if (r.hasQuietHours)
            row(Icons.bedtime_outlined, 'Quiet hours',
                '${r.quietHoursFrom} – ${r.quietHoursTo}'),
          if (r.additional.isNotEmpty) ...<Widget>[
            const SizedBox(height: 4),
            Text(r.additional,
                style: GoogleFonts.inter(
                    fontSize: 13.5,
                    height: 20 / 13.5,
                    color: GoOutsColors.bodyText)),
          ],
        ],
      ],
    );
  }

  // ── "Where you'll be" ─────────────────────────────────────────────────────
  //
  // ⚠ THIS SECTION WAS NEVER BUILT. Added 27 August 2026, reported as "there is
  // no map showing in the listing".
  //
  // Stitch draws it between Reviews and the booking bar, captioned with the
  // town. Every other section on this screen was built — gallery, about,
  // amenities, getting around, partner highlight, reviews — and this one was
  // simply skipped. The coordinates were already on the model (`lat`, `lng`,
  // both nullable), already parsed from the `geo` map, and nothing read them.
  //
  // The only GoogleMap in the entire Short Stay feature was on screen 04.
  //
  // ── ⚠ A CIRCLE, NOT A PIN. THIS IS DELIBERATE. ──────────────────────────────
  //
  // The exact address of somebody's home is not shown to a person who has not
  // booked it. This draws a 300m circle around the property and NO marker, so
  // the guest learns the area — which is what they are actually deciding on —
  // without the screen publishing where a host lives to anyone who opens a
  // listing. Every established stay platform does exactly this, and reversing
  // it would be a host-safety problem, not a design tweak.
  //
  // ── ⚠ THE MAP IS DEAD. NO GESTURES, NO CONTROLLER, NO DISPOSE. ─────────────
  //
  // 04_map_results carries a rule at the top of the file: "ONE GoogleMap alive
  // at a time across the whole Short Stay feature, and the controller is
  // disposed". A live, gesture-enabled map inside a scrolling list would break
  // that rule AND fight the ListView for vertical drags.
  //
  // So: every gesture flag off, no onMapCreated, no controller held, therefore
  // nothing to dispose. Lite mode on Android renders it as a static bitmap,
  // which is far cheaper again. Tapping opens the neighbourhood screen, which
  // is the interactive one.
  Widget _buildWhereYoullBe(StayListing listing) {
    final double? lat = listing.lat;
    final double? lng = listing.lng;

    // Hidden entirely when the property has no coordinates. An empty grey box
    // captioned "Where you'll be" is worse than no section: it reads as a
    // failure to load rather than as an absence of data.
    if (lat == null || lng == null) return const SizedBox.shrink();

    final LatLng centre = LatLng(lat, lng);

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        const Divider(height: 32),
        Text(
          "Where you'll be",
          style: GoogleFonts.inter(
            fontSize: 15,
            height: 20 / 15,
            fontWeight: FontWeight.w700,
            letterSpacing: 0.3,
            color: GoOutsColors.deepNavy,
          ),
        ),
        const SizedBox(height: 12),
        ClipRRect(
          borderRadius: BorderRadius.circular(12),
          child: SizedBox(
            height: 180,
            width: double.infinity,
            child: Stack(
              children: <Widget>[
                GoogleMap(
                  initialCameraPosition:
                      CameraPosition(target: centre, zoom: 14),
                  // Android only. Renders a non-interactive bitmap instead of a
                  // full map surface — a fraction of the memory and no texture
                  // for the ListView to composite on every frame.
                  liteModeEnabled: Theme.of(context).platform ==
                      TargetPlatform.android,
                  circles: <Circle>{
                    Circle(
                      circleId: const CircleId('approx'),
                      center: centre,
                      radius: 300,
                      fillColor:
                          GoOutsColors.primaryBlue.withValues(alpha: 0.18),
                      strokeColor: GoOutsColors.primaryBlue,
                      strokeWidth: 2,
                    ),
                  },
                  // ⚠ Everything off. See the note above about the ListView.
                  zoomControlsEnabled: false,
                  zoomGesturesEnabled: false,
                  scrollGesturesEnabled: false,
                  rotateGesturesEnabled: false,
                  tiltGesturesEnabled: false,
                  myLocationButtonEnabled: false,
                  myLocationEnabled: false,
                  mapToolbarEnabled: false,
                  compassEnabled: false,
                ),
                // ── ⚠ NOW TAPPABLE. 29 August 2026. ────────────────────────
                //
                // This carried a note saying there was deliberately no tap
                // handler, because StayRoutes.neighbourhood resolved to
                // `const NeighbourhoodScreen()` — no listingId, in front of an
                // Unsplash photograph with fake pins on it — so tapping would
                // have sent a guest to an empty screen about nowhere.
                //
                // The note ended "wire this when that screen takes a property".
                // It does now, and this is the most valuable place to open it
                // from: a guest deciding BETWEEN properties is exactly who
                // cares which one has fourteen cashback partners round it.
                //
                // ⚠ A TRANSPARENT OVERLAY, not onTap on the map. Every gesture
                // on this GoogleMap is disabled so it reads as a picture, and a
                // disabled map still swallows taps aimed at it.
                Positioned.fill(
                  child: Material(
                    color: Colors.transparent,
                    child: InkWell(
                      onTap: () => Navigator.of(context).pushNamed(
                        StayRoutes.neighbourhood,
                        arguments: <String, dynamic>{
                          'listingId': widget.listingId,
                        },
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
        const SizedBox(height: 8),
        Text(
          listing.address.publicLabel,
          style: GoogleFonts.inter(
            fontSize: 14,
            height: 20 / 14,
            fontWeight: FontWeight.w600,
            color: GoOutsColors.deepNavy,
          ),
        ),
        const SizedBox(height: 2),
        Text(
          'Exact address is shared once your booking is confirmed.',
          style: GoogleFonts.inter(
            fontSize: 12,
            height: 16 / 12,
            fontWeight: FontWeight.w500,
            color: GoOutsColors.bodyText,
          ),
        ),
      ],
    );
  }

  // ── Bottom bar ───────────────────────────────────────────────────────────
  //
  // Was "£112 nightly / 12 to 14 July" with an empty onPressed. The price is
  // now the property's own; the dates line is gone because no dates have been
  // chosen at this point — choosing them is what the button is for.
  Widget _buildBottomBar(BuildContext context, StayListing listing,
      {bool desktop = false}) {
    final Pence rate = listing.nightlyRate;

    final Widget row = Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              '${rate.compact} nightly',
              style: GoogleFonts.inter(
                  fontSize: 16, fontWeight: FontWeight.w700),
            ),
            if (!listing.cleaningFee.isZero)
              Text(
                '${listing.cleaningFee.compact} cleaning fee',
                style: GoogleFonts.inter(
                    fontSize: 14, color: GoOutsColors.bodyText),
              ),
          ],
        ),
        ElevatedButton(
          onPressed: () => Navigator.of(context).pushNamed(
            StayRoutes.bookingDates,
            arguments: <String, dynamic>{'listingId': listing.id},
          ),
          style: ElevatedButton.styleFrom(
            backgroundColor: GoOutsColors.primaryBlue,
            minimumSize: const Size(180, 52),
            shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(12)),
          ),
          child: Text(
            'Check availability',
            style: GoogleFonts.inter(
                fontSize: 16,
                fontWeight: FontWeight.w600,
                color: Colors.white),
          ),
        ),
      ],
    );

    return Align(
      alignment: Alignment.bottomCenter,
      child: Container(
        padding: EdgeInsets.symmetric(
            horizontal: desktop ? 0 : 16, vertical: 20),
        decoration: BoxDecoration(
          color: Colors.white,
          border:
              Border(top: BorderSide(color: Colors.grey.shade300, width: 0.5)),
        ),
        child: SafeArea(
          top: false,
          // ⚠ Desktop keeps the bar edge-to-edge (a sticky footer, like
          // booking.com's) but centres its CONTENT to the reading column so
          // the price and button line up with the text above them, not with
          // the browser's own edges.
          child: desktop ? DesktopCenter(maxWidth: 1100, child: row) : row,
        ),
      ),
    );
  }
}

/// Full-page message with a way back. Used when the listing cannot be loaded.
class _MessageState extends StatelessWidget {
  const _MessageState({
    required this.icon,
    required this.title,
    required this.message,
  });

  final IconData icon;
  final String title;
  final String message;

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Center(
        child: Padding(
          padding: const EdgeInsets.all(32),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Icon(icon, size: 56, color: GoOutsColors.primaryBlue),
              const SizedBox(height: 16),
              Text(
                title,
                textAlign: TextAlign.center,
                style: GoogleFonts.inter(
                    fontSize: 15,
                    fontWeight: FontWeight.w700,
                    color: GoOutsColors.deepNavy),
              ),
              const SizedBox(height: 8),
              Text(
                message,
                textAlign: TextAlign.center,
                style: GoogleFonts.inter(
                    fontSize: 15, color: GoOutsColors.bodyText),
              ),
              const SizedBox(height: 24),
              OutlinedButton(
                onPressed: () => Navigator.of(context).pop(),
                child: const Text('Go back'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
