// Generated by Google Stitch, 3 August 2026. Source folder: 5-listing_detail
//
// WIRED 16 August 2026, task #116.
//
// ── WHAT CHANGED AND WHY ─────────────────────────────────────────────────
//
// Reported as "no listing is opening". The listing WAS opening. Screen 02
// pushed StayRoutes.listing with the id, stay_routes.dart parsed the id, and
// then built `const ListingDetailScreen()` and threw the id away. This screen
// took no id and could not have used one — it was a StatelessWidget with a
// hardcoded two bedroom flat in Richmond, 4.9 stars, 124 reviews, Emma's
// review from July 2024.
//
// So every property in the search results opened the same flat. Tapping a
// £95 cottage in Whitby showed £112 nightly and three London stations. That
// reads as broken rather than unfinished, which is why it was reported as
// nothing opening at all.
//
// It now takes a listingId, loads the real listing, and renders what is
// actually stored. Nothing on this screen is invented any more:
//
//   title, rating, town           listing
//   about                         listing.description
//   amenities                     listing.amenities via the shared catalogue
//   distance, stations            listing.locationContext
//   partners within half a mile   listing.locationContext.partnerCounts
//   reviews                       StayListingService.reviews()
//   nightly price                 listing.nightlyRate
//
// ── THE SECTIONS THAT CAN BE ABSENT ──────────────────────────────────────
//
// locationContext is computed by a Cloud Function after the listing is
// approved, so a brand new property has none for a short while. Both sections
// that depend on it are HIDDEN when it is null rather than shown with zeroes.
// "0 GoOuts partners within half a mile" is a worse thing to say than nothing,
// and it would not be true — it is not known yet.
//
// Same for reviews: a listing with none shows the section with an honest
// "No reviews yet" instead of a fabricated one.
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import '../models/money.dart';
import '../models/stay_amenities.dart';
import '../models/stay_listing.dart';
import '../models/stay_property_types.dart';
import '../services/stay_booking_service.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import '../services/stay_listing_service.dart';
import '../services/stay_recently_viewed.dart';
import '../stay_routes.dart';
import '../theme/stay_colors.dart';

class ListingDetailScreen extends StatefulWidget {
  const ListingDetailScreen({super.key, required this.listingId});

  final String listingId;

  @override
  State<ListingDetailScreen> createState() => _ListingDetailScreenState();
}

class _ListingDetailScreenState extends State<ListingDetailScreen> {
  final StayListingService _service = StayListingService.instance;

  late Future<StayListing?> _listing;
  late Future<List<Map<String, dynamic>>> _reviews;

  /// The guest's own rate. Cached in the service, so this costs one call the
  /// first time Short Stay is opened and nothing after that.
  StayCashbackRate _rate = StayCashbackRate.unknown;

  @override
  void initState() {
    super.initState();
    _listing = _service.byId(widget.listingId);
    _reviews = _service.reviews(widget.listingId);
    _loadRate();

    // ── ⚠ THE ONLY PLACE A VIEW IS RECORDED. Added 27 August 2026. ──────────
    //
    // "Recently viewed" came back to the home screen when it became real. The
    // obvious place to record was the home screen's own onTap — and that would
    // have been wrong, because it is not the only door.
    //
    // Listings open from the home screen AND from search results. Recording at
    // the tap site means a property found by searching never appears in the
    // history, so the section shows only what was already on the front page —
    // which is the least useful possible version of it.
    //
    // This screen is where a listing is actually looked at, whatever route
    // reached it. Deep links and state restoration land here too.
    //
    // Never awaited and never throws: a browsing convenience must not be able
    // to delay or break opening a property.
    StayRecentlyViewed.instance.record(widget.listingId);
  }

  Future<void> _loadRate() async {
    final StayCashbackRate r =
        await StayBookingService.instance.cashbackRate();
    if (!mounted) return;
    setState(() => _rate = r);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: FutureBuilder<StayListing?>(
        future: _listing,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Center(child: CircularProgressIndicator());
          }

          // An id that does not resolve. Reached by a stale saved listing, a
          // property the host has since removed, or a deep link. Says so
          // rather than showing an empty page with a back button.
          final StayListing? listing = snapshot.data;
          if (snapshot.hasError || listing == null) {
            return const _MessageState(
              icon: Icons.search_off,
              title: 'This property is not available',
              message:
                  'It may have been removed by the host. Please go back and '
                  'choose another one.',
            );
          }

          return Stack(
            children: [
              SingleChildScrollView(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    _buildPhotoGallery(listing),
                    Padding(
                      padding: const EdgeInsets.all(16),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          _buildHeader(listing),
                          // Stitch puts the host directly under the title,
                          // before the property facts. Hides itself when the
                          // listing carries no host name.
                          _buildHostRow(listing),
                          const SizedBox(height: 16),
                          _buildFactsRow(listing),
                          if (_rate.isKnown) ...[
                            const SizedBox(height: 16),
                            _buildCashbackRow(listing),
                          ],
                          const Divider(height: 32),
                          _buildAboutSection(listing),
                          if (listing.amenities.isNotEmpty) ...[
                            const Divider(height: 32),
                            _buildAmenitiesSection(context, listing),
                          ],
                          // Hidden entirely until the location engine has run.
                          if (listing.locationContext != null) ...[
                            const Divider(height: 32),
                            _buildGettingAroundSection(
                                listing.locationContext!),
                            const SizedBox(height: 20),
                            _buildPartnerHighlightCard(
                                listing.locationContext!),
                          ],
                          const Divider(height: 32),
                          _buildReviewsSection(listing),
                          _buildHouseRules(listing),
                          _buildWhereYoullBe(listing),
                          const SizedBox(height: 100), // Space for bottom bar
                        ],
                      ),
                    ),
                  ],
                ),
              ),
              _buildTopButtons(context),
              _buildBottomBar(context, listing),
            ],
          );
        },
      ),
    );
  }

  // ── Photos ───────────────────────────────────────────────────────────────
  //
  // Was a fixed Unsplash URL. Now the host's own photos, in the order they
  // ordered them, swipeable when there is more than one.
  Widget _buildPhotoGallery(StayListing listing) {
    final List<StayPhoto> photos = List<StayPhoto>.from(listing.photos)
      ..sort((a, b) => a.order.compareTo(b.order));

    if (photos.isEmpty) {
      return Container(
        height: 300,
        width: double.infinity,
        color: GoOutsColors.paleBlueTint,
        child: const Center(
          child: Icon(Icons.home_outlined,
              size: 64, color: GoOutsColors.primaryBlue),
        ),
      );
    }

    return SizedBox(
      height: 300,
      width: double.infinity,
      child: PageView.builder(
        itemCount: photos.length,
        itemBuilder: (context, i) => Image.network(
          photos[i].url,
          fit: BoxFit.cover,
          // A photo that fails to load must not leave a broken-image glyph
          // across the top of the page.
          errorBuilder: (_, __, ___) => Container(
            color: GoOutsColors.paleBlueTint,
            child: const Center(
              child: Icon(Icons.image_not_supported_outlined,
                  size: 48, color: GoOutsColors.primaryBlue),
            ),
          ),
          loadingBuilder: (context, child, progress) => progress == null
              ? child
              : Container(
                  color: GoOutsColors.paleBlueTint,
                  child: const Center(child: CircularProgressIndicator()),
                ),
        ),
      ),
    );
  }

  // ── Back and save ────────────────────────────────────────────────────────
  //
  // The back button had `onPressed: () {}` and the second button was a share
  // icon that did nothing.
  //
  // Share is now save. setSaved/watchSaved already existed on the service and
  // nothing in the app called them, so saving a property was built and
  // unreachable. Sharing needs a link scheme and a landing page that do not
  // exist yet — putting a working control where a dead one was is worth more
  // than keeping the icon.
  Widget _buildTopButtons(BuildContext context) {
    return SafeArea(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            CircleAvatar(
              backgroundColor: Colors.white,
              child: IconButton(
                icon: const Icon(Icons.arrow_back,
                    color: GoOutsColors.primaryBlue),
                onPressed: () => Navigator.of(context).pop(),
              ),
            ),
            StreamBuilder<bool>(
              stream: _service.watchSaved(widget.listingId),
              builder: (context, snap) {
                final bool saved = snap.data ?? false;
                return CircleAvatar(
                  backgroundColor: Colors.white,
                  child: IconButton(
                    tooltip: saved ? 'Saved' : 'Save this property',
                    icon: Icon(
                      saved ? Icons.favorite : Icons.favorite_border,
                      color: saved
                          ? GoOutsColors.error
                          : GoOutsColors.primaryBlue,
                    ),
                    onPressed: () =>
                        _service.setSaved(widget.listingId, !saved),
                  ),
                );
              },
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildHeader(StayListing listing) {
    final String town = listing.address.town;
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          listing.title,
          style: GoogleFonts.inter(
            fontSize: 20,
            fontWeight: FontWeight.w700,
            color: GoOutsColors.deepNavy,
          ),
        ),
        const SizedBox(height: 8),
        Row(
          children: [
            // A new listing has no rating. Showing "0.0" next to a star reads
            // as a bad property rather than an unrated one.
            if (listing.ratingCount > 0) ...[
              const Icon(Icons.star, size: 18, color: GoOutsColors.warning),
              const SizedBox(width: 4),
              Text(
                listing.ratingAvg.toStringAsFixed(1),
                style: GoogleFonts.inter(
                    fontSize: 14, fontWeight: FontWeight.w600),
              ),
              const SizedBox(width: 8),
            ] else ...[
              Text(
                'New',
                style: GoogleFonts.inter(
                    fontSize: 14,
                    fontWeight: FontWeight.w600,
                    color: GoOutsColors.tealSecondary),
              ),
              const SizedBox(width: 8),
            ],
            Expanded(
              child: Text(
                town,
                style: GoogleFonts.inter(
                    fontSize: 13.5, color: GoOutsColors.bodyText),
                overflow: TextOverflow.ellipsis,
              ),
            ),
          ],
        ),
      ],
    );
  }

  // ── Who you are staying with ──────────────────────────────────────────────
  //
  // ⚠ THIS ROW IS BACK. Added 27 August 2026: "host profile is missing
  // completely".
  //
  // It was removed on 3 August for a good reason, recorded below in the
  // occupancy note: the listing carried no host name and the guest cannot read
  // /stay_hosts, because that record holds KYC evidence and payout details and
  // the rule correctly says owner or admin only.
  //
  // The fix was not to relax that rule. createStayListing now copies a first
  // name and a joining year onto the listing itself, on the server, where a
  // client cannot forge them. See StayListing.host.
  //
  // ⚠ HIDES ITSELF WHEN THERE IS NO NAME. Every listing created before today
  // has no host block, and "Hosted by" above a blank space is worse than no
  // row at all.
  //
  // ⚠ NO "SUPERHOST" AND NO "5 YEARS EXPERIENCE". Stitch drew both. Neither is
  // computed anywhere, and a badge nobody can earn is worse than no badge.
  Widget _buildHostRow(StayListing listing) {
    final StayHostSummary h = listing.host;
    if (!h.hasName) return const SizedBox.shrink();

    return Padding(
      padding: const EdgeInsets.only(top: 16),
      child: Row(
        children: <Widget>[
          CircleAvatar(
            radius: 20,
            backgroundColor: GoOutsColors.paleBlueTint,
            backgroundImage:
                h.photoUrl.isEmpty ? null : NetworkImage(h.photoUrl),
            child: h.photoUrl.isEmpty
                ? Text(h.initial,
                    style: GoogleFonts.inter(
                        fontSize: 15,
                        fontWeight: FontWeight.w700,
                        color: GoOutsColors.primaryBlue))
                : null,
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                Text('Hosted by ${h.name}',
                    style: GoogleFonts.inter(
                        fontSize: 14,
                        height: 20 / 14,
                        fontWeight: FontWeight.w600,
                        color: GoOutsColors.deepNavy)),
                // Only when the year is real. Nothing here guesses a tenure.
                if (h.hasSince)
                  Text('Host since ${h.since}',
                      style: GoogleFonts.inter(
                          fontSize: 12,
                          height: 16 / 12,
                          color: GoOutsColors.bodyText)),
              ],
            ),
          ),
        ],
      ),
    );
  }

  // ── Occupancy ────────────────────────────────────────────────────────────
  //
  // Replaced the "Hosted by Sarah, Superhost, 5 years experience" row when the
  // host name was unavailable. The occupancy facts stay because they are what
  // a booking actually turns on; the host row above now sits alongside them.
  Widget _buildFactsRow(StayListing listing) {
    // Via the catalogue, not by capitalising the slug: that would print
    // "Flat" and "Annexe" where a guest should read "Flat or apartment" and
    // "Annexe or outbuilding".
    final String propertyType = stayPropertyTypeLabel(listing.propertyType);

    return Wrap(
      spacing: 16,
      runSpacing: 8,
      children: [
        _fact(Icons.home_outlined, propertyType),
        _fact(Icons.person_outline, _plural(listing.maxGuests, 'guest')),
        _fact(Icons.meeting_room_outlined,
            _plural(listing.bedrooms, 'bedroom')),
        _fact(Icons.bed_outlined, _plural(listing.beds, 'bed')),
        _fact(Icons.bathtub_outlined,
            _plural(listing.bathrooms, 'bathroom')),
      ],
    );
  }

  Widget _fact(IconData icon, String label) => Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(icon, size: 18, color: GoOutsColors.tealSecondary),
          const SizedBox(width: 6),
          Text(label,
              style: GoogleFonts.inter(
                  fontSize: 14, color: GoOutsColors.bodyText)),
        ],
      );

  static String _plural(int n, String word) =>
      '$n $word${n == 1 ? '' : 's'}';

  // ── Cashback ─────────────────────────────────────────────────────────────
  //
  // Shown per NIGHT, not as a total, because no dates have been chosen yet and
  // a total would have to invent a length of stay. The exact figure for the
  // real dates comes from getStayQuote on the checkout screen.
  //
  // "at least" because Plus members earn more, and because the quote is the
  // authority. Understating here and settling up at checkout is the safe
  // direction to be wrong in.
  Widget _buildCashbackRow(StayListing listing) {
    final int perNightPence =
        ((listing.nightlyRate.value * _rate.pct) / 100).round();
    if (perNightPence <= 0) return const SizedBox.shrink();

    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
      decoration: BoxDecoration(
        color: GoOutsColors.tealSecondary.withValues(alpha: 0.10),
        borderRadius: BorderRadius.circular(10),
      ),
      child: Row(
        children: [
          const Icon(Icons.savings_outlined,
              size: 20, color: GoOutsColors.tealSecondary),
          const SizedBox(width: 10),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'Earn ${_rate.label} back — about '
                  '${Pence(perNightPence).compact} a night',
                  style: GoogleFonts.inter(
                    fontSize: 14,
                    fontWeight: FontWeight.w600,
                    color: GoOutsColors.deepNavy,
                  ),
                ),
                if (_rate.note.isNotEmpty)
                  Text(
                    _rate.note,
                    style: GoogleFonts.inter(
                        fontSize: 12, color: GoOutsColors.bodyText),
                  ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildAboutSection(StayListing listing) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          'About this place',
          style: GoogleFonts.inter(
            fontSize: 15,
            fontWeight: FontWeight.w700,
            color: GoOutsColors.deepNavy,
          ),
        ),
        const SizedBox(height: 12),
        Text(
          listing.description.trim().isEmpty
              ? 'The host has not added a description yet.'
              : listing.description,
          style: GoogleFonts.inter(
            fontSize: 15,
            height: 1.5,
            color: GoOutsColors.bodyText,
          ),
        ),
      ],
    );
  }

  // ── Amenities ────────────────────────────────────────────────────────────
  //
  // Was six hardcoded rows and a button reading "Show all 34 amenities" that
  // did nothing. Now the property's own amenities, capped at six with the
  // button appearing only when there are more, and the count comes from the
  // catalogue rather than being typed in.
  Widget _buildAmenitiesSection(BuildContext context, StayListing listing) {
    final List<StayAmenity> shown = listing.amenities
        .take(6)
        .map(stayAmenityFor)
        .toList(growable: false);

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // ⚠ "Amenities", not "What this place offers". Corrected 27 Aug 2026.
        //
        // Stitch labels this section "Amenities" and the full list screen it
        // opens is "All amenities". Renaming it in the build gave the guest
        // three different words for one thing across two screens, and the
        // button underneath still says "Show all 34 amenities", which read as
        // though it opened something else.
        Text(
          'Amenities',
          style: GoogleFonts.inter(
            fontSize: 15,
            height: 20 / 15,
            fontWeight: FontWeight.w700,
            letterSpacing: 0.3,
            color: GoOutsColors.deepNavy,
          ),
        ),
        const SizedBox(height: 16),
        GridView.builder(
          shrinkWrap: true,
          physics: const NeverScrollableScrollPhysics(),
          gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
            crossAxisCount: 2,
            mainAxisExtent: 40,
            crossAxisSpacing: 16,
            mainAxisSpacing: 16,
          ),
          itemCount: shown.length,
          itemBuilder: (context, index) {
            return Row(
              children: [
                // Stitch draws these at roughly 20px against body text. Ours
                // were 24px icons against 15px labels, which made the grid
                // read as six buttons rather than a list of facts.
                Icon(shown[index].icon,
                    color: GoOutsColors.tealSecondary, size: 20),
                const SizedBox(width: 12),
                Expanded(
                  child: Text(
                    shown[index].label,
                    style: GoogleFonts.inter(
                        fontSize: 13.5,
                        height: 20 / 13.5,
                        color: GoOutsColors.deepNavy),
                    overflow: TextOverflow.ellipsis,
                  ),
                ),
              ],
            );
          },
        ),
        if (listing.amenities.length > 6) ...[
          const SizedBox(height: 24),
          OutlinedButton(
            onPressed: () => Navigator.of(context).pushNamed(
              StayRoutes.amenities,
              arguments: <String, dynamic>{'listingId': listing.id},
            ),
            style: OutlinedButton.styleFrom(
              minimumSize: const Size(double.infinity, 52),
              shape:
                  RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
              side: const BorderSide(color: GoOutsColors.deepNavy),
            ),
            child: Text(
              'Show all ${listing.amenities.length} amenities',
              style: GoogleFonts.inter(
                  color: GoOutsColors.deepNavy, fontWeight: FontWeight.w600),
            ),
          ),
        ],
      ],
    );
  }

  // ── Getting around ───────────────────────────────────────────────────────
  //
  // Every figure here comes from the location engine (task #114), which
  // computes it from the property's real postcode.
  Widget _buildGettingAroundSection(StayLocationContext ctx) {
    final List<StayStation> stations = ctx.stations.take(3).toList();

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          'Getting around',
          style: GoogleFonts.inter(
            fontSize: 15,
            fontWeight: FontWeight.w700,
            color: GoOutsColors.deepNavy,
          ),
        ),
        const SizedBox(height: 12),
        if (ctx.centreName.isNotEmpty)
          Text(
            '${_miles(ctx.distanceToCentreMi)} from ${ctx.centreName}',
            style:
                GoogleFonts.inter(fontSize: 15, color: GoOutsColors.bodyText),
          ),
        if (stations.isNotEmpty) ...[
          const SizedBox(height: 16),
          for (final s in stations) _buildStationItem(s),
          const SizedBox(height: 8),
          Text(
            'Distances are calculated from the property address',
            style: GoogleFonts.inter(
                fontSize: 12,
                fontStyle: FontStyle.italic,
                color: GoOutsColors.bodyText),
          ),
        ],
      ],
    );
  }

  static String _miles(double mi) =>
      '${mi.toStringAsFixed(1)} ${mi == 1.0 ? 'mile' : 'miles'}';

  Widget _buildStationItem(StayStation station) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 12),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Icon(Icons.train, color: GoOutsColors.primaryBlue, size: 20),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(station.name,
                    style: GoogleFonts.inter(
                        fontSize: 15, fontWeight: FontWeight.w600)),
                if (station.lines.isNotEmpty)
                  Text(station.lines.join(', '),
                      style: GoogleFonts.inter(
                          fontSize: 13.5, color: GoOutsColors.bodyText)),
                Text('${_miles(station.walkMi)} walking',
                    style: GoogleFonts.inter(
                        fontSize: 13.5, fontWeight: FontWeight.w500)),
              ],
            ),
          ),
        ],
      ),
    );
  }

  // ── The GoOuts difference ────────────────────────────────────────────────
  //
  // The one thing on this screen no competitor can show, so it must be true.
  // Counts come from partnerCounts, and the breakdown is built from the
  // categories actually present rather than the fixed "6 restaurants, 3 pubs,
  // 2 cafes, 3 shops" that used to be printed under every property.
  Widget _buildPartnerHighlightCard(StayLocationContext ctx) {
    final int half = ctx.partnerCounts.halfMile;
    if (half <= 0) return const SizedBox.shrink();

    final List<MapEntry<String, int>> byCategory =
        ctx.partnerCounts.byCategory.entries.where((e) => e.value > 0).toList()
          ..sort((a, b) => b.value.compareTo(a.value));

    final String breakdown = byCategory
        .take(4)
        .map((e) => '${e.value} ${e.key}')
        .join(', ');

    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: GoOutsColors.primaryBlue,
        borderRadius: BorderRadius.circular(12),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            '$half GoOuts ${half == 1 ? 'partner' : 'partners'} '
            'within half a mile',
            style: GoogleFonts.inter(
              fontSize: 15,
              fontWeight: FontWeight.w700,
              color: Colors.white,
            ),
          ),
          if (breakdown.isNotEmpty) ...[
            const SizedBox(height: 12),
            Text(
              breakdown,
              style: GoogleFonts.inter(
                  fontSize: 15, color: Colors.white.withValues(alpha: 0.9)),
            ),
          ],
          const SizedBox(height: 12),
          Text(
            'Earn cashback at every one',
            style: GoogleFonts.inter(
              fontSize: 15,
              fontWeight: FontWeight.w600,
              color: Colors.white,
            ),
          ),
        ],
      ),
    );
  }

  // ── Reviews ──────────────────────────────────────────────────────────────
  //
  // Was one invented review from "Emma • July 2024" shown on every property.
  // Reviews are written by real guests after a stay (task #106); until that
  // exists this section will legitimately be empty, and empty is what it now
  // says.
  Widget _buildReviewsSection(StayListing listing) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            const Icon(Icons.star, color: GoOutsColors.warning, size: 20),
            const SizedBox(width: 8),
            Text(
              listing.ratingCount > 0
                  ? '${listing.ratingAvg.toStringAsFixed(1)} • '
                      '${_plural(listing.ratingCount, 'review')}'
                  : 'Reviews',
              style:
                  GoogleFonts.inter(fontSize: 15, fontWeight: FontWeight.w700),
            ),
          ],
        ),
        const SizedBox(height: 8),
        FutureBuilder<List<Map<String, dynamic>>>(
          future: _reviews,
          builder: (context, snap) {
            if (snap.connectionState == ConnectionState.waiting) {
              return const Padding(
                padding: EdgeInsets.symmetric(vertical: 16),
                child: Center(child: CircularProgressIndicator()),
              );
            }
            final List<Map<String, dynamic>> reviews =
                snap.data ?? const <Map<String, dynamic>>[];
            if (reviews.isEmpty) {
              return Padding(
                padding: const EdgeInsets.symmetric(vertical: 8),
                child: Text(
                  'No reviews yet. Be the first to stay here.',
                  style: GoogleFonts.inter(
                      fontSize: 15, color: GoOutsColors.bodyText),
                ),
              );
            }
            return Column(
              children: [
                for (final r in reviews) _reviewTile(r),
              ],
            );
          },
        ),
      ],
    );
  }

  Widget _reviewTile(Map<String, dynamic> r) {
    final String name = (r['guestName'] as String?)?.trim().isNotEmpty == true
        ? r['guestName'] as String
        : 'Guest';
    final String body = (r['comment'] as String?) ?? '';
    final DateTime? when = _toDate(r['createdAt']);
    final String subtitle =
        when == null ? name : '$name • ${_monthYear(when)}';

    return ListTile(
      contentPadding: EdgeInsets.zero,
      leading: const CircleAvatar(backgroundColor: GoOutsColors.paleBlueTint),
      title: Text(subtitle,
          style: GoogleFonts.inter(fontWeight: FontWeight.w600)),
      subtitle: body.isEmpty
          ? null
          : Text(body,
              style: GoogleFonts.inter(color: GoOutsColors.bodyText)),
    );
  }

  // Firestore hands back a Timestamp, but a hand-edited document or an older
  // write can hold an ISO string. Both are accepted; anything else is treated
  // as no date rather than crashing the tile.
  static DateTime? _toDate(Object? v) {
    if (v == null) return null;
    if (v is DateTime) return v;
    if (v is String) return DateTime.tryParse(v);
    try {
      return (v as dynamic).toDate() as DateTime;
    } catch (_) {
      return null;
    }
  }

  static const List<String> _months = <String>[
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December',
  ];

  static String _monthYear(DateTime d) =>
      '${_months[d.month - 1]} ${d.year}';

  // ── House rules, check-in and check-out ───────────────────────────────────
  //
  // ⚠ ADDED 27 August 2026: "there is no rules shows to consumer check in and
  // check out".
  //
  // Nothing anywhere in the product carried these. The Stitch GUEST screens
  // displayed them — trip detail draws "Check in 15:00 / Check out 11:00" and a
  // House rules row — but no Stitch HOST screen ever asked for them. Stitch's
  // host step 7 is called "pricing_rules" and its rules are the CANCELLATION
  // policy. So the design showed guest data the design never collected, and
  // 15_trip_detail_screen.dart recorded exactly that on 17 August and left the
  // section out rather than invent a check-in time for somebody's holiday.
  //
  // Fixed at the source: host wizard step 7 now captures it, createStayListing
  // validates and stores it, StayListing parses it with the UK norm as the
  // default for every listing written before today.
  //
  // ⚠ SHOWN BEFORE BOOKING, ON PURPOSE. "No pets" is something a guest needs
  // while they are deciding, not an unpleasant surprise on the confirmation.
  //
  // ⚠ arrivalInstructions IS DELIBERATELY NOT HERE. Door codes and key safe
  // locations belong to a confirmed booking, not to a public listing page that
  // anybody can open.
  Widget _buildHouseRules(StayListing listing) {
    final StayHouseRules r = listing.houseRules;

    TextStyle head() => GoogleFonts.inter(
        fontSize: 15,
        height: 20 / 15,
        fontWeight: FontWeight.w700,
        letterSpacing: 0.3,
        color: GoOutsColors.deepNavy);

    Widget row(IconData icon, String label, String value, {Color? tone}) =>
        Padding(
          padding: const EdgeInsets.only(bottom: 10),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Icon(icon, size: 18, color: tone ?? GoOutsColors.primaryBlue),
              const SizedBox(width: 12),
              Expanded(
                child: Text(label,
                    style: GoogleFonts.inter(
                        fontSize: 13.5,
                        height: 20 / 13.5,
                        color: GoOutsColors.bodyText)),
              ),
              Text(value,
                  style: GoogleFonts.inter(
                      fontSize: 14,
                      height: 20 / 14,
                      fontWeight: FontWeight.w600,
                      color: tone ?? GoOutsColors.deepNavy)),
            ],
          ),
        );

    // A permission the host has NOT granted is the ordinary case and is drawn
    // plainly. Only what they HAVE allowed is worth colouring, because that is
    // the surprising, useful information.
    Widget permission(IconData icon, String label, bool allowed) => row(
          icon,
          label,
          allowed ? 'Allowed' : 'Not allowed',
          tone: allowed ? GoOutsColors.success : GoOutsColors.bodyText,
        );

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        const Divider(height: 32),
        Text('House rules', style: head()),
        const SizedBox(height: 12),

        // Always shown. Every listing has these two, defaulted to the UK norm
        // when the host left the step alone, so there is no empty state.
        row(Icons.login_rounded, 'Check-in from', listing.checkInTime),
        row(Icons.logout_rounded, 'Check-out by', listing.checkOutTime),

        // Hidden entirely when the host said nothing beyond the defaults.
        // Printing three "Not allowed" lines a host never actually chose would
        // put words in their mouth.
        if (!r.isUnset) ...<Widget>[
          const SizedBox(height: 2),
          permission(Icons.smoking_rooms_outlined, 'Smoking',
              r.smokingAllowed),
          permission(Icons.pets_outlined, 'Pets', r.petsAllowed),
          permission(Icons.celebration_outlined, 'Parties or events',
              r.partiesAllowed),
          if (r.hasQuietHours)
            row(Icons.bedtime_outlined, 'Quiet hours',
                '${r.quietHoursFrom} – ${r.quietHoursTo}'),
          if (r.additional.isNotEmpty) ...<Widget>[
            const SizedBox(height: 4),
            Text(r.additional,
                style: GoogleFonts.inter(
                    fontSize: 13.5,
                    height: 20 / 13.5,
                    color: GoOutsColors.bodyText)),
          ],
        ],
      ],
    );
  }

  // ── "Where you'll be" ─────────────────────────────────────────────────────
  //
  // ⚠ THIS SECTION WAS NEVER BUILT. Added 27 August 2026, reported as "there is
  // no map showing in the listing".
  //
  // Stitch draws it between Reviews and the booking bar, captioned with the
  // town. Every other section on this screen was built — gallery, about,
  // amenities, getting around, partner highlight, reviews — and this one was
  // simply skipped. The coordinates were already on the model (`lat`, `lng`,
  // both nullable), already parsed from the `geo` map, and nothing read them.
  //
  // The only GoogleMap in the entire Short Stay feature was on screen 04.
  //
  // ── ⚠ A CIRCLE, NOT A PIN. THIS IS DELIBERATE. ──────────────────────────────
  //
  // The exact address of somebody's home is not shown to a person who has not
  // booked it. This draws a 300m circle around the property and NO marker, so
  // the guest learns the area — which is what they are actually deciding on —
  // without the screen publishing where a host lives to anyone who opens a
  // listing. Every established stay platform does exactly this, and reversing
  // it would be a host-safety problem, not a design tweak.
  //
  // ── ⚠ THE MAP IS DEAD. NO GESTURES, NO CONTROLLER, NO DISPOSE. ─────────────
  //
  // 04_map_results carries a rule at the top of the file: "ONE GoogleMap alive
  // at a time across the whole Short Stay feature, and the controller is
  // disposed". A live, gesture-enabled map inside a scrolling list would break
  // that rule AND fight the ListView for vertical drags.
  //
  // So: every gesture flag off, no onMapCreated, no controller held, therefore
  // nothing to dispose. Lite mode on Android renders it as a static bitmap,
  // which is far cheaper again. Tapping opens the neighbourhood screen, which
  // is the interactive one.
  Widget _buildWhereYoullBe(StayListing listing) {
    final double? lat = listing.lat;
    final double? lng = listing.lng;

    // Hidden entirely when the property has no coordinates. An empty grey box
    // captioned "Where you'll be" is worse than no section: it reads as a
    // failure to load rather than as an absence of data.
    if (lat == null || lng == null) return const SizedBox.shrink();

    final LatLng centre = LatLng(lat, lng);

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        const Divider(height: 32),
        Text(
          "Where you'll be",
          style: GoogleFonts.inter(
            fontSize: 15,
            height: 20 / 15,
            fontWeight: FontWeight.w700,
            letterSpacing: 0.3,
            color: GoOutsColors.deepNavy,
          ),
        ),
        const SizedBox(height: 12),
        ClipRRect(
          borderRadius: BorderRadius.circular(12),
          child: SizedBox(
            height: 180,
            width: double.infinity,
            child: Stack(
              children: <Widget>[
                GoogleMap(
                  initialCameraPosition:
                      CameraPosition(target: centre, zoom: 14),
                  // Android only. Renders a non-interactive bitmap instead of a
                  // full map surface — a fraction of the memory and no texture
                  // for the ListView to composite on every frame.
                  liteModeEnabled: Theme.of(context).platform ==
                      TargetPlatform.android,
                  circles: <Circle>{
                    Circle(
                      circleId: const CircleId('approx'),
                      center: centre,
                      radius: 300,
                      fillColor:
                          GoOutsColors.primaryBlue.withValues(alpha: 0.18),
                      strokeColor: GoOutsColors.primaryBlue,
                      strokeWidth: 2,
                    ),
                  },
                  // ⚠ Everything off. See the note above about the ListView.
                  zoomControlsEnabled: false,
                  zoomGesturesEnabled: false,
                  scrollGesturesEnabled: false,
                  rotateGesturesEnabled: false,
                  tiltGesturesEnabled: false,
                  myLocationButtonEnabled: false,
                  myLocationEnabled: false,
                  mapToolbarEnabled: false,
                  compassEnabled: false,
                ),
                // ⚠ NO TAP HANDLER, ON PURPOSE.
                //
                // The obvious move was to open StayRoutes.neighbourhood on tap.
                // That route resolves to `const NeighbourhoodScreen()` — it
                // takes NO listingId, and stay_routes.dart:129 records that
                // screens 07 to 10 are still unwired. Tapping would have sent
                // the guest to an empty screen about nowhere in particular.
                //
                // Stitch's own map here is a flat image with no interaction, so
                // a dead map is the design, not a shortcut. Wire this to the
                // neighbourhood screen when that screen takes a property.
              ],
            ),
          ),
        ),
        const SizedBox(height: 8),
        Text(
          listing.address.publicLabel,
          style: GoogleFonts.inter(
            fontSize: 14,
            height: 20 / 14,
            fontWeight: FontWeight.w600,
            color: GoOutsColors.deepNavy,
          ),
        ),
        const SizedBox(height: 2),
        Text(
          'Exact address is shared once your booking is confirmed.',
          style: GoogleFonts.inter(
            fontSize: 12,
            height: 16 / 12,
            fontWeight: FontWeight.w500,
            color: GoOutsColors.bodyText,
          ),
        ),
      ],
    );
  }

  // ── Bottom bar ───────────────────────────────────────────────────────────
  //
  // Was "£112 nightly / 12 to 14 July" with an empty onPressed. The price is
  // now the property's own; the dates line is gone because no dates have been
  // chosen at this point — choosing them is what the button is for.
  Widget _buildBottomBar(BuildContext context, StayListing listing) {
    final Pence rate = listing.nightlyRate;

    return Align(
      alignment: Alignment.bottomCenter,
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 20),
        decoration: BoxDecoration(
          color: Colors.white,
          border:
              Border(top: BorderSide(color: Colors.grey.shade300, width: 0.5)),
        ),
        child: SafeArea(
          top: false,
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    '${rate.compact} nightly',
                    style: GoogleFonts.inter(
                        fontSize: 16, fontWeight: FontWeight.w700),
                  ),
                  if (!listing.cleaningFee.isZero)
                    Text(
                      '${listing.cleaningFee.compact} cleaning fee',
                      style: GoogleFonts.inter(
                          fontSize: 14, color: GoOutsColors.bodyText),
                    ),
                ],
              ),
              ElevatedButton(
                onPressed: () => Navigator.of(context).pushNamed(
                  StayRoutes.bookingDates,
                  arguments: <String, dynamic>{'listingId': listing.id},
                ),
                style: ElevatedButton.styleFrom(
                  backgroundColor: GoOutsColors.primaryBlue,
                  minimumSize: const Size(180, 52),
                  shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12)),
                ),
                child: Text(
                  'Check availability',
                  style: GoogleFonts.inter(
                      fontSize: 16,
                      fontWeight: FontWeight.w600,
                      color: Colors.white),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

/// Full-page message with a way back. Used when the listing cannot be loaded.
class _MessageState extends StatelessWidget {
  const _MessageState({
    required this.icon,
    required this.title,
    required this.message,
  });

  final IconData icon;
  final String title;
  final String message;

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Center(
        child: Padding(
          padding: const EdgeInsets.all(32),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Icon(icon, size: 56, color: GoOutsColors.primaryBlue),
              const SizedBox(height: 16),
              Text(
                title,
                textAlign: TextAlign.center,
                style: GoogleFonts.inter(
                    fontSize: 15,
                    fontWeight: FontWeight.w700,
                    color: GoOutsColors.deepNavy),
              ),
              const SizedBox(height: 8),
              Text(
                message,
                textAlign: TextAlign.center,
                style: GoogleFonts.inter(
                    fontSize: 15, color: GoOutsColors.bodyText),
              ),
              const SizedBox(height: 24),
              OutlinedButton(
                onPressed: () => Navigator.of(context).pop(),
                child: const Text('Go back'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
