// Generated by Google Stitch, 3 August 2026. Source folder: 7-days_out
// Cleaned and consolidated by the pass described in
// goouts/design/SHORT_STAY_WIRING_PLAN.md part 1.
// NOT WIRED. Every handler in this file is still empty. See part 2.
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import '../theme/stay_colors.dart';

class DaysOutScreen extends StatelessWidget {
  const DaysOutScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: GoOutsColors.pageBackground,
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0.5,
        leading: const Icon(Icons.arrow_back, color: GoOutsColors.primaryBlue),
        title: Text(
          'Days out from your stay',
          style: GoogleFonts.inter(
            fontSize: 18,
            fontWeight: FontWeight.w700,
            color: GoOutsColors.deepNavy,
          ),
        ),
      ),
      body: SingleChildScrollView(
        child: Column(
          children: [
            Padding(
              padding: const EdgeInsets.all(16.0),
              child: Text(
                'Grouped by what you can do in one trip, and ordered by how long it takes to get there.',
                style: GoogleFonts.inter(
                  fontSize: 14,
                  color: GoOutsColors.bodyText,
                  height: 1.5,
                ),
              ),
            ),
            _buildAttractionCard(
              title: 'South Kensington museums',
              time: 'About 35 minutes from your door',
              tag: 'Top Choice',
              description: 'Natural History Museum, Science Museum, Victoria & Albert Museum.',
              partnerCount: 7,
              images: [
                'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=300',
                'https://images.unsplash.com/photo-1540553016722-983e48a2cd10?auto=format&fit=crop&q=80&w=300',
                'https://images.unsplash.com/photo-1534073828943-f801091bb18c?auto=format&fit=crop&q=80&w=300',
              ],
            ),
            _buildAttractionCard(
              title: 'Richmond Riverside & Park',
              time: 'About 50 minutes from your door',
              description: 'Richmond Park, Petersham Nurseries, Riverside Walk.',
              partnerCount: 4,
              images: [
                'https://images.unsplash.com/photo-1541461421424-699317d740c2?auto=format&fit=crop&q=80&w=300',
                'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&q=80&w=300',
                'https://images.unsplash.com/photo-1513519245088-0e12902e35ca?auto=format&fit=crop&q=80&w=300',
              ],
            ),
            _buildAttractionCard(
              title: 'Greenwich Maritime',
              time: 'About 75 minutes from your door',
              description: 'Cutty Sark, Royal Observatory, Painted Hall.',
              partnerCount: 12,
              images: [
                'https://images.unsplash.com/photo-1516496636080-14fb876e029d?auto=format&fit=crop&q=80&w=300',
                'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=300',
                'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&q=80&w=300',
              ],
            ),
            const SizedBox(height: 100),
          ],
        ),
      ),
      bottomNavigationBar: _buildBottomNavBar(),
    );
  }

  Widget _buildAttractionCard({
    required String title,
    required String time,
    String? tag,
    required String description,
    required int partnerCount,
    required List<String> images,
  }) {
    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.05),
            blurRadius: 10,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Padding(
            padding: const EdgeInsets.all(16),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Expanded(
                      child: Text(
                        title,
                        style: GoogleFonts.inter(
                          fontSize: 18,
                          fontWeight: FontWeight.w700,
                          color: GoOutsColors.deepNavy,
                        ),
                      ),
                    ),
                    if (tag != null)
                      Container(
                        padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                        decoration: BoxDecoration(
                          color: GoOutsColors.choiceBlue.withValues(alpha: 0.3),
                          borderRadius: BorderRadius.circular(4),
                        ),
                        child: Row(
                          children: [
                            const Icon(Icons.confirmation_number_outlined, size: 14, color: GoOutsColors.partnerTeal),
                            const SizedBox(width: 4),
                            Text(
                              tag,
                              style: GoogleFonts.inter(
                                fontSize: 11,
                                fontWeight: FontWeight.w700,
                                color: GoOutsColors.partnerTeal,
                              ),
                            ),
                          ],
                        ),
                      ),
                  ],
                ),
                const SizedBox(height: 4),
                Row(
                  children: [
                    const Icon(Icons.access_time, size: 16, color: GoOutsColors.partnerTeal),
                    const SizedBox(width: 6),
                    Text(
                      time,
                      style: GoogleFonts.inter(
                        fontSize: 13,
                        color: GoOutsColors.bodyText,
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
          SizedBox(
            height: 100,
            child: ListView.separated(
              padding: const EdgeInsets.symmetric(horizontal: 16),
              scrollDirection: Axis.horizontal,
              itemCount: images.length,
              separatorBuilder: (context, index) => const SizedBox(width: 8),
              itemBuilder: (context, index) => ClipRRect(
                borderRadius: BorderRadius.circular(8),
                child: Image.network(
                  images[index],
                  width: 100,
                  height: 100,
                  fit: BoxFit.cover,
                ),
              ),
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(16),
            child: Text(
              description,
              style: GoogleFonts.inter(
                fontSize: 14,
                color: GoOutsColors.bodyText,
                height: 1.4,
              ),
            ),
          ),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
            decoration: const BoxDecoration(
              color: GoOutsColors.partnerTeal,
              borderRadius: BorderRadius.vertical(bottom: Radius.circular(12)),
            ),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Row(
                  children: [
                    const Icon(Icons.restaurant, color: Colors.white, size: 18),
                    const SizedBox(width: 10),
                    Text(
                      '$partnerCount GOOUTS PARTNERS NEARBY FOR LUNCH\nAND COFFEE',
                      style: GoogleFonts.inter(
                        fontSize: 11,
                        fontWeight: FontWeight.w800,
                        color: Colors.white,
                        letterSpacing: 0.5,
                      ),
                    ),
                  ],
                ),
                const Icon(Icons.chevron_right, color: Colors.white),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildBottomNavBar() {
    return Container(
      height: 80,
      decoration: BoxDecoration(
        color: Colors.white,
        border: Border(top: BorderSide(color: Colors.grey.shade200)),
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        children: [
          _buildNavItem(Icons.search, 'Search', false),
          _buildNavItem(Icons.explore, 'Trips', true),
          _buildNavItem(Icons.stars, 'Rewards', false),
          _buildNavItem(Icons.person, 'Profile', false),
        ],
      ),
    );
  }

  Widget _buildNavItem(IconData icon, String label, bool isActive) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        Icon(
          icon,
          color: isActive ? GoOutsColors.primaryBlue : GoOutsColors.bodyText,
        ),
        const SizedBox(height: 4),
        Text(
          label,
          style: GoogleFonts.inter(
            fontSize: 12,
            fontWeight: isActive ? FontWeight.w700 : FontWeight.w500,
            color: isActive ? GoOutsColors.primaryBlue : GoOutsColors.bodyText,
          ),
        ),
      ],
    );
  }
}
