// Screen 09 of 29. Generated by Google Stitch, source folder 9-neighbourhood.
//
// WIRED 29 August 2026. Until today this was the emptiest screen left in the
// feature, and it was live on a route:
//
//   * the "map" was an UNSPLASH PHOTOGRAPH of a city seen from above, with
//     Positioned() pins at fixed pixel offsets on top of it
//   * every handler was empty
//   * it took no listingId, so it could not have known whose neighbourhood it
//     was showing even if the data had been there
//
// ── WHERE THE DATA COMES FROM ───────────────────────────────────────────────
//
// stay_listings/{id}.locationContext.nearestPartners, written by
// enrichListingLocation when the listing is created. Up to ten partners within
// three miles, each with a name, a category, a distance and a cashback rate —
// see short_stay.js:288. It has been sitting there since the enrichment was
// built and only ever surfaced as a COUNT on a card.
//
// ── ⚠ MILES, NEVER MINUTES ──────────────────────────────────────────────────
//
// The Stitch design says "5 mins walk" against every partner. We have no
// routing API. A straight line distance is measured; a walking time would be
// invented, and this is a screen somebody uses to decide whether to walk
// somewhere in the dark with a suitcase.
//
// Same decision, same reason, as screens 07 and 08.
//
// ── ⚠ THE MAP SHOWS THE PROPERTY, NOT THE PARTNERS ──────────────────────────
//
// nearestPartners stores name, category, walkMi and cashbackRate. It does NOT
// store coordinates, so the partners cannot be plotted, and inventing pin
// positions is precisely what the Unsplash version did.
//
// What is drawn instead is true: the property, and a circle at the radius the
// list covers. A guest can see how far three miles reaches from their door,
// which is the question the map was there to answer.
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

import '../models/stay_listing.dart';
import '../services/stay_listing_service.dart';
import '../theme/stay_colors.dart';
import '../theme/stay_type.dart';
import '../widgets/stay_bottom_nav.dart';

class NeighbourhoodScreen extends StatefulWidget {
  const NeighbourhoodScreen({super.key, required this.listingId});

  /// ⚠ REQUIRED, and the thing this screen never had.
  final String listingId;

  @override
  State<NeighbourhoodScreen> createState() => _NeighbourhoodScreenState();
}

class _NeighbourhoodScreenState extends State<NeighbourhoodScreen> {
  /// The radius enrichListingLocation actually searched. Stated as a constant
  /// rather than a number in a sentence, because it is drawn on the map as
  /// well as written in the copy and the two must agree.
  ///
  /// ⚠ IF short_stay.js CHANGES ITS `p.mi <= 3.0` FILTER, THIS CHANGES WITH IT.
  static const double _radiusMiles = 3;

  StayListing? _listing;
  bool _loading = true;

  /// null means "All". Otherwise the category being filtered to.
  String? _category;

  GoogleMapController? _map;

  @override
  void initState() {
    super.initState();
    _load();
  }

  @override
  void dispose() {
    // A leaked map controller holds native resources. Same rule as screen 04.
    _map?.dispose();
    super.dispose();
  }

  Future<void> _load() async {
    try {
      final StayListing? l =
          await StayListingService.instance.byId(widget.listingId);
      if (!mounted) return;
      setState(() {
        _listing = l;
        _loading = false;
      });
    } catch (_) {
      if (!mounted) return;
      setState(() => _loading = false);
    }
  }

  List<StayNearbyPartner> get _all =>
      _listing?.locationContext?.nearestPartners ??
      const <StayNearbyPartner>[];

  /// The categories that are actually present, in the order they first appear.
  ///
  /// ⚠ DERIVED, NOT A FIXED LIST. Stitch draws All, Restaurants, Pubs, Cafes.
  /// Offering a Pubs filter to a guest whose nearest partners are a barber and
  /// a corner shop gives them a chip that returns nothing, and it implies a
  /// pub is nearby.
  List<String> get _categories {
    final List<String> out = <String>[];
    for (final StayNearbyPartner p in _all) {
      final String c = p.category.trim();
      if (c.isNotEmpty && !out.contains(c)) out.add(c);
    }
    return out;
  }

  List<StayNearbyPartner> get _visible {
    final List<StayNearbyPartner> list = _category == null
        ? _all
        : _all.where((StayNearbyPartner p) => p.category == _category).toList();
    // Nearest first. The list arrives sorted from the server, but a filtered
    // subset should not depend on that staying true.
    final List<StayNearbyPartner> sorted = List<StayNearbyPartner>.from(list)
      ..sort((StayNearbyPartner a, StayNearbyPartner b) =>
          a.walkMi.compareTo(b.walkMi));
    return sorted;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: GoOutsColors.pageBackground,
      appBar: AppBar(
        backgroundColor: GoOutsColors.cardSurface,
        surfaceTintColor: Colors.transparent,
        elevation: 0,
        toolbarHeight: 52,
        shape: const Border(
          bottom: BorderSide(color: GoOutsColors.outlineVariant, width: 0.5),
        ),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: GoOutsColors.primaryBlue),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: Text('Local rewards',
            style: StayType.screenTitle.on(GoOutsColors.primaryBlue)),
        actions: <Widget>[
          // ⚠ WAS `onPressed: () {}`. Stitch draws an info circle here and it
          // did nothing. It now explains the one thing a guest will wonder,
          // which is where these percentages come from and whether they apply
          // to them.
          IconButton(
            icon: const Icon(Icons.info_outline,
                color: GoOutsColors.primaryBlue),
            tooltip: 'About local rewards',
            onPressed: _explain,
          ),
        ],
      ),
      bottomNavigationBar: const StayBottomNav(current: StayTab.rewards),
      body: _loading
          ? const Center(child: CircularProgressIndicator())
          : _all.isEmpty
              ? _empty()
              : _body(),
    );
  }

  void _explain() => showDialog<void>(
        context: context,
        builder: (BuildContext ctx) => AlertDialog(
          backgroundColor: GoOutsColors.cardSurface,
          shape:
              RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
          title: Text('About local rewards',
              style: StayType.sectionHeader.on(GoOutsColors.deepNavy)),
          content: Text(
            'These are GoOuts partners within '
            '${_radiusMiles.toStringAsFixed(0)} miles of the property you are '
            'staying in. Pay with a linked card at any of them and the '
            'cashback shown is credited to your wallet.\n\n'
            'Distances are measured in a straight line from the property, not '
            'along the roads, so treat them as a guide.',
            style: StayType.body.on(GoOutsColors.bodyText),
          ),
          actions: <Widget>[
            TextButton(
              onPressed: () => Navigator.of(ctx).pop(),
              child: Text('Got it',
                  style: StayType.cardTitle.on(GoOutsColors.primaryBlue)),
            ),
          ],
        ),
      );

  /// ⚠ SAYS WHICH OF THE TWO IT IS. A property whose location has never been
  /// enriched and a property with genuinely nothing nearby are different
  /// situations, and telling a guest in the middle of Birmingham that there
  /// are no partners near them would be false.
  Widget _empty() {
    final bool enriched = _listing?.locationContext != null;
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(32),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            const Icon(Icons.storefront_outlined,
                size: 48, color: GoOutsColors.outlineVariant),
            const SizedBox(height: StaySpacing.inline),
            Text(
              enriched
                  ? 'No partners near this stay yet'
                  : 'We have not mapped this area yet',
              textAlign: TextAlign.center,
              style: StayType.cardTitle.on(GoOutsColors.deepNavy),
            ),
            const SizedBox(height: 6),
            Text(
              enriched
                  ? 'The partner network is growing. There is still cashback '
                      'on everything else you book through GoOuts.'
                  : 'Partners are added area by area. Check back before you '
                      'travel.',
              textAlign: TextAlign.center,
              style: StayType.body.on(GoOutsColors.bodyText),
            ),
          ],
        ),
      ),
    );
  }

  Widget _body() => Column(
        children: <Widget>[
          _map_(),
          _filters(),
          Expanded(
            child: ListView(
              padding: const EdgeInsets.fromLTRB(
                  StaySpacing.page, 0, StaySpacing.page, 24),
              children: <Widget>[
                Padding(
                  padding: const EdgeInsets.only(bottom: StaySpacing.inline),
                  child: Text(
                    'Nearby partners',
                    style: StayType.sectionHeader.on(GoOutsColors.deepNavy),
                  ),
                ),
                for (final StayNearbyPartner p in _visible) _partnerRow(p),
                if (_visible.isEmpty)
                  Padding(
                    padding: const EdgeInsets.symmetric(vertical: 24),
                    child: Text(
                      'Nothing in that category near this stay.',
                      textAlign: TextAlign.center,
                      style: StayType.body.on(GoOutsColors.bodyText),
                    ),
                  ),
              ],
            ),
          ),
        ],
      );

  // ── The map ──────────────────────────────────────────────────────────────

  /// Named with a trailing underscore because `_map` is the controller.
  Widget _map_() {
    final double? lat = _listing?.lat;
    final double? lng = _listing?.lng;
    // No coordinates, no map. Not a grey box, and certainly not a photograph
    // of a different city, which is what was here before.
    if (lat == null || lng == null) return const SizedBox.shrink();

    final LatLng centre = LatLng(lat, lng);
    return SizedBox(
      height: 220,
      child: GoogleMap(
        initialCameraPosition: CameraPosition(target: centre, zoom: 12.5),
        markers: <Marker>{
          Marker(markerId: const MarkerId('stay'), position: centre),
        },
        // The radius the list actually covers, drawn rather than described.
        // 1 mile is 1609.34 metres.
        circles: <Circle>{
          Circle(
            circleId: const CircleId('radius'),
            center: centre,
            radius: _radiusMiles * 1609.34,
            strokeWidth: 2,
            strokeColor: GoOutsColors.primaryBlue.withValues(alpha: 0.6),
            fillColor: GoOutsColors.primaryBlue.withValues(alpha: 0.08),
          ),
        },
        zoomControlsEnabled: false,
        myLocationEnabled: false,
        myLocationButtonEnabled: false,
        mapToolbarEnabled: false,
        compassEnabled: false,
        onMapCreated: (GoogleMapController c) {
          _map = c;
          WidgetsBinding.instance
              .addPostFrameCallback((_) => _frameRadius(centre));
        },
      ),
    );
  }

  /// ── ⚠ FRAME THE CIRCLE, DO NOT GUESS A ZOOM. 29 August 2026. ─────────────
  ///
  ///  The camera opened at a hardcoded zoom 12.5, chosen because it looked
  ///  about right for three miles on the phone I was picturing. It is not right
  ///  on any other phone: the same zoom shows a different amount of ground on a
  ///  narrow device than a wide one, so the circle that is the entire point of
  ///  this map would be clipped on some handsets and lost in whitespace on
  ///  others.
  ///
  ///  Framing the circle's own bounding box makes the radius fit whatever
  ///  screen it lands on, which is what the number is there to communicate.
  Future<void> _frameRadius(LatLng centre) async {
    final GoogleMapController? map = _map;
    if (map == null) return;

    // A degree of latitude is about 69 miles anywhere. A degree of longitude
    // is 69 miles only at the equator and shrinks by cos(latitude), which at
    // UK latitudes is roughly 0.6 — ignoring it would draw a box far too
    // narrow and clip the circle east and west.
    const double milesPerDegreeLat = 69.0;
    final double dLat = _radiusMiles / milesPerDegreeLat;
    final double dLng = _radiusMiles /
        (milesPerDegreeLat * math.cos(centre.latitude * math.pi / 180).abs());

    try {
      await map.animateCamera(
        CameraUpdate.newLatLngBounds(
          LatLngBounds(
            southwest: LatLng(centre.latitude - dLat, centre.longitude - dLng),
            northeast: LatLng(centre.latitude + dLat, centre.longitude + dLng),
          ),
          24,
        ),
      );
    } catch (_) {
      // Thrown when the map has not laid out yet. The initial camera position
      // is close enough that failing quietly is the right outcome.
    }
  }

  // ── Filters ──────────────────────────────────────────────────────────────

  Widget _filters() {
    final List<String> cats = _categories;
    // One category is not a filter, it is a label. Hiding the row entirely is
    // better than showing All and one chip that do the same thing.
    if (cats.length < 2) return const SizedBox(height: StaySpacing.inline);

    return Container(
      color: GoOutsColors.cardSurface,
      padding: const EdgeInsets.symmetric(vertical: StaySpacing.inline),
      child: SizedBox(
        height: 40,
        child: ListView(
          scrollDirection: Axis.horizontal,
          padding: const EdgeInsets.symmetric(horizontal: StaySpacing.page),
          children: <Widget>[
            _chip('All', null),
            for (final String c in cats) _chip(c, c),
          ],
        ),
      ),
    );
  }

  Widget _chip(String label, String? value) {
    final bool on = _category == value;
    return Padding(
      padding: const EdgeInsets.only(right: StaySpacing.card),
      child: Material(
        color: on ? GoOutsColors.primaryBlue : GoOutsColors.cardSurface,
        borderRadius: BorderRadius.circular(20),
        child: InkWell(
          borderRadius: BorderRadius.circular(20),
          onTap: () => setState(() => _category = value),
          child: Container(
            alignment: Alignment.center,
            padding:
                const EdgeInsets.symmetric(horizontal: StaySpacing.page),
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(20),
              border: Border.all(
                color: on ? Colors.transparent : GoOutsColors.outlineVariant,
              ),
            ),
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: <Widget>[
                Icon(_iconFor(value),
                    size: 16,
                    color:
                        on ? GoOutsColors.cardSurface : GoOutsColors.bodyText),
                const SizedBox(width: 6),
                Text(
                  label,
                  style: StayType.body.semibold.on(
                    on ? GoOutsColors.cardSurface : GoOutsColors.bodyText,
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  // ── Rows ─────────────────────────────────────────────────────────────────

  Widget _partnerRow(StayNearbyPartner p) => Container(
        margin: const EdgeInsets.only(bottom: StaySpacing.card),
        padding: const EdgeInsets.all(StaySpacing.inline),
        decoration: BoxDecoration(
          color: GoOutsColors.cardSurface,
          borderRadius: BorderRadius.circular(12),
        ),
        child: Row(
          children: <Widget>[
            Container(
              width: 44,
              height: 44,
              decoration: BoxDecoration(
                color: GoOutsColors.paleBlueTint,
                borderRadius: BorderRadius.circular(10),
              ),
              child: Icon(_iconFor(p.category),
                  size: 20, color: GoOutsColors.primaryBlue),
            ),
            const SizedBox(width: StaySpacing.inline),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: <Widget>[
                  Text(
                    p.name.isEmpty ? 'GoOuts partner' : p.name,
                    maxLines: 1,
                    overflow: TextOverflow.ellipsis,
                    style: StayType.cardTitle.on(GoOutsColors.deepNavy),
                  ),
                  const SizedBox(height: 2),
                  Text(
                    // ⚠ MILES. See the header. "0.4 miles away" is measured;
                    // "5 mins walk" would be a guess dressed as a fact.
                    <String>[
                      '${p.walkMi.toStringAsFixed(1)} miles away',
                      if (p.category.trim().isNotEmpty) p.category,
                    ].join('  •  '),
                    maxLines: 1,
                    overflow: TextOverflow.ellipsis,
                    style: StayType.body.on(GoOutsColors.bodyText),
                  ),
                ],
              ),
            ),
            const SizedBox(width: StaySpacing.card),
            // Only when there is a rate. A "0% cashback" chip on a partner
            // whose rate has not been set yet is worse than no chip.
            if (p.cashbackRate > 0)
              Container(
                padding: const EdgeInsets.symmetric(
                    horizontal: 10, vertical: 5),
                decoration: BoxDecoration(
                  color: GoOutsColors.paleBlueTint,
                  borderRadius: BorderRadius.circular(20),
                ),
                child: Text(
                  '${p.cashbackRate.toStringAsFixed(0)}%',
                  style: StayType.caption.bold.on(GoOutsColors.primaryBlue),
                ),
              ),
          ],
        ),
      );

  /// A guessable icon per category, and a shop for anything unrecognised.
  ///
  /// ⚠ MATCHED LOOSELY ON PURPOSE. The category strings come from the partner
  /// records, which were written by several onboarding flows over months, so
  /// "Cafe", "Coffee shop" and "Coffee" all exist. Matching on `contains`
  /// catches all three; an exact switch would drop two of them to the fallback.
  IconData _iconFor(String? category) {
    final String c = (category ?? '').toLowerCase();
    if (c.isEmpty) return Icons.apps;
    if (c.contains('restaurant') || c.contains('food') ||
        c.contains('dining')) {
      return Icons.restaurant;
    }
    if (c.contains('pub') || c.contains('bar') || c.contains('drink')) {
      return Icons.local_bar_outlined;
    }
    if (c.contains('cafe') || c.contains('coffee')) {
      return Icons.local_cafe_outlined;
    }
    if (c.contains('groc') || c.contains('market') || c.contains('store') ||
        c.contains('shop')) {
      return Icons.shopping_bag_outlined;
    }
    if (c.contains('beauty') || c.contains('salon') || c.contains('barber')) {
      return Icons.content_cut;
    }
    if (c.contains('gym') || c.contains('fitness')) {
      return Icons.fitness_center;
    }
    return Icons.storefront_outlined;
  }
}
