// Generated by Google Stitch, 3 August 2026. Source folder: 14-my_bookings
// Cleaned and consolidated by the pass described in
// goouts/design/SHORT_STAY_WIRING_PLAN.md part 1.
// NOT WIRED. Every handler in this file is still empty. See part 2.
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import '../theme/stay_colors.dart';

class MyBookingsScreen extends StatelessWidget {
  const MyBookingsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: 2,
      child: Scaffold(
        backgroundColor: GoOutsColors.background,
        appBar: AppBar(
          backgroundColor: Colors.white,
          elevation: 0.5,
          leading: IconButton(
            icon: const Icon(Icons.arrow_back, color: GoOutsColors.primaryBlue),
            onPressed: () => Navigator.of(context).pop(),
          ),
          title: Text(
            'My Bookings',
            style: GoogleFonts.inter(
              fontSize: 20,
              fontWeight: FontWeight.bold,
              color: GoOutsColors.deepNavy,
            ),
          ),
          bottom: TabBar(
            indicatorColor: GoOutsColors.primaryBlue,
            indicatorWeight: 3,
            labelColor: GoOutsColors.primaryBlue,
            unselectedLabelColor: GoOutsColors.bodyText,
            labelStyle: GoogleFonts.inter(fontWeight: FontWeight.bold, fontSize: 16),
            tabs: const [
              Tab(text: 'Upcoming'),
              Tab(text: 'Past'),
            ],
          ),
        ),
        body: TabBarView(
          children: [
            _buildUpcomingList(),
            const Center(child: Text('No past bookings')),
          ],
        ),
        bottomNavigationBar: _buildBottomNavBar(),
      ),
    );
  }

  Widget _buildUpcomingList() {
    return ListView(
      padding: const EdgeInsets.all(16),
      children: [
        _buildBookingCard(
          imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800',
          title: 'The Riverside Apartment',
          dates: '12 to 14 July',
          location: 'Richmond',
          status: 'CONFIRMED',
          statusColor: GoOutsColors.successGreen,
          daysAway: 'In 12 days',
        ),
        const SizedBox(height: 16),
        _buildBookingCard(
          imageUrl: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&q=80&w=800',
          title: 'Stow on the Wold',
          dates: '20 to 22 August',
          location: 'Cotswolds',
          status: 'PENDING',
          statusColor: GoOutsColors.pendingOrange,
        ),
        const SizedBox(height: 24),
        _buildManagementNote(),
      ],
    );
  }

  Widget _buildBookingCard({
    required String imageUrl,
    required String title,
    required String dates,
    required String location,
    required String status,
    required Color statusColor,
    String? daysAway,
  }) {
    return Container(
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.04),
            blurRadius: 10,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          ClipRRect(
            borderRadius: const BorderRadius.vertical(top: Radius.circular(16)),
            child: Image.network(
              imageUrl,
              height: 180,
              width: double.infinity,
              fit: BoxFit.cover,
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(16),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Expanded(
                      child: Text(
                        title,
                        style: GoogleFonts.inter(
                          fontSize: 18,
                          fontWeight: FontWeight.bold,
                          color: GoOutsColors.deepNavy,
                        ),
                      ),
                    ),
                    if (daysAway != null)
                      Text(
                        daysAway,
                        style: GoogleFonts.inter(
                          fontSize: 14,
                          fontWeight: FontWeight.w500,
                          color: GoOutsColors.primaryBlue,
                        ),
                      ),
                  ],
                ),
                const SizedBox(height: 4),
                Text(
                  dates,
                  style: GoogleFonts.inter(
                    fontSize: 15,
                    color: GoOutsColors.bodyText,
                  ),
                ),
                Text(
                  location,
                  style: GoogleFonts.inter(
                    fontSize: 15,
                    color: GoOutsColors.bodyText,
                  ),
                ),
                const SizedBox(height: 16),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Container(
                      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                      decoration: BoxDecoration(
                        color: statusColor.withValues(alpha: 0.1),
                        borderRadius: BorderRadius.circular(8),
                      ),
                      child: Text(
                        status,
                        style: GoogleFonts.inter(
                          fontSize: 12,
                          fontWeight: FontWeight.w800,
                          color: statusColor,
                          letterSpacing: 0.5,
                        ),
                      ),
                    ),
                    TextButton(
                      onPressed: () {},
                      child: Text(
                        'View Details',
                        style: GoogleFonts.inter(
                          fontSize: 14,
                          fontWeight: FontWeight.bold,
                          color: GoOutsColors.primaryBlue,
                        ),
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildManagementNote() {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: const Color(0xFFEFF6FF),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: const Color(0xFFDBEAFE)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'Booking Management',
            style: GoogleFonts.inter(
              fontSize: 16,
              fontWeight: FontWeight.bold,
              color: GoOutsColors.deepNavy,
            ),
          ),
          const SizedBox(height: 8),
          Text(
            'Your upcoming trips are displayed here. You can manage your check-in details or request changes by selecting a specific booking card.',
            style: GoogleFonts.inter(
              fontSize: 14,
              color: GoOutsColors.bodyText,
              height: 1.5,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildBottomNavBar() {
    return Container(
      height: 80,
      decoration: BoxDecoration(
        color: Colors.white,
        border: Border(top: BorderSide(color: Colors.grey.shade200)),
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        children: [
          _buildNavItem(Icons.search, 'Search', false),
          _buildNavItem(Icons.travel_explore, 'Trips', true),
          _buildNavItem(Icons.stars, 'Rewards', false),
          _buildNavItem(Icons.person, 'Profile', false),
        ],
      ),
    );
  }

  Widget _buildNavItem(IconData icon, String label, bool isActive) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        Icon(icon, color: isActive ? GoOutsColors.primaryBlue : GoOutsColors.bodyText),
        const SizedBox(height: 4),
        Text(
          label,
          style: GoogleFonts.inter(
            fontSize: 12,
            fontWeight: isActive ? FontWeight.bold : FontWeight.w500,
            color: isActive ? GoOutsColors.primaryBlue : GoOutsColors.bodyText,
          ),
        ),
      ],
    );
  }
}
