// Generated by Google Stitch, 3 August 2026. Source folder: 14-my_bookings
//
// WIRED 17 August 2026, task #116, Phase C.
//
// ── WHAT THIS REPLACED ───────────────────────────────────────────────────
//
// Two fixed cards — "The Riverside Apartment, 12 to 14 July, Richmond,
// CONFIRMED, In 12 days" and "Stow on the Wold, PENDING" — shown to every
// guest whether or not they had ever booked anything. The Past tab was
// `const Center(child: Text('No past bookings'))`, permanently. "View Details"
// had an empty handler.
//
// So a guest who had just booked saw somebody else's two trips and not their
// own, and could not open either.
//
// ── THE INDEX THIS NEEDED, WHICH DID NOT EXIST ───────────────────────────
//
// myBookings() filters on guestUid and orders by checkIn. That combination
// needs a composite index, and firestore.indexes.json had three stay_bookings
// indexes — all keyed on hostUid, built for the host app. The guest's own
// query had never had one, so it would have failed with FAILED_PRECONDITION
// the first time anybody opened this screen.
//
// Added guestUid + checkIn DESC. Same fault as mostPartnersNearby on the home
// screen: a guest-side query written weeks ago, never called, never indexed.
// ⚠ Needs DEPLOY_INDEXES.bat, and a new index takes minutes to build.
//
// ── WHY THE LISTINGS ARE FETCHED SEPARATELY ──────────────────────────────
//
// A booking stores listingId, not the title or the photo. Rather than one read
// per card, every id in the list goes through StayListingService.byIds, which
// chunks at 30 for whereIn. Ten bookings cost one extra query, not ten.
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import '../models/stay_booking.dart';
import '../models/stay_enums.dart';
import '../models/stay_listing.dart';
import '../services/stay_booking_service.dart';
import '../models/stay_reference.dart';
import '../services/stay_listing_service.dart';
import '../stay_routes.dart';
import '../theme/stay_colors.dart';
import '../widgets/desktop_top_nav.dart';
import '../widgets/stay_bottom_nav.dart';
import '15_trip_detail_screen.dart';

class MyBookingsScreen extends StatefulWidget {
  const MyBookingsScreen({super.key});

  @override
  State<MyBookingsScreen> createState() => _MyBookingsScreenState();
}

class _MyBookingsScreenState extends State<MyBookingsScreen> {
  /// listingId -> listing, filled as bookings arrive.
  final Map<String, StayListing> _listings = <String, StayListing>{};
  final Set<String> _requested = <String>{};

  // ── Desktop split view, added 14 September 2026 ───────────────────────
  //
  // Mobile keeps navigating away entirely (push to 15_trip_detail_screen.dart)
  // — these two fields only exist for the desktop branch below, which shows
  // the list and the selected booking's detail side by side and never pushes
  // a route to look at one.

  /// Which of the desktop's own Upcoming/Past tabs is showing. Separate from
  /// the mobile Scaffold's DefaultTabController — the desktop branch renders
  /// its own tab row rather than sharing that TabBar's widgets, so it needs
  /// its own index.
  int _desktopTabIndex = 0;

  /// The booking selected in the desktop left-hand list. Left null rather
  /// than defaulted eagerly in initState — the booking stream has not loaded
  /// anything yet at that point — so _buildDesktop falls back to "first
  /// booking in the current list" itself on every build until the guest
  /// actually clicks a card.
  String? _selectedBookingId;

  /// Loads any listing referenced by a booking that has not been fetched.
  ///
  /// Guarded by _requested so a rebuilding stream does not re-query the same
  /// ids forever — the StreamBuilder can rebuild many times per second while
  /// Firestore settles.
  void _ensureListings(List<StayBooking> bookings) {
    final List<String> missing = bookings
        .map((b) => b.listingId)
        .where((id) => id.isNotEmpty && !_requested.contains(id))
        .toSet()
        .toList();
    if (missing.isEmpty) return;

    _requested.addAll(missing);
    _fetchListings(missing);
  }

  /// try/catch, not .catchError.
  ///
  /// This was `.then(...).catchError((_) => <StayListing>[])`, which the
  /// analyzer rejects: the `then` returns `Future<void>`, so the error handler
  /// must return void or null — a list is not assignable to it. Awaiting in a
  /// plain async method sidesteps the whole question and reads better.
  Future<void> _fetchListings(List<String> ids) async {
    try {
      final List<StayListing> found =
          await StayListingService.instance.byIds(ids);
      if (!mounted) return;
      setState(() {
        for (final l in found) {
          _listings[l.id] = l;
        }
      });
    } catch (_) {
      // Swallowed on purpose. The dates, status and reference all come from
      // the booking itself; a missing title is a worse card, not a broken one.
    }
  }

  @override
  Widget build(BuildContext context) {
    // ── DESKTOP WEB SPLIT, added 14 September 2026 ─────────────────────────
    //
    // Same top-level shape as 01_short_stay_home_screen.dart and
    // 05_listing_detail_screen.dart: a LayoutBuilder picks a genuinely
    // separate desktop layout (own Scaffold, own DesktopTopNav, no mobile
    // AppBar/TabBar/bottomNavigationBar) rather than centering the mobile
    // column. _buildMobile below is exactly what build() produced before —
    // moved into a method, not rewritten — so width<900 (and any non-web
    // platform) is unchanged.
    return LayoutBuilder(
      builder: (context, constraints) {
        final bool desktop = kIsWeb && constraints.maxWidth >= 900;
        return desktop ? _buildDesktop(context) : _buildMobile(context);
      },
    );
  }

  Widget _buildMobile(BuildContext context) {
    return DefaultTabController(
      length: 2,
      child: Scaffold(
        backgroundColor: GoOutsColors.background,
        appBar: AppBar(
          backgroundColor: Colors.white,
          elevation: 0.5,
          leading: IconButton(
            icon: const Icon(Icons.arrow_back, color: GoOutsColors.primaryBlue),
            onPressed: () => Navigator.of(context).pop(),
          ),
          title: Text(
            'My Bookings',
            style: GoogleFonts.inter(
              fontSize: 20,
              fontWeight: FontWeight.w700,
              color: GoOutsColors.deepNavy,
            ),
          ),
          bottom: TabBar(
            indicatorColor: GoOutsColors.primaryBlue,
            indicatorWeight: 3,
            labelColor: GoOutsColors.primaryBlue,
            unselectedLabelColor: GoOutsColors.bodyText,
            labelStyle: GoogleFonts.inter(
                fontWeight: FontWeight.w700,
                fontSize: 15,
                letterSpacing: 0.3),
            tabs: const [
              Tab(text: 'Upcoming'),
              Tab(text: 'Past'),
            ],
          ),
        ),
        // A REAL bottom bar as of 28 August 2026. The one removed here was
        // Rewards / Profile with no tap handling on a screen that is PUSHED,
        // not a tab — so it was four dead labels sitting under a real app.
        bottomNavigationBar: const StayBottomNav(current: StayTab.trips),
        body: _bookingsBody(context, builder: (context, upcoming, past) {
          return TabBarView(
            children: [
              _list(upcoming, emptyTitle: 'No trips booked yet',
                  emptyBody: 'When you book somewhere, it appears here with '
                      'everything you need for the stay.'),
              _list(past, emptyTitle: 'Nothing here yet',
                  emptyBody: 'Stays you have finished, and any you cancelled, '
                      'are kept here.'),
            ],
          );
        }),
      ),
    );
  }

  // ══════════════════════════════════════════════════════════════════════════
  //  DESKTOP WEB LAYOUT — see the note at the top of build().
  // ══════════════════════════════════════════════════════════════════════════
  //
  // A genuine desktop split view, matching the Stitch reference
  // (06_desktop_my_bookings_trips): DesktopTopNav across the top, then
  // "My Trips" with the Upcoming/Past tabs beside it, then a Row — a narrow
  // scrollable list of bookings on the left, the selected booking's full
  // detail (15_trip_detail_screen.dart's own body, embedded rather than
  // pushed — see that file's `embedded` flag) filling the rest on the right.
  // Nothing here navigates; selecting a card just changes _selectedBookingId
  // and the right pane rebuilds in place.
  //
  // ⚠ THE STITCH MOCK'S GoCover/QR/KEYPAD BLOCKS ARE NOT REPRODUCED. Those
  // sections describe product surfaces (deposit protection status, a phone
  // hand-off QR code, a revealed keypad code) that do not exist anywhere in
  // this codebase — 15_trip_detail_screen.dart's own header comment explains
  // in detail why (no checkInTime/arrivalInstructions model, no host contact
  // fields guests can read). The right pane reuses exactly what that screen
  // already renders for real: claim banner, header, address, check-in/out,
  // when card, review prompt, message host, access instructions, arrival
  // photos, neighbourhood partners, house rules, map. Three tabs
  // (Upcoming/Completed/Cancelled) in the mock become the real two
  // (Upcoming/Past) this screen already has — inventing a third status
  // bucket the booking stream cannot produce would be the same mistake.

  Widget _buildDesktop(BuildContext context) {
    return Scaffold(
      backgroundColor: GoOutsColors.background,
      body: Column(
        children: [
          const DesktopTopNav(current: DesktopNavTab.stay),
          Expanded(
            child: DesktopCenter(
              maxWidth: 1200,
              child: _bookingsBody(context, builder: (context, upcoming, past) {
                final List<StayBooking> list =
                    _desktopTabIndex == 0 ? upcoming : past;

                // Falls back to the first booking in the CURRENT list — not
                // stored, just computed — whenever nothing is selected yet,
                // or the previous selection isn't in this list any more
                // (switched tabs, or that booking dropped out of Upcoming
                // because it just finished). Never mutates state during
                // build; _selectedBookingId only changes from a tap.
                final String? effectiveId = (_selectedBookingId != null &&
                        list.any((b) => b.id == _selectedBookingId))
                    ? _selectedBookingId
                    : (list.isEmpty ? null : list.first.id);
                final StayBooking? selected = effectiveId == null
                    ? null
                    : list.firstWhere((b) => b.id == effectiveId,
                        orElse: () => list.first);

                return Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const SizedBox(height: 28),
                    Row(
                      children: [
                        Text(
                          'My Trips',
                          style: GoogleFonts.inter(
                            fontSize: 28,
                            fontWeight: FontWeight.w800,
                            color: GoOutsColors.deepNavy,
                          ),
                        ),
                        const Spacer(),
                        _desktopTabButton('Upcoming (${upcoming.length})', 0),
                        const SizedBox(width: 8),
                        _desktopTabButton('Past (${past.length})', 1),
                      ],
                    ),
                    const SizedBox(height: 24),
                    Expanded(
                      child: list.isEmpty
                          ? _list(
                              list,
                              emptyTitle: _desktopTabIndex == 0
                                  ? 'No trips booked yet'
                                  : 'Nothing here yet',
                              emptyBody: _desktopTabIndex == 0
                                  ? 'When you book somewhere, it appears '
                                      'here with everything you need for '
                                      'the stay.'
                                  : 'Stays you have finished, and any you '
                                      'cancelled, are kept here.',
                            )
                          : Row(
                              crossAxisAlignment: CrossAxisAlignment.stretch,
                              children: [
                                SizedBox(
                                  width: 340,
                                  child: ListView.separated(
                                    padding: EdgeInsets.zero,
                                    itemCount: list.length,
                                    separatorBuilder: (_, __) =>
                                        const SizedBox(height: 10),
                                    itemBuilder: (context, i) =>
                                        _desktopBookingCard(
                                      list[i],
                                      selected: list[i].id == effectiveId,
                                    ),
                                  ),
                                ),
                                const SizedBox(width: 24),
                                Expanded(
                                  child: selected == null
                                      ? const SizedBox.shrink()
                                      // ⚠ KEYED ON THE BOOKING ID. Without a
                                      // key, Flutter would update the SAME
                                      // State object in place when a
                                      // different card is clicked — its
                                      // _listing field would briefly show the
                                      // PREVIOUS booking's property under the
                                      // new booking's dates until the new
                                      // listing finishes loading. The key
                                      // forces a fresh State per booking, so
                                      // the pane never shows a mismatched
                                      // pair.
                                      : TripDetailsScreen(
                                          key: ValueKey(selected.id),
                                          bookingId: selected.id,
                                          embedded: true,
                                        ),
                                ),
                              ],
                            ),
                    ),
                    const SizedBox(height: 24),
                  ],
                );
              }),
            ),
          ),
        ],
      ),
    );
  }

  Widget _desktopTabButton(String label, int index) {
    final bool active = _desktopTabIndex == index;
    return InkWell(
      onTap: () => setState(() {
        _desktopTabIndex = index;
        // Reset rather than try to carry a selection across tabs — the two
        // lists hold different bookings, and "first in the new list" is a
        // clearer default than silently keeping an id that may not be there.
        _selectedBookingId = null;
      }),
      borderRadius: BorderRadius.circular(8),
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
        decoration: BoxDecoration(
          color: active ? GoOutsColors.paleBlueTint : Colors.transparent,
          borderRadius: BorderRadius.circular(8),
        ),
        child: Text(
          label,
          style: GoogleFonts.inter(
            fontSize: 14,
            fontWeight: active ? FontWeight.w700 : FontWeight.w500,
            color: active ? GoOutsColors.primaryBlue : GoOutsColors.bodyText,
          ),
        ),
      ),
    );
  }

  /// Compact left-column card for the desktop split view: thumbnail, status
  /// chip, title, town, dates — the same facts _bookingCard shows, laid out
  /// horizontally for a ~340px column instead of stacked for a full-width
  /// mobile card. Selecting one updates _selectedBookingId in place; nothing
  /// navigates on desktop.
  Widget _desktopBookingCard(StayBooking b, {required bool selected}) {
    final StayListing? listing = _listings[b.listingId];
    final chip = _statusChip(b.status);
    final List<StayPhoto> photos =
        List<StayPhoto>.from(listing?.photos ?? const <StayPhoto>[])
          ..sort((a, b2) => a.order.compareTo(b2.order));

    return Material(
      color: selected ? GoOutsColors.paleBlueTint : Colors.white,
      borderRadius: BorderRadius.circular(12),
      child: InkWell(
        onTap: () => setState(() => _selectedBookingId = b.id),
        borderRadius: BorderRadius.circular(12),
        child: Container(
          padding: const EdgeInsets.all(10),
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(12),
            border: Border.all(
              color: selected
                  ? GoOutsColors.primaryBlue
                  : GoOutsColors.dividerGray,
              width: selected ? 1.5 : 1,
            ),
          ),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(8),
                child: photos.isEmpty
                    ? Container(
                        width: 64,
                        height: 64,
                        color: GoOutsColors.paleBlueTint,
                        child: const Icon(Icons.home_outlined,
                            size: 24, color: GoOutsColors.primaryBlue),
                      )
                    : Image.network(
                        photos.first.url,
                        width: 64,
                        height: 64,
                        fit: BoxFit.cover,
                        errorBuilder: (_, __, ___) => Container(
                          width: 64,
                          height: 64,
                          color: GoOutsColors.paleBlueTint,
                          child: const Icon(Icons.home_outlined,
                              size: 24, color: GoOutsColors.primaryBlue),
                        ),
                      ),
              ),
              const SizedBox(width: 10),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Container(
                      padding: const EdgeInsets.symmetric(
                          horizontal: 8, vertical: 3),
                      decoration: BoxDecoration(
                        color: chip.colour.withValues(alpha: 0.1),
                        borderRadius: BorderRadius.circular(6),
                      ),
                      child: Text(
                        chip.label,
                        style: GoogleFonts.inter(
                          fontSize: 10,
                          fontWeight: FontWeight.w700,
                          color: chip.colour,
                          letterSpacing: 0.4,
                        ),
                      ),
                    ),
                    const SizedBox(height: 6),
                    Text(
                      listing?.title ??
                          'Booking ${stayBookingReference(b.id)}',
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                      style: GoogleFonts.inter(
                        fontSize: 13.5,
                        fontWeight: FontWeight.w700,
                        color: GoOutsColors.deepNavy,
                      ),
                    ),
                    if ((listing?.address.town ?? '').isNotEmpty)
                      Text(
                        listing!.address.town,
                        maxLines: 1,
                        overflow: TextOverflow.ellipsis,
                        style: GoogleFonts.inter(
                            fontSize: 12, color: GoOutsColors.bodyText),
                      ),
                    const SizedBox(height: 2),
                    Text(
                      _dateRange(b.checkIn, b.checkOut),
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                      style: GoogleFonts.inter(
                          fontSize: 12, color: GoOutsColors.bodyText),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  /// The real booking stream, filtered into Upcoming/Past exactly as before
  /// — factored out of build() on 14 September 2026 so both _buildMobile
  /// (TabBarView) and _buildDesktop (its own tab row + split pane) read the
  /// same data through the same StreamBuilder instead of two copies of this
  /// filtering logic drifting apart.
  Widget _bookingsBody(
    BuildContext context, {
    required Widget Function(BuildContext context, List<StayBooking> upcoming,
            List<StayBooking> past)
        builder,
  }) {
    return StreamBuilder<List<StayBooking>>(
      stream: StayBookingService.instance.myBookings(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Center(child: CircularProgressIndicator());
        }
        if (snapshot.hasError) {
          return _error(snapshot.error.toString());
        }

        final List<StayBooking> all = snapshot.data ?? const <StayBooking>[];
        _ensureListings(all);

        final DateTime today = DateTime.now();
        // "Upcoming" means the stay has not finished AND was not called
        // off. A cancelled trip next month belongs in Past — it is not
        // something the guest is going on.
        final upcoming = all
            .where((b) =>
                !b.status.isCancelled &&
                b.status != BookingStatus.declined &&
                b.checkOut.isAfter(today))
            .toList()
          ..sort((a, b) => a.checkIn.compareTo(b.checkIn));

        final past = all.where((b) => !upcoming.contains(b)).toList()
          ..sort((a, b) => b.checkIn.compareTo(a.checkIn));

        return builder(context, upcoming, past);
      },
    );
  }

  Widget _error(String message) => Center(
        child: Padding(
          padding: const EdgeInsets.all(32),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              const Icon(Icons.cloud_off, size: 48,
                  color: GoOutsColors.primaryBlue),
              const SizedBox(height: 12),
              Text(
                'Your bookings could not be loaded',
                textAlign: TextAlign.center,
                style: GoogleFonts.inter(
                    fontSize: 14,
                    fontWeight: FontWeight.w600,
                    color: GoOutsColors.deepNavy),
              ),
              const SizedBox(height: 8),
              // The real error, not "something went wrong". A failed-precondition
              // here means the guestUid + checkIn index has not finished
              // building, and that is worth being able to read rather than
              // guess at.
              Text(
                message,
                textAlign: TextAlign.center,
                style: GoogleFonts.inter(
                    fontSize: 12, color: GoOutsColors.bodyText),
              ),
            ],
          ),
        ),
      );

  Widget _list(List<StayBooking> bookings,
      {required String emptyTitle, required String emptyBody}) {
    if (bookings.isEmpty) {
      return Center(
        child: Padding(
          padding: const EdgeInsets.all(32),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              const Icon(Icons.luggage_outlined,
                  size: 48, color: GoOutsColors.primaryBlue),
              const SizedBox(height: 12),
              Text(
                emptyTitle,
                style: GoogleFonts.inter(
                    fontSize: 14,
                    fontWeight: FontWeight.w600,
                    color: GoOutsColors.deepNavy),
              ),
              const SizedBox(height: 6),
              Text(
                emptyBody,
                textAlign: TextAlign.center,
                style: GoogleFonts.inter(
                    fontSize: 14, color: GoOutsColors.bodyText),
              ),
            ],
          ),
        ),
      );
    }

    return ListView.separated(
      padding: const EdgeInsets.all(16),
      itemCount: bookings.length,
      separatorBuilder: (_, __) => const SizedBox(height: 16),
      itemBuilder: (context, i) => _bookingCard(bookings[i]),
    );
  }

  // ── Status ───────────────────────────────────────────────────────────────
  //
  // Every status the enum can hold gets a label and a colour. A switch with no
  // default means adding a status to BookingStatus breaks the build here
  // rather than rendering a blank chip.
  ({String label, Color colour}) _statusChip(BookingStatus s) {
    switch (s) {
      case BookingStatus.pending:
        return (label: 'AWAITING HOST', colour: GoOutsColors.pendingOrange);
      case BookingStatus.confirmed:
        return (label: 'CONFIRMED', colour: GoOutsColors.successGreen);
      case BookingStatus.inProgress:
        return (label: 'YOU ARE THERE', colour: GoOutsColors.primaryBlue);
      case BookingStatus.completed:
        return (label: 'COMPLETED', colour: GoOutsColors.bodyText);
      case BookingStatus.declined:
        return (label: 'DECLINED', colour: GoOutsColors.error);
      case BookingStatus.cancelledGuest:
        return (label: 'YOU CANCELLED', colour: GoOutsColors.error);
      case BookingStatus.cancelledHost:
        return (label: 'HOST CANCELLED', colour: GoOutsColors.error);
      case BookingStatus.disputed:
        return (label: 'UNDER REVIEW', colour: GoOutsColors.warning);
    }
  }

  static const List<String> _months = <String>[
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December',
  ];

  /// "12 to 14 July" when one month, "30 July to 2 August" when it spans two.
  static String _dateRange(DateTime a, DateTime b) => a.month == b.month
      ? '${a.day} to ${b.day} ${_months[b.month - 1]}'
      : '${a.day} ${_months[a.month - 1]} to ${b.day} ${_months[b.month - 1]}';

  /// null when the stay is not ahead of us.
  static String? _countdown(DateTime checkIn) {
    final DateTime today = DateTime.now();
    final int days = DateTime(checkIn.year, checkIn.month, checkIn.day)
        .difference(DateTime(today.year, today.month, today.day))
        .inDays;
    if (days < 0) return null;
    if (days == 0) return 'Today';
    if (days == 1) return 'Tomorrow';
    return 'In $days days';
  }

  Widget _bookingCard(StayBooking b) {
    final StayListing? listing = _listings[b.listingId];
    final chip = _statusChip(b.status);
    final String? countdown =
        b.status.isCancelled || b.status == BookingStatus.declined
            ? null
            : _countdown(b.checkIn);

    final List<StayPhoto> photos =
        List<StayPhoto>.from(listing?.photos ?? const <StayPhoto>[])
          ..sort((a, b2) => a.order.compareTo(b2.order));

    return InkWell(
      onTap: () => Navigator.of(context).pushNamed(
        StayRoutes.bookingDetails,
        arguments: <String, dynamic>{'bookingId': b.id},
      ),
      borderRadius: BorderRadius.circular(16),
      child: Container(
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(16),
          boxShadow: [
            BoxShadow(
              color: Colors.black.withValues(alpha: 0.04),
              blurRadius: 10,
              offset: const Offset(0, 4),
            ),
          ],
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            ClipRRect(
              borderRadius:
                  const BorderRadius.vertical(top: Radius.circular(16)),
              child: photos.isEmpty
                  ? Container(
                      height: 180,
                      width: double.infinity,
                      color: GoOutsColors.paleBlueTint,
                      child: const Icon(Icons.home_outlined,
                          size: 44, color: GoOutsColors.primaryBlue),
                    )
                  : Image.network(
                      photos.first.url,
                      height: 180,
                      width: double.infinity,
                      fit: BoxFit.cover,
                      errorBuilder: (_, __, ___) => Container(
                        height: 180,
                        width: double.infinity,
                        color: GoOutsColors.paleBlueTint,
                        child: const Icon(Icons.home_outlined,
                            size: 44, color: GoOutsColors.primaryBlue),
                      ),
                    ),
            ),
            Padding(
              padding: const EdgeInsets.all(16),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Expanded(
                        child: Text(
                          // Falls back to the reference while the listing
                          // loads, so the card is never nameless.
                          // ⚠ THE SHORT CODE, NOT THE RAW ID. Screen 13 shows
                          // GOS-XXXXX-X, so a fallback printing the twenty
                          // character Firestore id here would give a guest two
                          // different strings for the same booking.
                          listing?.title ??
                              'Booking ${stayBookingReference(b.id)}',
                          overflow: TextOverflow.ellipsis,
                          style: GoogleFonts.inter(
                            fontSize: 14,
                            fontWeight: FontWeight.w600,
                            color: GoOutsColors.deepNavy,
                          ),
                        ),
                      ),
                      if (countdown != null) ...[
                        const SizedBox(width: 8),
                        Text(
                          countdown,
                          style: GoogleFonts.inter(
                            fontSize: 14,
                            fontWeight: FontWeight.w500,
                            color: GoOutsColors.primaryBlue,
                          ),
                        ),
                      ],
                    ],
                  ),
                  const SizedBox(height: 4),
                  Text(
                    '${_dateRange(b.checkIn, b.checkOut)} · '
                    '${b.nights} ${b.nights == 1 ? 'night' : 'nights'}',
                    style: GoogleFonts.inter(
                        fontSize: 15, color: GoOutsColors.bodyText),
                  ),
                  if ((listing?.address.town ?? '').isNotEmpty)
                    Text(
                      listing!.address.town,
                      style: GoogleFonts.inter(
                          fontSize: 15, color: GoOutsColors.bodyText),
                    ),
                  const SizedBox(height: 16),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Container(
                        padding: const EdgeInsets.symmetric(
                            horizontal: 12, vertical: 6),
                        decoration: BoxDecoration(
                          color: chip.colour.withValues(alpha: 0.1),
                          borderRadius: BorderRadius.circular(8),
                        ),
                        child: Text(
                          chip.label,
                          style: GoogleFonts.inter(
                            fontSize: 12,
                            fontWeight: FontWeight.w700,
                            color: chip.colour,
                            letterSpacing: 0.5,
                          ),
                        ),
                      ),
                      Text(
                        'View details',
                        style: GoogleFonts.inter(
                          fontSize: 14,
                          fontWeight: FontWeight.w600,
                          color: GoOutsColors.primaryBlue,
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
