// Generated by Google Stitch, 3 August 2026. Source folder: 15-trip_detail
//
// WIRED 17 August 2026, task #116, Phase C.
//
// ── FOUR OF THIS SCREEN'S SIX SECTIONS HAD NO DATA BEHIND THEM ───────────
//
// The Stitch version showed check-in and check-out times, the host's name and
// phone number, written access instructions, and a map. Checked against the
// model before rebuilding:
//
//   check-in / check-out times   NOT on StayListing. Not collected by the
//                                host wizard either.
//   access instructions          Same. No field, nowhere to enter one.
//   house rules                  Same.
//   host name / phone            Guests cannot read /stay_hosts under the
//                                security rules. Same wall screen 05 hit with
//                                "Hosted by Sarah".
//
// So this was not an unwired screen. It was a screen describing a product that
// does not exist yet, and wiring it would have meant inventing a check-in time
// for somebody's holiday.
//
// What it shows instead is everything that IS real and that a guest actually
// needs while travelling: where the property is, when they are there, the
// photographs that protect their deposit, and the GoOuts partners around them
// — which is the one thing on this screen no other platform could show.
//
// ⚠ THE MISSING FIELDS ARE A HOST WIZARD JOB, NOT A SCREEN JOB. Adding
// checkInTime, checkOutTime and arrivalInstructions to the listing model and
// to host_04 is what unblocks the rest of this screen. Until then, the note at
// the bottom tells the guest the truth: the host sends arrival details
// directly.
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:url_launcher/url_launcher.dart';

import '../models/stay_booking.dart';
import '../models/stay_enums.dart';
import '../models/stay_evidence.dart';
import '../models/stay_listing.dart';
import '../services/stay_booking_service.dart';
import '../services/stay_claim_service.dart';
import '../services/stay_evidence_service.dart';
import '../services/stay_listing_service.dart';
import '../stay_routes.dart';
import '../theme/stay_colors.dart';
import '../widgets/stay_bottom_nav.dart';

class TripDetailsScreen extends StatefulWidget {
  const TripDetailsScreen({super.key, required this.bookingId});

  final String bookingId;

  @override
  State<TripDetailsScreen> createState() => _TripDetailsScreenState();
}

class _TripDetailsScreenState extends State<TripDetailsScreen> {
  StayListing? _listing;
  String? _loadedFor;

  void _ensureListing(String listingId) {
    if (listingId.isEmpty || _loadedFor == listingId) return;
    _loadedFor = listingId;
    StayListingService.instance.byId(listingId).then((l) {
      if (!mounted) return;
      setState(() => _listing = l);
    }).catchError((_) => null);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: GoOutsColors.background,
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0.5,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: GoOutsColors.primaryBlue),
          onPressed: () => Navigator.of(context).pop(),
        ),
        // "Trip details", matching Stitch. Renamed 27 August 2026.
        title: Text(
          'Trip details',
          style: GoogleFonts.inter(
            fontSize: 20,
            height: 28 / 20,
            fontWeight: FontWeight.w700,
            color: GoOutsColors.primaryBlue,
          ),
        ),
      ),
      // A REAL bottom bar as of 28 August 2026. What was removed from here
      // was four dead labels; StayBottomNav actually navigates, and resets the
      // stack rather than pushing another copy of a screen you are already on.
      bottomNavigationBar: const StayBottomNav(current: StayTab.trips),
      body: StreamBuilder<StayBooking?>(
        stream: StayBookingService.instance.watch(widget.bookingId),
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Center(child: CircularProgressIndicator());
          }
          final StayBooking? b = snapshot.data;
          if (b == null) {
            return Center(
              child: Padding(
                padding: const EdgeInsets.all(32),
                child: Text('This trip could not be loaded.',
                    style: GoogleFonts.inter(
                        fontSize: 15, color: GoOutsColors.bodyText)),
              ),
            );
          }
          _ensureListing(b.listingId);

          return ListView(
            padding: const EdgeInsets.all(16),
            children: [
              // ── ⚠ A CLAIM MUST BE FINDABLE WITHOUT THE NOTIFICATION ───────
              //
              // Added 25 August 2026 with the claims flow. The push is the only
              // other way a guest learns a claim has been made against them,
              // and pushes get dismissed, silenced, or never granted at all.
              //
              // A 72 hour clock the person cannot see running is not a window,
              // it is a trapdoor — so it sits at the TOP of this screen, above
              // the trip itself, for as long as it is waiting on them.
              // ── Order follows Stitch 15-trip_detail. 27 August 2026. ──────
              //
              // Stitch runs: property and address with Directions, the two
              // check-in and check-out cards, the host, access instructions,
              // the check-in photos block, then quick links, then a map.
              //
              // The claim banner stays ABOVE all of it, for the reason above.
              // Everything else is Stitch's sequence.
              _claimBanner(b.id),
              _header(b),
              _addressRow(),
              const SizedBox(height: 16),
              _checkTimesRow(),
              const SizedBox(height: 16),
              _whenCard(b),
              const SizedBox(height: 16),
              _contactHostCard(b),
              const SizedBox(height: 16),
              _accessCard(),
              const SizedBox(height: 16),
              _photosCard(b),
              if (_listing?.locationContext != null) ...[
                const SizedBox(height: 16),
                _partnersCard(_listing!.locationContext!),
              ],
              _houseRulesCard(),
              const SizedBox(height: 16),
              _mapCard(),
              const SizedBox(height: 24),
            ],
          );
        },
      ),
    );
  }

  Widget _card(Widget child) => Container(
        padding: const EdgeInsets.all(16),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(12),
        ),
        child: child,
      );

  static const List<String> _months = <String>[
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December',
  ];
  static String _d(DateTime d) => '${d.day} ${_months[d.month - 1]}';

  // ── Header ───────────────────────────────────────────────────────────────

  /// Shows only while a claim on THIS booking is waiting on this guest.
  ///
  /// ⚠ SCOPED TO THE BOOKING, NOT TO THE PERSON. watchMyClaims returns every
  /// claim against them; filtering here means a claim on a different trip does
  /// not appear on this one, which would be alarming and useless in equal
  /// measure.
  ///
  /// ⚠ SILENT ON ERROR AND WHILE LOADING. A red box saying "could not check
  /// for claims" on a screen somebody opened to look at their holiday is worse
  /// than the small chance of a missed banner — and the push notification and
  /// the claim screen itself are both still there.
  Widget _claimBanner(String bookingId) => StreamBuilder<List<StayClaim>>(
        // ⚠ watchAwaitingReplyClaims, NOT watchMyClaims.
        //
        // The first version streamed the guest's last 20 claims of any status
        // on every open of every trip screen, then threw almost all of them
        // away client-side. This asks the server for the only ones that can
        // possibly produce a banner — status awaiting_guest — which for nearly
        // every guest is an empty result set costing one document read.
        stream: StayClaimService.instance.watchAwaitingReplyClaims(),
        builder: (BuildContext c, AsyncSnapshot<List<StayClaim>> snap) {
          if (!snap.hasData || snap.hasError) return const SizedBox.shrink();
          final Iterable<StayClaim> mine = snap.data!
              .where((StayClaim x) => x.bookingId == bookingId);
          if (mine.isEmpty) return const SizedBox.shrink();
          final StayClaim claim = mine.first;

          return Padding(
            padding: const EdgeInsets.only(bottom: 16),
            child: InkWell(
              onTap: () => Navigator.of(context).pushNamed(
                StayRoutes.claim,
                arguments: <String, dynamic>{'claimId': claim.id},
              ),
              borderRadius: BorderRadius.circular(12),
              child: Container(
                padding: const EdgeInsets.all(14),
                decoration: BoxDecoration(
                  color: const Color(0xFFFEF2F2),
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(color: const Color(0xFFFECACA)),
                ),
                child: Row(
                  children: <Widget>[
                    const Icon(Icons.report_gmailerrorred_outlined,
                        color: Color(0xFFB91C1C), size: 22),
                    const SizedBox(width: 12),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: <Widget>[
                          Text('Your host has made a damage claim',
                              style: GoogleFonts.inter(
                                  fontSize: 13.5,
                                  fontWeight: FontWeight.w700,
                                  color: const Color(0xFF991B1B))),
                          const SizedBox(height: 2),
                          Text(
                            '£${claim.amount.toStringAsFixed(2)} — tap to read '
                            'it and respond.',
                            style: GoogleFonts.inter(
                                fontSize: 13.5,
                                height: 1.4,
                                color: const Color(0xFFB91C1C)),
                          ),
                        ],
                      ),
                    ),
                    const Icon(Icons.chevron_right_rounded,
                        color: Color(0xFFB91C1C)),
                  ],
                ),
              ),
            ),
          );
        },
      );

  Widget _header(StayBooking b) {
    final List<StayPhoto> photos =
        List<StayPhoto>.from(_listing?.photos ?? const <StayPhoto>[])
          ..sort((a, b2) => a.order.compareTo(b2.order));

    return ClipRRect(
      borderRadius: BorderRadius.circular(12),
      child: Stack(
        children: [
          photos.isEmpty
              ? Container(
                  height: 160,
                  width: double.infinity,
                  color: GoOutsColors.paleBlueTint,
                  child: const Icon(Icons.home_outlined,
                      size: 48, color: GoOutsColors.primaryBlue),
                )
              : Image.network(
                  photos.first.url,
                  height: 160,
                  width: double.infinity,
                  fit: BoxFit.cover,
                  errorBuilder: (_, __, ___) => Container(
                    height: 160,
                    color: GoOutsColors.paleBlueTint,
                  ),
                ),
          Positioned(
            left: 0,
            right: 0,
            bottom: 0,
            child: Container(
              padding: const EdgeInsets.all(12),
              color: Colors.black.withValues(alpha: 0.45),
              child: Text(
                _listing?.title ?? 'Your stay',
                style: GoogleFonts.inter(
                  fontSize: 15,
                  height: 20 / 15,
                  fontWeight: FontWeight.w700,
                  color: Colors.white,
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  // ── Address and Directions ────────────────────────────────────────────────
  //
  // Stitch puts the address directly under the property with a Directions
  // button beside it, rather than in a card of its own further down. Folded in
  // here on 27 August 2026 and _addressCard retired, because two places showing
  // the same address is how one of them ends up stale.
  //
  // ⚠ THE FULL ADDRESS IS SHOWN, unlike screen 05 which deliberately shows only
  // a 300m circle and the town. That difference is the point: this screen only
  // opens on a booking the guest holds, so they are entitled to the address.
  Widget _addressRow() {
    final StayAddress? a = _listing?.address;
    if (a == null || (a.line1.isEmpty && a.postcode.isEmpty)) {
      return const SizedBox.shrink();
    }

    final String full = <String>[
      if (a.line1.isNotEmpty) a.line1,
      if (a.town.isNotEmpty) a.town,
      if (a.postcode.isNotEmpty) a.postcode,
    ].join(', ');

    return Padding(
      padding: const EdgeInsets.only(top: 12),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.center,
        children: <Widget>[
          Expanded(
            child: Text(
              full,
              style: GoogleFonts.inter(
                  fontSize: 13.5,
                  height: 20 / 13.5,
                  color: GoOutsColors.bodyText),
            ),
          ),
          const SizedBox(width: 12),
          OutlinedButton(
            onPressed: () => _openMaps(full),
            style: OutlinedButton.styleFrom(
              foregroundColor: GoOutsColors.primaryBlue,
              side: const BorderSide(color: GoOutsColors.outlineVariant),
              shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(10)),
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
            ),
            child: Text('Directions',
                style: GoogleFonts.inter(
                    fontSize: 14, fontWeight: FontWeight.w600)),
          ),
        ],
      ),
    );
  }

  /// Opens the platform's maps app at the property.
  ///
  /// ⚠ COORDINATES WHEN WE HAVE THEM, THE ADDRESS WHEN WE DO NOT. A postcode
  /// search can land on the wrong side of a large postcode; lat/lng cannot. The
  /// address is the fallback rather than the first choice.
  ///
  /// Never throws. A device with no maps app is not a reason to crash a screen
  /// somebody opened to look at their holiday.
  Future<void> _openMaps(String address) async {
    final double? lat = _listing?.lat;
    final double? lng = _listing?.lng;
    final String q = (lat != null && lng != null)
        ? '$lat,$lng'
        : Uri.encodeComponent(address);

    final Uri uri = Uri.parse('https://www.google.com/maps/search/?api=1&query=$q');
    try {
      await launchUrl(uri, mode: LaunchMode.externalApplication);
    } catch (_) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('No maps app could be opened.')),
      );
    }
  }

  // ── When ─────────────────────────────────────────────────────────────────
  //
  // ⚠ THE TIMES ARE REAL NOW. Updated 27 August 2026.
  //
  // This said "Dates only. NOT times — the listing has no checkInTime or
  // checkOutTime and the host wizard does not ask for one, so any clock shown
  // here would have been chosen by this screen rather than by the host."
  //
  // That was true and it was the right call. Reported as "there is no rules
  // shows to consumer check in and check out", so it was fixed at the source
  // rather than papered over here: host wizard step 7 now asks, createStayListing
  // validates and stores, StayListing parses. See stay_listing.dart.
  //
  // ⚠ STILL NOT CHOSEN BY THIS SCREEN. The times come from `_listing`, which
  // may not have loaded yet or may be null if the read failed — in which case
  // the rows are simply absent, exactly as before. Nothing here invents 15:00.

  Widget _whenCard(StayBooking b) {
    final int nightsLeft = b.checkOut.difference(DateTime.now()).inDays;
    // `l` was read here for the check-in and check-out times. Those moved out
    // into _checkTimesRow on 27 August 2026, so nothing in this card needs the
    // listing any more.

    return _card(
      Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text('When',
              style: GoogleFonts.inter(
                  fontSize: 16,
                  fontWeight: FontWeight.bold,
                  color: GoOutsColors.deepNavy)),
          const SizedBox(height: 12),
          Row(
            children: [
              Expanded(child: _fact('Arrive', _d(b.checkIn))),
              Expanded(child: _fact('Leave', _d(b.checkOut))),
              Expanded(
                child: _fact('Nights', '${b.nights}'),
              ),
            ],
          ),
          // The times moved OUT of this card on 27 August 2026, into the two
          // side-by-side cards Stitch draws above it. Left here as a note so
          // nobody adds them back and shows the same fact twice.
          if (b.status == BookingStatus.inProgress && nightsLeft >= 0) ...[
            const SizedBox(height: 12),
            Text(
              nightsLeft == 0
                  ? 'You leave today.'
                  : 'You have $nightsLeft '
                      '${nightsLeft == 1 ? 'night' : 'nights'} left.',
              style: GoogleFonts.inter(
                  fontSize: 13.5, color: GoOutsColors.bodyText),
            ),
          ],
        ],
      ),
    );
  }

  Widget _fact(String label, String value) => Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(label,
              style: GoogleFonts.inter(
                  fontSize: 12, color: GoOutsColors.bodyText)),
          const SizedBox(height: 2),
          Text(value,
              style: GoogleFonts.inter(
                  fontSize: 15,
                  fontWeight: FontWeight.w700,
                  color: GoOutsColors.deepNavy)),
        ],
      );

  // ── Where ────────────────────────────────────────────────────────────────
  //
  // The real address. This is the single most useful thing on the screen for
  // somebody actually travelling, and it was not on the Stitch version at all
  // — that had a map picture instead.

  // _addressCard was retired 27 August 2026. Stitch puts the address under
  // the property with a Directions button, which is _addressRow above. Two
  // places rendering one address is how one of them goes stale.

  Widget _contactHostCard(StayBooking b) => _card(
        Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Need something?',
              style: GoogleFonts.inter(
                fontSize: 15,
                fontWeight: FontWeight.w700,
                color: GoOutsColors.deepNavy,
              ),
            ),
            const SizedBox(height: 6),
            Text(
              'Message your host about arrival, keys, parking or anything '
              'that is not right. They see it in their GoOuts Host app.',
              style: GoogleFonts.inter(
                fontSize: 13.5,
                height: 1.4,
                color: GoOutsColors.bodyText,
              ),
            ),
            const SizedBox(height: 12),
            SizedBox(
              width: double.infinity,
              child: FilledButton.icon(
                onPressed: () => Navigator.of(context).pushNamed(
                  StayRoutes.messageHost,
                  arguments: <String, dynamic>{'bookingId': b.id},
                ),
                icon: const Icon(Icons.chat_bubble_outline_rounded, size: 18),
                label: const Text('Message your host'),
                style: FilledButton.styleFrom(
                  minimumSize: const Size(0, 46),
                  backgroundColor: GoOutsColors.primaryBlue,
                  foregroundColor: Colors.white,
                ),
              ),
            ),
          ],
        ),
      );

  Widget _photosCard(StayBooking b) {
    return StreamBuilder<List<StayEvidence>>(
      stream: StayEvidenceService.instance
          .watchKind(widget.bookingId, CaptureKind.guestCheckIn),
      builder: (context, snap) {
        final List<StayEvidence> taken =
            (snap.data ?? const <StayEvidence>[])
                .where((e) => !e.skipped)
                .toList(growable: false);

        return _card(
          Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text('Arrival photographs',
                  style: GoogleFonts.inter(
                      fontSize: 16,
                      fontWeight: FontWeight.bold,
                      color: GoOutsColors.deepNavy)),
              const SizedBox(height: 4),
              Text(
                taken.isEmpty
                    ? 'Take these when you arrive. They are your evidence if a '
                        'damage claim is made.'
                    : '${taken.length} '
                        '${taken.length == 1 ? 'photograph' : 'photographs'} '
                        'held for your arrival.',
                style: GoogleFonts.inter(
                    fontSize: 13.5,
                    height: 1.35,
                    color: GoOutsColors.bodyText),
              ),
              const SizedBox(height: 12),
              Row(
                children: [
                  Expanded(
                    child: OutlinedButton.icon(
                      onPressed: () => Navigator.of(context).pushNamed(
                        StayRoutes.captureIntro,
                        arguments: <String, dynamic>{
                          'bookingId': b.id,
                          'captureKind': CaptureKind.guestCheckIn.wire,
                        },
                      ),
                      icon: const Icon(Icons.photo_camera_outlined, size: 18),
                      label: Text(taken.isEmpty ? 'Take them' : 'Add more'),
                      style: OutlinedButton.styleFrom(
                        minimumSize: const Size(0, 44),
                        foregroundColor: GoOutsColors.primaryBlue,
                        side: const BorderSide(
                            color: GoOutsColors.primaryBlue),
                      ),
                    ),
                  ),
                  if (taken.isNotEmpty) ...[
                    const SizedBox(width: 10),
                    Expanded(
                      child: TextButton(
                        onPressed: () => Navigator.of(context).pushNamed(
                          StayRoutes.evidencePack,
                          arguments: <String, dynamic>{'bookingId': b.id},
                        ),
                        child: const Text('View all'),
                      ),
                    ),
                  ],
                ],
              ),
            ],
          ),
        );
      },
    );
  }

  // ── Partners ─────────────────────────────────────────────────────────────
  //
  // The reason to book through GoOuts rather than anywhere else, and the most
  // useful thing on this screen once somebody has arrived.

  Widget _partnersCard(StayLocationContext ctx) {
    final int half = ctx.partnerCounts.halfMile;
    if (half <= 0) return const SizedBox.shrink();

    final List<StayNearbyPartner> nearest =
        ctx.nearestPartners.take(4).toList(growable: false);

    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: GoOutsColors.primaryBlue,
        borderRadius: BorderRadius.circular(12),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            '$half GoOuts ${half == 1 ? 'partner' : 'partners'} '
            'within half a mile',
            style: GoogleFonts.inter(
                fontSize: 16,
                fontWeight: FontWeight.bold,
                color: Colors.white),
          ),
          const SizedBox(height: 4),
          Text(
            'Earn cashback on your coffee, dinner and shopping while you are '
            'here.',
            style: GoogleFonts.inter(
                fontSize: 13.5,
                height: 1.35,
                color: Colors.white.withValues(alpha: 0.9)),
          ),
          if (nearest.isNotEmpty) ...[
            const SizedBox(height: 12),
            for (final p in nearest)
              Padding(
                padding: const EdgeInsets.only(bottom: 6),
                child: Row(
                  children: [
                    const Icon(Icons.storefront_outlined,
                        size: 16, color: Colors.white),
                    const SizedBox(width: 8),
                    Expanded(
                      child: Text(
                        p.name,
                        overflow: TextOverflow.ellipsis,
                        style: GoogleFonts.inter(
                            fontSize: 13.5, color: Colors.white),
                      ),
                    ),
                    Text(
                      '${p.walkMi.toStringAsFixed(1)} mi',
                      style: GoogleFonts.inter(
                          fontSize: 12,
                          color: Colors.white.withValues(alpha: 0.85)),
                    ),
                  ],
                ),
              ),
          ],
        ],
      ),
    );
  }

  // ── The honest note ──────────────────────────────────────────────────────

  // ── Check in / Check out, the two Stitch cards ────────────────────────────
  //
  // Stitch gives these their own pair of cards at the top, not a line inside a
  // details block, because on the day of travel they are the two facts the
  // guest actually opens this screen for.
  //
  // Hidden entirely until the listing loads. Nothing here invents 15:00.
  Widget _checkTimesRow() {
    final StayListing? l = _listing;
    if (l == null) return const SizedBox.shrink();

    Widget box(String label, String value) => Expanded(
          child: Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(12),
              border: Border.all(color: GoOutsColors.dividerGray),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                Text(label.toUpperCase(),
                    style: GoogleFonts.inter(
                        fontSize: 12,
                        height: 16 / 12,
                        fontWeight: FontWeight.w600,
                        letterSpacing: 0.3,
                        color: GoOutsColors.bodyText)),
                const SizedBox(height: 4),
                Text(value,
                    style: GoogleFonts.inter(
                        fontSize: 20,
                        height: 28 / 20,
                        fontWeight: FontWeight.w700,
                        color: GoOutsColors.deepNavy)),
              ],
            ),
          ),
        );

    return Row(children: <Widget>[
      box('Check in', l.checkInTime),
      const SizedBox(width: 12),
      box('Check out', l.checkOutTime),
    ]);
  }

  // ── Access instructions ───────────────────────────────────────────────────
  //
  // Replaces _arrivalNote, which was an info strip saying the host would be in
  // touch. Stitch gives this a card with a key icon, because on arrival it is
  // the most important thing on the screen.
  //
  // ⚠ PRIVATE, AND ONLY REACHABLE ON A BOOKING THE GUEST HOLDS. Door codes and
  // key safe locations are never on the public listing. See stay_listing.dart.
  //
  // The fallback stays for every host who left the field blank, which is most
  // of them and every listing created before 27 August 2026.
  Widget _accessCard() {
    final String written = _listing?.arrivalInstructions ?? '';
    final bool have = written.isNotEmpty;

    return _card(
      Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Row(
            children: <Widget>[
              const Icon(Icons.vpn_key_outlined,
                  size: 20, color: GoOutsColors.primaryBlue),
              const SizedBox(width: 10),
              Text('Access instructions',
                  style: GoogleFonts.inter(
                      fontSize: 15,
                      height: 20 / 15,
                      fontWeight: FontWeight.w700,
                      letterSpacing: 0.3,
                      color: GoOutsColors.primaryBlue)),
            ],
          ),
          const SizedBox(height: 10),
          Text(
            have
                ? written
                : 'Your host will send arrival times and how to get in. If you '
                    'have not heard from them, contact us and we will chase it.',
            style: GoogleFonts.inter(
                fontSize: 13.5, height: 20 / 13.5, color: GoOutsColors.bodyText),
          ),
        ],
      ),
    );
  }

  // ── Quick links ───────────────────────────────────────────────────────────
  //
  // Stitch lists Days out, Partners nearby and House rules.
  //
  // ⚠ PARTNERS NEARBY IS NOT A LINK HERE. _partnersCard already renders the
  // real count above, computed by the location engine. Replacing a live figure
  // with a chevron would be a downgrade.
  //
  // DAYS OUT IS LIVE as of 28 August 2026. It read "opens an empty screen
  // today" until screen 07 was wired to stay_attractions/{citySlug}, built from
  // OpenStreetMap. It shows the empty state only for a city we have not built
  // yet, and says exactly that rather than claiming there is nothing to do.
  Widget _houseRulesCard() {
    final StayListing? l = _listing;
    if (l == null) return const SizedBox.shrink();
    final StayHouseRules r = l.houseRules;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        const SizedBox(height: 20),
        Padding(
          padding: const EdgeInsets.only(left: 4, bottom: 10),
          child: Text('Quick links',
              style: GoogleFonts.inter(
                  fontSize: 15,
                  height: 20 / 15,
                  fontWeight: FontWeight.w700,
                  letterSpacing: 0.3,
                  color: GoOutsColors.deepNavy)),
        ),
        // ⚠ PASSES THE listingId. Yesterday this pushed the route bare and the
        // note here said it would open an empty screen. Screen 07 is wired now
        // and needs the property to know which city to read and which day out
        // is nearest, so a bare push would still show nothing.
        _quickLink(Icons.map_outlined, 'Days out',
            () => Navigator.of(context).pushNamed(
                  StayRoutes.daysOut,
                  arguments: <String, dynamic>{'listingId': l.id},
                )),
        const SizedBox(height: 8),
        // House rules are rendered rather than linked: they are four short
        // lines and there is no house rules screen to open.
        _rulesTile(r, l),
      ],
    );
  }

  Widget _quickLink(IconData icon, String label, VoidCallback onTap) => Material(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
        child: InkWell(
          onTap: onTap,
          borderRadius: BorderRadius.circular(12),
          child: Padding(
            padding: const EdgeInsets.all(14),
            child: Row(
              children: <Widget>[
                Container(
                  width: 40,
                  height: 40,
                  decoration: BoxDecoration(
                    color: GoOutsColors.paleBlueTint,
                    borderRadius: BorderRadius.circular(10),
                  ),
                  child: Icon(icon, size: 20, color: GoOutsColors.primaryBlue),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: Text(label,
                      style: GoogleFonts.inter(
                          fontSize: 14,
                          height: 20 / 14,
                          fontWeight: FontWeight.w600,
                          color: GoOutsColors.deepNavy)),
                ),
                const Icon(Icons.chevron_right,
                    color: GoOutsColors.outlineVariant),
              ],
            ),
          ),
        ),
      );

  Widget _rulesTile(StayHouseRules r, StayListing l) {
    Widget line(String text) => Padding(
          padding: const EdgeInsets.only(top: 6),
          child: Text('\u2022  $text',
              style: GoogleFonts.inter(
                  fontSize: 13.5,
                  height: 20 / 13.5,
                  color: GoOutsColors.bodyText)),
        );

    return _card(
      Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Row(
            children: <Widget>[
              const Icon(Icons.rule_rounded,
                  size: 20, color: GoOutsColors.primaryBlue),
              const SizedBox(width: 10),
              Text('House rules',
                  style: GoogleFonts.inter(
                      fontSize: 14,
                      height: 20 / 14,
                      fontWeight: FontWeight.w600,
                      color: GoOutsColors.deepNavy)),
            ],
          ),
          line('Check out by ${l.checkOutTime}'),
          // Only what the host actually said. isUnset hides the permissions
          // entirely rather than printing three "not allowed" lines nobody
          // chose. See StayHouseRules.
          if (!r.isUnset) ...<Widget>[
            line(r.smokingAllowed ? 'Smoking allowed' : 'No smoking'),
            line(r.petsAllowed ? 'Pets allowed' : 'No pets'),
            line(r.partiesAllowed
                ? 'Parties or events allowed'
                : 'No parties or events'),
            if (r.hasQuietHours)
              line('Quiet hours ${r.quietHoursFrom} to ${r.quietHoursTo}'),
            if (r.additional.isNotEmpty) line(r.additional),
          ],
        ],
      ),
    );
  }

  // ── The map ───────────────────────────────────────────────────────────────
  //
  // ⚠ AN EXACT PIN HERE, unlike screen 05 which shows a 300m circle and no
  // marker. That difference is deliberate: screen 05 is public and this screen
  // only opens on a booking the guest holds, so they are entitled to know
  // precisely where they are going.
  //
  // Dead map, same as screen 05: every gesture off, no controller, nothing to
  // dispose, lite mode on Android. The button underneath is what moves.
  Widget _mapCard() {
    final double? lat = _listing?.lat;
    final double? lng = _listing?.lng;
    if (lat == null || lng == null) return const SizedBox.shrink();

    final LatLng centre = LatLng(lat, lng);
    final StayAddress? a = _listing?.address;
    final String full = <String>[
      if (a != null && a.line1.isNotEmpty) a.line1,
      if (a != null && a.town.isNotEmpty) a.town,
      if (a != null && a.postcode.isNotEmpty) a.postcode,
    ].join(', ');

    return ClipRRect(
      borderRadius: BorderRadius.circular(12),
      child: SizedBox(
        height: 180,
        child: Stack(
          children: <Widget>[
            GoogleMap(
              initialCameraPosition: CameraPosition(target: centre, zoom: 15),
              liteModeEnabled:
                  Theme.of(context).platform == TargetPlatform.android,
              markers: <Marker>{
                Marker(markerId: const MarkerId('stay'), position: centre),
              },
              zoomControlsEnabled: false,
              zoomGesturesEnabled: false,
              scrollGesturesEnabled: false,
              rotateGesturesEnabled: false,
              tiltGesturesEnabled: false,
              myLocationButtonEnabled: false,
              myLocationEnabled: false,
              mapToolbarEnabled: false,
              compassEnabled: false,
            ),
            Positioned(
              left: 12,
              bottom: 12,
              child: Material(
                color: Colors.white,
                borderRadius: BorderRadius.circular(999),
                elevation: 2,
                child: InkWell(
                  onTap: () => _openMaps(full),
                  borderRadius: BorderRadius.circular(999),
                  child: Padding(
                    padding: const EdgeInsets.symmetric(
                        horizontal: 14, vertical: 10),
                    child: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: <Widget>[
                        const Icon(Icons.place_outlined,
                            size: 16, color: GoOutsColors.primaryBlue),
                        const SizedBox(width: 6),
                        Text('Open in Maps',
                            style: GoogleFonts.inter(
                                fontSize: 13.5,
                                fontWeight: FontWeight.w600,
                                color: GoOutsColors.deepNavy)),
                      ],
                    ),
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
