// Screen 17 of 29. Generated by Google Stitch, source folder 17-capture_checklist.
// Rebuilt 3 August 2026. The generated version hardcoded seven rooms and had no
// state at all, so nothing could be ticked and Finish did nothing.
//
// THIS IS THE SCREEN THAT ANSWERS "why can I not just take one photograph".
//
// Three rules it enforces, and they are the whole point:
//   1. The room list comes from the LISTING, not from this file. A two bedroom
//      flat asks for both bedrooms. The server generates captureRooms from
//      bedrooms and bathrooms, so it cannot be guessed or shortened here.
//   2. FINISH STAYS DISABLED while any room is outstanding. That single
//      constraint is what stops the one photograph problem, before any AI or
//      quality checking is involved.
//   3. A skip is allowed, recorded, and counts against whoever skipped it.
//      Nobody is ever trapped. But nobody skips silently either.
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import '../models/stay_booking.dart';
import '../models/stay_enums.dart';
import '../theme/stay_colors.dart';

/// One row's state. Derived from the booking, never stored on this screen.
enum RoomState { pending, done, skipped }

class CaptureChecklistScreen extends StatelessWidget {
  const CaptureChecklistScreen({
    super.key,
    this.rooms = const [],
    this.phase,
    this.kind = CaptureKind.guestCheckIn,
    this.onCapture,
    this.onSkip,
    this.onFinish,
  });

  /// From `StayListing.captureRooms`. Empty until the screen is wired, which
  /// is why there is a real empty state below rather than a hardcoded list.
  final List<String> rooms;

  /// From `StayBooking.capture.forKind(kind)`.
  final CapturePhase? phase;

  final CaptureKind kind;
  final void Function(String room)? onCapture;
  final void Function(String room)? onSkip;
  final VoidCallback? onFinish;

  RoomState _stateOf(String room) {
    final p = phase;
    if (p == null) return RoomState.pending;
    if (p.isDone(room)) return RoomState.done;
    if (p.isSkipped(room)) return RoomState.skipped;
    return RoomState.pending;
  }

  int get _addressed =>
      rooms.where((r) => _stateOf(r) != RoomState.pending).length;

  bool get _complete => rooms.isNotEmpty && _addressed == rooms.length;

  int get _remaining => rooms.length - _addressed;

  @override
  Widget build(BuildContext context) {
    final isCheckOut = kind == CaptureKind.guestCheckOut;

    return Scaffold(
      backgroundColor: GoOutsColors.pageBackground,
      appBar: AppBar(
        backgroundColor: GoOutsColors.cardSurface,
        elevation: 0.5,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: GoOutsColors.primaryBlue),
          onPressed: () => Navigator.of(context).maybePop(),
        ),
        title: Text(
          isCheckOut ? 'Check out photos' : 'Check in photos',
          style: GoogleFonts.inter(
            fontSize: 18,
            fontWeight: FontWeight.w700,
            color: GoOutsColors.primaryBlue,
          ),
        ),
        centerTitle: false,
      ),
      body: rooms.isEmpty ? _empty() : _list(context),
      bottomNavigationBar: rooms.isEmpty ? null : _footer(context, isCheckOut),
    );
  }

  // ── Empty state. Stitch produced none of these, and a blank screen is the
  //    most common way a wired screen fails in front of a real user. ────────
  Widget _empty() => Center(
        child: Padding(
          padding: const EdgeInsets.all(32),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const Icon(Icons.home_outlined,
                  size: 48, color: GoOutsColors.outlineVariant),
              const SizedBox(height: 16),
              Text(
                'We could not load the room list',
                textAlign: TextAlign.center,
                style: GoogleFonts.inter(
                  fontSize: 16,
                  fontWeight: FontWeight.w600,
                  color: GoOutsColors.deepNavy,
                ),
              ),
              const SizedBox(height: 8),
              Text(
                'Check your connection and try again. If it keeps happening, '
                'your host or our support team can help.',
                textAlign: TextAlign.center,
                style: GoogleFonts.inter(
                  fontSize: 13.5,
                  height: 1.5,
                  color: GoOutsColors.bodyText,
                ),
              ),
            ],
          ),
        ),
      );

  Widget _list(BuildContext context) => ListView(
        padding: const EdgeInsets.fromLTRB(16, 16, 16, 24),
        children: [
          _progress(),
          const SizedBox(height: 20),
          for (final room in rooms) _roomCard(context, room),
        ],
      );

  Widget _progress() {
    final fraction = rooms.isEmpty ? 0.0 : _addressed / rooms.length;
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: GoOutsColors.cardSurface,
        borderRadius: BorderRadius.circular(12),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Text(
                '$_addressed of ${rooms.length} captured',
                style: GoogleFonts.inter(
                  fontSize: 16,
                  fontWeight: FontWeight.w700,
                  color: GoOutsColors.deepNavy,
                ),
              ),
              const Spacer(),
              if (_complete)
                Row(children: [
                  const Icon(Icons.check_circle,
                      size: 18, color: GoOutsColors.success),
                  const SizedBox(width: 4),
                  Text('All done',
                      style: GoogleFonts.inter(
                        fontSize: 13,
                        fontWeight: FontWeight.w600,
                        color: GoOutsColors.success,
                      )),
                ]),
            ],
          ),
          const SizedBox(height: 12),
          ClipRRect(
            borderRadius: BorderRadius.circular(4),
            child: LinearProgressIndicator(
              value: fraction,
              minHeight: 8,
              backgroundColor: GoOutsColors.surfaceBlue,
              valueColor: AlwaysStoppedAnimation<Color>(
                _complete ? GoOutsColors.success : GoOutsColors.primaryBlue,
              ),
            ),
          ),
          const SizedBox(height: 12),
          Text(
            _complete
                ? 'Thank you. Your host can see these now.'
                : 'About ten seconds a room. It protects your deposit.',
            style: GoogleFonts.inter(
              fontSize: 13,
              color: GoOutsColors.bodyText,
            ),
          ),
        ],
      ),
    );
  }

  Widget _roomCard(BuildContext context, String room) {
    final state = _stateOf(room);
    final (IconData icon, Color tint, String label) = switch (state) {
      RoomState.done => (Icons.check_circle, GoOutsColors.success, 'Captured'),
      RoomState.skipped => (
          Icons.remove_circle_outline,
          GoOutsColors.outlineVariant,
          'Skipped, and recorded'
        ),
      RoomState.pending => (
          Icons.photo_camera_outlined,
          GoOutsColors.primaryBlue,
          'Not yet'
        ),
    };

    return Container(
      margin: const EdgeInsets.only(bottom: 8),
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: GoOutsColors.cardSurface,
        borderRadius: BorderRadius.circular(12),
      ),
      child: Row(
        children: [
          Container(
            width: 44,
            height: 44,
            decoration: BoxDecoration(
              color: state == RoomState.pending
                  ? GoOutsColors.paleBlueTint
                  : GoOutsColors.dividerGray,
              borderRadius: BorderRadius.circular(10),
            ),
            child: Icon(icon, color: tint, size: 22),
          ),
          const SizedBox(width: 14),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  room,
                  style: GoogleFonts.inter(
                    fontSize: 14,
                    fontWeight: FontWeight.w600,
                    color: GoOutsColors.deepNavy,
                  ),
                ),
                const SizedBox(height: 2),
                Text(
                  label,
                  style: GoogleFonts.inter(
                    fontSize: 12,
                    color: state == RoomState.done
                        ? GoOutsColors.success
                        : GoOutsColors.bodyText,
                  ),
                ),
              ],
            ),
          ),
          if (state == RoomState.pending) ...[
            TextButton(
              onPressed: onSkip == null ? null : () => onSkip!(room),
              child: Text(
                'Skip',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  fontWeight: FontWeight.w600,
                  color: GoOutsColors.bodyText,
                ),
              ),
            ),
            const SizedBox(width: 4),
            ElevatedButton(
              onPressed: onCapture == null ? null : () => onCapture!(room),
              style: ElevatedButton.styleFrom(
                backgroundColor: GoOutsColors.primaryBlue,
                foregroundColor: GoOutsColors.cardSurface,
                elevation: 0,
                padding: const EdgeInsets.symmetric(horizontal: 16),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(10),
                ),
              ),
              child: Text('Capture',
                  style: GoogleFonts.inter(
                      fontSize: 13, fontWeight: FontWeight.w600)),
            ),
          ] else
            TextButton(
              onPressed: onCapture == null ? null : () => onCapture!(room),
              child: Text(
                'Retake',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  fontWeight: FontWeight.w600,
                  color: GoOutsColors.primaryBlue,
                ),
              ),
            ),
        ],
      ),
    );
  }

  Widget _footer(BuildContext context, bool isCheckOut) {
    // THE RULE. Finish is dead until every room has been addressed.
    //
    // Check out is prompted rather than required, so it offers a way past for
    // a guest running for a train. Check in does not, because that is the set
    // which protects the guest from being blamed for what was already there.
    final canFinish = _complete;

    return Container(
      padding: const EdgeInsets.fromLTRB(16, 12, 16, 28),
      decoration: const BoxDecoration(
        color: GoOutsColors.cardSurface,
        border: Border(top: BorderSide(color: GoOutsColors.dividerGray)),
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          if (!canFinish)
            Padding(
              padding: const EdgeInsets.only(bottom: 10),
              child: Text(
                _remaining == 1
                    ? 'One room left to finish.'
                    : 'Photograph the remaining $_remaining rooms to finish.',
                textAlign: TextAlign.center,
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: GoOutsColors.bodyText,
                ),
              ),
            ),
          ElevatedButton(
            onPressed: canFinish ? onFinish : null,
            style: ElevatedButton.styleFrom(
              backgroundColor: GoOutsColors.primaryBlue,
              foregroundColor: GoOutsColors.cardSurface,
              disabledBackgroundColor: GoOutsColors.outlineVariant,
              disabledForegroundColor: GoOutsColors.cardSurface,
              minimumSize: const Size(double.infinity, 52),
              elevation: 0,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(12),
              ),
            ),
            child: Text(
              'Finish',
              style:
                  GoogleFonts.inter(fontSize: 16, fontWeight: FontWeight.w700),
            ),
          ),
          if (isCheckOut && !canFinish)
            TextButton(
              onPressed: onFinish,
              child: Text(
                'Leave without finishing',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  fontWeight: FontWeight.w600,
                  color: GoOutsColors.bodyText,
                ),
              ),
            ),
        ],
      ),
    );
  }
}
