// Screen 21 of 29. Generated by Google Stitch, source folder 21-checkout_capture.
// Rewritten 3 August 2026 as a THIN WRAPPER, not a second camera.
//
// WHY
// The generated version was a near copy of screen 18 with a ghost image
// placeholder bolted on. Two camera implementations means two CameraControllers
// to initialise, two to release on backgrounding, and two places to get the
// memory handling wrong. This app has already been killed once by iOS Jetsam.
//
// So there is ONE camera screen, CameraCaptureScreen, and it takes an optional
// referencePhotoUrl. Check out passes the guest's own arrival photograph of
// that room; check in passes nothing. Same code path, same disposal, same
// lifecycle handling.
//
// If this file ever grows a CameraController of its own, something has gone
// wrong. Delete that and call screen 18 instead.
import 'dart:io';

import 'package:flutter/material.dart';
import '../models/stay_enums.dart';
import '18_camera_capture_screen.dart';

class CheckoutCaptureScreen extends StatelessWidget {
  const CheckoutCaptureScreen({
    super.key,
    this.room = '',
    this.arrivalPhotoUrl,
    this.onCaptured,
  });

  final String room;

  /// The guest's OWN photograph of this room taken at check in. Loaded by the
  /// caller from StayEvidenceService.arrivalPhotoFor.
  ///
  /// This is what makes the two sets comparable. Matched before and after
  /// photographs settle a claim. Unmatched ones just give both sides more to
  /// argue about.
  final String? arrivalPhotoUrl;

  final Future<void> Function(File photo)? onCaptured;

  @override
  Widget build(BuildContext context) {
    return CameraCaptureScreen(
      room: room,
      kind: CaptureKind.guestCheckOut,
      referencePhotoUrl: arrivalPhotoUrl,
      guidance: arrivalPhotoUrl == null
          ? (room.isEmpty
              ? 'Capture the whole room in one photograph.'
              : '$room. Capture the whole room.')
          : 'Line up the same shot as your arrival photo. '
              'Use the slider to fade it in and out.',
      onCaptured: onCaptured,
    );
  }
}
