// Screen 22 of 29. Generated by Google Stitch, source folder 22-evidence_pack.
//
// WIRED 16 August 2026, task #116, Phase D.
//
// ── THE CLAIM THIS SCREEN USED TO MAKE ───────────────────────────────────
//
// Under a padlock icon, headed "Immutable Security":
//
//     "Nobody can edit or delete these, including us. Photos are
//      cryptographically signed and timestamped."
//
// and at the foot of the page:
//
//     "Hash: 8a4f...2d1e | SHA-256 Verified"
//
// None of it was true. A search of the entire app for sha256, crypto, digest
// or signature returns exactly two results, and both are those lines. There is
// no hashing, no signing, and no immutability — the photographs are JPEGs in
// Cloud Storage with a Firestore document beside them, and an administrator
// can delete either.
//
// This is worse than the fake Visa on screen 12, and for a specific reason:
// the entire purpose of this screen is to be relied upon in a dispute. A guest
// reading "cryptographically signed, SHA-256 verified" would reasonably believe
// they held court-grade evidence, and would act on that belief precisely when
// they were most exposed. A fabricated assurance about evidence is the one that
// does damage at the worst possible moment.
//
// ── WHAT IS ACTUALLY TRUE, AND IS WORTH SAYING ───────────────────────────
//
// Two real protections exist, and both are meaningful:
//
//   1. takenAt is FieldValue.serverTimestamp(). The time on every photograph
//      comes from Google's servers, not the phone. Changing a device clock
//      does not change it.
//   2. Camera only. Screen 18 takes photographs through the camera and offers
//      no gallery picker, so an image cannot be substituted from the photo
//      library after the fact.
//
// Those are the claims now on the screen. They are smaller than the ones they
// replaced and they have the advantage of being so.
//
// If real hashing is wanted later — and for a deposit dispute it probably is —
// it belongs server side, in a trigger that reads the uploaded object and
// records its digest. Recording a hash computed on the phone would prove
// nothing, because the phone is the thing being trusted.
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import '../models/stay_enums.dart';
import '../models/stay_evidence.dart';
import '../services/stay_evidence_service.dart';
import '../theme/stay_colors.dart';

class EvidencePackScreen extends StatelessWidget {
  const EvidencePackScreen({super.key, required this.bookingId});

  final String bookingId;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: GoOutsColors.background,
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0.5,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: GoOutsColors.primaryBlue),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: Text(
          'Evidence pack',
          style: GoogleFonts.inter(
            fontSize: 20,
            fontWeight: FontWeight.bold,
            color: GoOutsColors.deepNavy,
          ),
        ),
      ),
      body: StreamBuilder<List<StayEvidence>>(
        stream: StayEvidenceService.instance.watch(bookingId),
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Center(child: CircularProgressIndicator());
          }
          if (snapshot.hasError) {
            return _message('These photographs could not be loaded. '
                'They are safe — this is a problem showing them, not storing '
                'them.');
          }

          final List<StayEvidence> all =
              snapshot.data ?? const <StayEvidence>[];
          if (all.isEmpty) {
            return _message('No photographs have been taken for this stay '
                'yet. They are what protects you if a damage claim is made.');
          }

          return ListView(
            padding: const EdgeInsets.all(16),
            children: [
              _buildSecurityBanner(),
              const SizedBox(height: 8),
              for (final kind in CaptureKind.values)
                ..._sectionFor(kind, all),
              const SizedBox(height: 16),
              _buildFooter(all),
              const SizedBox(height: 24),
            ],
          );
        },
      ),
    );
  }

  Widget _message(String text) => Center(
        child: Padding(
          padding: const EdgeInsets.all(32),
          child: Text(
            text,
            textAlign: TextAlign.center,
            style: GoogleFonts.inter(
                fontSize: 15, color: GoOutsColors.bodyText, height: 1.4),
          ),
        ),
      );

  // ── Sections ─────────────────────────────────────────────────────────────
  //
  // Grouped by who took them and when — the host before arrival, the guest on
  // arrival, the guest on departure. That grouping is the point of the pack:
  // a claim is settled by comparing one set against another, so they have to
  // be readable side by side.

  List<Widget> _sectionFor(CaptureKind kind, List<StayEvidence> all) {
    final List<StayEvidence> mine =
        all.where((e) => e.kind == kind).toList(growable: false);
    if (mine.isEmpty) return const <Widget>[];

    final List<StayEvidence> photos =
        mine.where((e) => !e.skipped).toList(growable: false);
    final List<StayEvidence> skipped =
        mine.where((e) => e.skipped).toList(growable: false);

    return <Widget>[
      Padding(
        padding: const EdgeInsets.only(top: 16, bottom: 8),
        child: Row(
          children: [
            Expanded(
              child: Text(
                kind.label,
                style: GoogleFonts.inter(
                  fontSize: 16,
                  fontWeight: FontWeight.bold,
                  color: GoOutsColors.deepNavy,
                ),
              ),
            ),
            Text(
              '${photos.length} '
              '${photos.length == 1 ? 'photo' : 'photos'}',
              style: GoogleFonts.inter(
                  fontSize: 13, color: GoOutsColors.bodyText),
            ),
          ],
        ),
      ),
      for (final e in photos) _photoCard(e),
      // Skips are shown, never hidden. A room nobody photographed is a fact
      // about this stay, and burying it would leave the guest with a rosier
      // picture of their own evidence than they actually have.
      for (final e in skipped) _skipCard(e),
    ];
  }

  Widget _photoCard(StayEvidence e) {
    return Container(
      margin: const EdgeInsets.only(bottom: 12),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
      ),
      clipBehavior: Clip.antiAlias,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          AspectRatio(
            aspectRatio: 4 / 3,
            child: Image.network(
              e.url,
              fit: BoxFit.cover,
              errorBuilder: (_, __, ___) => Container(
                color: GoOutsColors.paleBlueTint,
                child: const Center(
                  child: Icon(Icons.image_not_supported_outlined,
                      color: GoOutsColors.primaryBlue),
                ),
              ),
              loadingBuilder: (context, child, progress) => progress == null
                  ? child
                  : Container(
                      color: GoOutsColors.paleBlueTint,
                      child:
                          const Center(child: CircularProgressIndicator()),
                    ),
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(12),
            child: Row(
              children: [
                Expanded(
                  child: Text(
                    e.room.isEmpty ? 'Room' : e.room,
                    style: GoogleFonts.inter(
                      fontSize: 15,
                      fontWeight: FontWeight.w600,
                      color: GoOutsColors.deepNavy,
                    ),
                  ),
                ),
                if (e.takenAt != null)
                  Text(
                    _stamp(e.takenAt!),
                    style: GoogleFonts.inter(
                        fontSize: 12, color: GoOutsColors.bodyText),
                  ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _skipCard(StayEvidence e) {
    return Container(
      margin: const EdgeInsets.only(bottom: 12),
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: GoOutsColors.dividerGray),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Icon(Icons.remove_circle_outline,
              size: 20, color: GoOutsColors.bodyText),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  '${e.room.isEmpty ? 'Room' : e.room} — not photographed',
                  style: GoogleFonts.inter(
                    fontSize: 15,
                    fontWeight: FontWeight.w600,
                    color: GoOutsColors.deepNavy,
                  ),
                ),
                if ((e.skipReason ?? '').isNotEmpty)
                  Text(
                    e.skipReason!,
                    style: GoogleFonts.inter(
                        fontSize: 13, color: GoOutsColors.bodyText),
                  ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  static const List<String> _months = <String>[
    'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
  ];

  static String _stamp(DateTime d) =>
      '${d.day} ${_months[d.month - 1]} '
      '${d.hour.toString().padLeft(2, '0')}:'
      '${d.minute.toString().padLeft(2, '0')}';

  // ── The banner that replaced the false one ───────────────────────────────

  Widget _buildSecurityBanner() {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: GoOutsColors.infoBlueBg,
        borderRadius: BorderRadius.circular(12),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Icon(Icons.schedule, color: GoOutsColors.primaryBlue, size: 24),
          const SizedBox(width: 16),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'Timed by our servers, not your phone',
                  style: GoogleFonts.inter(
                    fontSize: 16,
                    fontWeight: FontWeight.bold,
                    color: GoOutsColors.primaryBlue,
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  'The time on each photograph is recorded by GoOuts when you '
                  'take it, so changing a device clock cannot change it. '
                  'Photographs are taken with the camera in the app and '
                  'cannot be chosen from your photo library.',
                  style: GoogleFonts.inter(
                    fontSize: 14,
                    color: GoOutsColors.bodyText,
                    height: 1.4,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  // ── Footer ───────────────────────────────────────────────────────────────
  //
  // The "Download PDF Report" button had an empty handler and the hash line was
  // invented. Both are gone. A count of what is held is a true thing to say and
  // is what a guest actually wants to know at the bottom of this list.

  Widget _buildFooter(List<StayEvidence> all) {
    final int photos = all.where((e) => !e.skipped).length;
    final int skips = all.where((e) => e.skipped).length;

    // Built as plain statements rather than nested inside one interpolation.
    // The nested-ternary-inside-${} version compiled but was unreadable, and
    // unreadable is how the wrong branch survives review.
    final String photoPart =
        '$photos ${photos == 1 ? 'photograph' : 'photographs'} held for '
        'this stay';
    final String skipPart = skips == 0
        ? ''
        : ', $skips ${skips == 1 ? 'room' : 'rooms'} not photographed';

    return Center(
      child: Column(
        children: [
          Text(
            '$photoPart$skipPart.',
            textAlign: TextAlign.center,
            style: GoogleFonts.inter(
                fontSize: 13, color: GoOutsColors.bodyText),
          ),
          const SizedBox(height: 4),
          Text(
            'Both you and your host can see these.',
            style: GoogleFonts.inter(
              fontSize: 12,
              color: GoOutsColors.bodyText.withValues(alpha: 0.7),
            ),
          ),
        ],
      ),
    );
  }
}
