// Screen 25 of 29. Generated by Google Stitch, source folder 25-review_stay.
//
// WIRED 29 August 2026. Until today this was the emptiest screen in the app:
// a StatelessWidget taking no bookingId, with `onPressed: () {}` on both the
// account icon and Submit, and NO SCREEN ANYWHERE PUSHED StayRoutes.review.
// It was a live route nothing could reach, in front of a form that could not
// have known which stay it was about if it had been reached.
//
// ── ⚠ WHAT THAT COST, WHICH WAS NOT OBVIOUS ─────────────────────────────────
//
// Four things were already reading review data and shipping:
//
//     05_listing_detail     renders stay_listings/{id}/reviews
//     02_search_results     a rating chip on every card
//     StaySort.rating       "Rating" offered as a sort order
//     stay_listing_service  reviews(), written and called
//
// and nothing on the platform could create a review. Real listing creation
// writes ratingAvg 0 in two places and only stay_demo_seed.js ever wrote a
// real number. So every genuinely listed property was going to sit at zero
// stars for ever while the demo ones looked perfect. That is why it took four
// weeks to notice.
//
// ── ⚠ DOUBLE BLIND, AND STITCH SAID SO FIRST ────────────────────────────────
//
// The line at the bottom of the Stitch screen reads "Your review and your
// host's are published together on your profile and the listing page once both
// are submitted", and firestore.rules has carried "submitStayReview only.
// Double blind release cannot be enforced on a client" since the rules were
// written. Both were describing a system that did not exist. This screen and
// functions/stay_reviews.js are that system.
//
// The consequence for this file: SUBMITTING DOES NOT PUBLISH. The guest is
// told what actually happened — waiting on the host, or both now visible —
// rather than a flat "thank you" that implies their words are live.
import 'package:cloud_functions/cloud_functions.dart';
import 'package:flutter/material.dart';

import '../models/stay_booking.dart';
import '../services/stay_booking_service.dart';
import '../services/stay_review_service.dart';
import '../theme/stay_colors.dart';
import '../theme/stay_type.dart';
import '../widgets/stay_bottom_nav.dart';

/// The six sub scores Stitch asks for. Wire keys on the left, because the
/// server validates against exactly these and drops anything else.
const Map<String, String> kReviewCategories = <String, String>{
  'cleanliness': 'Cleanliness',
  'accuracy': 'Accuracy',
  'checkIn': 'Check in',
  'communication': 'Communication',
  'location': 'Location',
  'value': 'Value',
};

class ReviewStayScreen extends StatefulWidget {
  const ReviewStayScreen({super.key, required this.bookingId});

  /// ⚠ REQUIRED, and it is the thing this screen never had. Without it there
  /// is no stay to attach a review to and no way for the server to work out
  /// whether the caller is the guest or the host.
  final String bookingId;

  @override
  State<ReviewStayScreen> createState() => _ReviewStayScreenState();
}

class _ReviewStayScreenState extends State<ReviewStayScreen> {
  final TextEditingController _comment = TextEditingController();

  StayBooking? _booking;
  bool _loading = true;
  bool _sending = false;
  String? _error;

  int _overall = 0;
  final Map<String, int> _categories = <String, int>{};

  @override
  void initState() {
    super.initState();
    _load();
  }

  @override
  void dispose() {
    _comment.dispose();
    super.dispose();
  }

  Future<void> _load() async {
    try {
      final StayBooking? b =
          await StayBookingService.instance.byId(widget.bookingId);
      if (!mounted) return;
      setState(() {
        _booking = b;
        _loading = false;
      });
    } catch (e) {
      if (!mounted) return;
      setState(() {
        _loading = false;
        _error = e.toString();
      });
    }
  }

  Future<void> _submit() async {
    if (_overall == 0 || _sending) return;
    setState(() {
      _sending = true;
      _error = null;
    });
    try {
      final StayReviewOutcome out = await StayReviewService.instance.submit(
        bookingId: widget.bookingId,
        rating: _overall,
        comment: _comment.text,
        categories: _categories,
      );
      if (!mounted) return;
      await _showOutcome(out);
      if (!mounted) return;
      Navigator.of(context).pop(true);
    } on FirebaseFunctionsException catch (e) {
      if (!mounted) return;
      setState(() {
        _sending = false;
        // ⚠ THE SERVER'S OWN WORDING. It is the only side that knows whether
        // this was a closed window, an unfinished stay or a second attempt,
        // and a screen that guesses would tell somebody the wrong one.
        _error = e.message ?? 'That could not be sent.';
      });
    } catch (e) {
      if (!mounted) return;
      setState(() {
        _sending = false;
        _error = e.toString();
      });
    }
  }

  /// ⚠ SAYS WHICH OF THE TWO HAPPENED. "Thank you" would imply the review is
  /// live, and in the ordinary case it is not — it sits unpublished until the
  /// host writes theirs or the fortnight runs out. Telling a guest their words
  /// are up when they are not is the kind of small lie that gets noticed when
  /// they go looking for them.
  Future<void> _showOutcome(StayReviewOutcome out) => showDialog<void>(
        context: context,
        builder: (BuildContext ctx) => AlertDialog(
          backgroundColor: GoOutsColors.cardSurface,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(16),
          ),
          title: Text(
            out.published ? 'Both reviews are up' : 'Review saved',
            style: StayType.sectionHeader.on(GoOutsColors.deepNavy),
          ),
          content: Text(
            out.published
                ? 'Your host had already written theirs, so both are now '
                    'visible on the listing.'
                : 'Your host has not reviewed you yet. Both reviews go up '
                    'together once they do, or after the review window '
                    'closes.',
            style: StayType.body.on(GoOutsColors.bodyText),
          ),
          actions: <Widget>[
            TextButton(
              onPressed: () => Navigator.of(ctx).pop(),
              child: Text('Done',
                  style: StayType.cardTitle.on(GoOutsColors.primaryBlue)),
            ),
          ],
        ),
      );

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: GoOutsColors.pageBackground,
      appBar: AppBar(
        backgroundColor: GoOutsColors.cardSurface,
        surfaceTintColor: Colors.transparent,
        elevation: 0,
        toolbarHeight: 52,
        shape: const Border(
          bottom: BorderSide(color: GoOutsColors.outlineVariant, width: 0.5),
        ),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: GoOutsColors.primaryBlue),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: Text('Review your stay',
            style: StayType.screenTitle.on(GoOutsColors.primaryBlue)),
      ),
      // ⚠ THE ACCOUNT ICON IS GONE. Stitch draws one here and it had
      // `onPressed: () {}`. A profile button on a form somebody is halfway
      // through filling in is a way to lose the form, and there is a Profile
      // tab two centimetres below it doing the same job properly.
      bottomNavigationBar: const StayBottomNav(current: StayTab.trips),
      body: _loading
          ? const Center(child: CircularProgressIndicator())
          : _body(),
    );
  }

  Widget _body() {
    final StayBooking? b = _booking;

    // ⚠ REFUSES CLEARLY RATHER THAN COLLECTING A REVIEW IT CANNOT SEND. The
    // server would reject these anyway, so letting somebody rate six
    // categories and write four paragraphs before telling them is the worse
    // order to do it in.
    if (b == null) {
      return _notice(Icons.error_outline, 'That stay could not be loaded',
          'Go back and open it from your trips.');
    }
    if (b.reviewSubmittedByGuest) {
      return _notice(
          Icons.done_all,
          'You have already reviewed this stay',
          b.reviewsPublishedAt == null
              ? 'It goes up when your host writes theirs, or when the review '
                  'window closes.'
              : 'It is on the listing now.');
    }
    if (!b.isPast) {
      return _notice(Icons.schedule, 'This stay has not finished yet',
          'You can review it once you have checked out.');
    }
    if (!b.reviewWindowOpen) {
      return _notice(
          Icons.lock_clock,
          'The review window has closed',
          'Reviews close ${StayBooking.reviewWindowDays} days after check '
              'out.');
    }

    return ListView(
      padding: const EdgeInsets.fromLTRB(
          StaySpacing.page, StaySpacing.section, StaySpacing.page, 32),
      children: <Widget>[
        _overallCard(),
        const SizedBox(height: StaySpacing.inline),
        _detailsCard(),
        const SizedBox(height: StaySpacing.inline),
        _commentCard(),
        const SizedBox(height: StaySpacing.inline),
        _blindNotice(),
        const SizedBox(height: StaySpacing.section),
        if (_error != null) ...<Widget>[
          Text(_error!,
              textAlign: TextAlign.center,
              style: StayType.body.on(GoOutsColors.error)),
          const SizedBox(height: StaySpacing.inline),
        ],
        _submitButton(),
      ],
    );
  }

  Widget _notice(IconData icon, String title, String detail) => Center(
        child: Padding(
          padding: const EdgeInsets.all(32),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              Icon(icon, size: 48, color: GoOutsColors.outlineVariant),
              const SizedBox(height: StaySpacing.inline),
              Text(title,
                  textAlign: TextAlign.center,
                  style: StayType.cardTitle.on(GoOutsColors.deepNavy)),
              const SizedBox(height: 6),
              Text(detail,
                  textAlign: TextAlign.center,
                  style: StayType.body.on(GoOutsColors.bodyText)),
            ],
          ),
        ),
      );

  Widget _card({required List<Widget> children}) => Container(
        width: double.infinity,
        padding: const EdgeInsets.all(StaySpacing.page),
        decoration: BoxDecoration(
          color: GoOutsColors.cardSurface,
          borderRadius: BorderRadius.circular(12),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: children,
        ),
      );

  // ── Overall ────────────────────────────────────────────────────────────────

  Widget _overallCard() => _card(
        children: <Widget>[
          Center(
            child: Column(
              children: <Widget>[
                Text('Overall experience',
                    style: StayType.sectionHeader.on(GoOutsColors.deepNavy)),
                const SizedBox(height: 4),
                Text('How would you rate your total stay?',
                    textAlign: TextAlign.center,
                    style: StayType.body.on(GoOutsColors.bodyText)),
                const SizedBox(height: StaySpacing.page),
                _stars(
                  value: _overall,
                  size: 40,
                  onPick: (int v) => setState(() => _overall = v),
                ),
              ],
            ),
          ),
        ],
      );

  // ── Categories ─────────────────────────────────────────────────────────────

  Widget _detailsCard() => _card(
        children: <Widget>[
          Text('Details', style: StayType.sectionHeader.on(GoOutsColors.deepNavy)),
          const SizedBox(height: 4),
          // ⚠ SAYS THEY ARE OPTIONAL, because they are. The server drops any
          // score that is absent rather than defaulting it, and a guest who
          // rates four of the six is not penalised on the other two.
          Text('Optional. Skip anything that does not apply.',
              style: StayType.caption.on(GoOutsColors.bodyText)),
          const SizedBox(height: StaySpacing.inline),
          for (final MapEntry<String, String> c in kReviewCategories.entries)
            Padding(
              padding: const EdgeInsets.symmetric(vertical: 6),
              child: Row(
                children: <Widget>[
                  Expanded(
                    child: Text(c.value,
                        style: StayType.body.on(GoOutsColors.deepNavy)),
                  ),
                  _stars(
                    value: _categories[c.key] ?? 0,
                    size: 22,
                    onPick: (int v) => setState(() {
                      // Tapping the same star again clears it, so a score set
                      // by accident can be taken back rather than being stuck
                      // at whatever was touched first.
                      if (_categories[c.key] == v) {
                        _categories.remove(c.key);
                      } else {
                        _categories[c.key] = v;
                      }
                    }),
                  ),
                ],
              ),
            ),
        ],
      );

  Widget _stars({
    required int value,
    required double size,
    required ValueChanged<int> onPick,
  }) =>
      Row(
        mainAxisSize: MainAxisSize.min,
        children: <Widget>[
          for (int i = 1; i <= 5; i++)
            InkWell(
              customBorder: const CircleBorder(),
              onTap: () => onPick(i),
              child: Padding(
                padding: const EdgeInsets.all(2),
                child: Icon(
                  i <= value ? Icons.star_rounded : Icons.star_border_rounded,
                  size: size,
                  color: i <= value
                      ? GoOutsColors.warning
                      : GoOutsColors.starGray,
                ),
              ),
            ),
        ],
      );

  // ── Words ──────────────────────────────────────────────────────────────────

  Widget _commentCard() => _card(
        children: <Widget>[
          Text('Describe your stay',
              style: StayType.sectionHeader.on(GoOutsColors.deepNavy)),
          const SizedBox(height: 4),
          Text('Share what you loved or what could be improved.',
              style: StayType.body.on(GoOutsColors.bodyText)),
          const SizedBox(height: StaySpacing.inline),
          TextField(
            controller: _comment,
            maxLines: 5,
            maxLength: 1500,
            textCapitalization: TextCapitalization.sentences,
            style: StayType.body.on(GoOutsColors.deepNavy),
            decoration: InputDecoration(
              hintText: 'Write your review here',
              hintStyle: StayType.body.on(GoOutsColors.outlineVariant),
              counterStyle: StayType.caption.on(GoOutsColors.bodyText),
              filled: true,
              fillColor: GoOutsColors.pageBackground,
              contentPadding: const EdgeInsets.all(StaySpacing.inline),
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide: const BorderSide(
                    color: GoOutsColors.outlineVariant),
              ),
              enabledBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide: const BorderSide(
                    color: GoOutsColors.outlineVariant),
              ),
              focusedBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide:
                    const BorderSide(color: GoOutsColors.primaryBlue),
              ),
            ),
          ),
        ],
      );

  Widget _blindNotice() => Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          const Icon(Icons.info_outline,
              size: 18, color: GoOutsColors.primaryBlue),
          const SizedBox(width: StaySpacing.card),
          Expanded(
            child: Text(
              'Your review and your host\'s go up together, once you have '
              'both written one or after '
              '${StayBooking.reviewWindowDays} days. Neither of you sees the '
              'other until then.',
              style: StayType.body.on(GoOutsColors.bodyText),
            ),
          ),
        ],
      );

  Widget _submitButton() => ElevatedButton(
        // ⚠ DISABLED UNTIL A STAR IS CHOSEN. The server rejects a rating
        // outside 1 to 5, so an enabled button with nothing selected would be
        // a round trip that can only fail.
        onPressed: (_overall == 0 || _sending) ? null : _submit,
        style: ElevatedButton.styleFrom(
          backgroundColor: GoOutsColors.primaryBlue,
          foregroundColor: GoOutsColors.cardSurface,
          disabledBackgroundColor: GoOutsColors.outlineVariant,
          disabledForegroundColor: GoOutsColors.cardSurface,
          minimumSize: const Size(double.infinity, StaySpacing.buttonHeight),
          elevation: 0,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12),
          ),
        ),
        child: _sending
            ? const SizedBox(
                width: 20,
                height: 20,
                child: CircularProgressIndicator(
                    strokeWidth: 2, color: GoOutsColors.cardSurface),
              )
            : Text(
                _overall == 0 ? 'Choose a rating' : 'Submit review',
                style: StayType.buttonText,
              ),
      );
}
