// Generated by Google Stitch, 3 August 2026. Source folder: 25-review_stay
// Cleaned and consolidated by the pass described in
// goouts/design/SHORT_STAY_WIRING_PLAN.md part 1.
// NOT WIRED. Every handler in this file is still empty. See part 2.
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import '../theme/stay_colors.dart';

class ReviewStayScreen extends StatelessWidget {
  const ReviewStayScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: GoOutsColors.background,
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0.5,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: GoOutsColors.primaryBlue),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: Text(
          'Review your stay',
          style: GoogleFonts.inter(
            fontSize: 20,
            fontWeight: FontWeight.bold,
            color: GoOutsColors.primaryBlue,
          ),
        ),
        actions: [
          IconButton(
            icon: const Icon(Icons.account_circle_outlined, color: GoOutsColors.primaryBlue),
            onPressed: () {},
          ),
        ],
      ),
      body: SingleChildScrollView(
        child: Column(
          children: [
            const SizedBox(height: 32),
            _buildOverallExperience(),
            const SizedBox(height: 40),
            _buildDetailsSection(),
            const SizedBox(height: 40),
            _buildReviewTextSection(),
            const SizedBox(height: 40),
            _buildSubmitButton(),
            const SizedBox(height: 40),
          ],
        ),
      ),
      bottomNavigationBar: _buildBottomNavBar(),
    );
  }

  Widget _buildOverallExperience() {
    return Column(
      children: [
        Text(
          'Overall experience',
          style: GoogleFonts.inter(
            fontSize: 18,
            fontWeight: FontWeight.bold,
            color: GoOutsColors.deepNavy,
          ),
        ),
        const SizedBox(height: 8),
        Text(
          'How would you rate your total stay?',
          style: GoogleFonts.inter(
            fontSize: 14,
            color: GoOutsColors.bodyText,
          ),
        ),
        const SizedBox(height: 20),
        Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: List.generate(5, (index) => const Padding(
            padding: EdgeInsets.symmetric(horizontal: 4),
            child: Icon(Icons.star_outline, size: 40, color: GoOutsColors.starGray),
          )),
        ),
      ],
    );
  }

  Widget _buildDetailsSection() {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'Details',
            style: GoogleFonts.inter(
              fontSize: 18,
              fontWeight: FontWeight.bold,
              color: GoOutsColors.deepNavy,
            ),
          ),
          const SizedBox(height: 24),
          _buildRatingRow('Cleanliness'),
          _buildRatingRow('Accuracy'),
          _buildRatingRow('Check-in'),
          _buildRatingRow('Communication'),
          _buildRatingRow('Location'),
          _buildRatingRow('Value'),
        ],
      ),
    );
  }

  Widget _buildRatingRow(String label) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 20),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(
            label,
            style: GoogleFonts.inter(
              fontSize: 15,
              fontWeight: FontWeight.w500,
              color: GoOutsColors.bodyText,
            ),
          ),
          Row(
            children: List.generate(5, (index) => const Padding(
              padding: EdgeInsets.only(left: 4),
              child: Icon(Icons.star_outline, size: 24, color: GoOutsColors.starGray),
            )),
          ),
        ],
      ),
    );
  }

  Widget _buildReviewTextSection() {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'Describe your stay',
            style: GoogleFonts.inter(
              fontSize: 18,
              fontWeight: FontWeight.bold,
              color: GoOutsColors.deepNavy,
            ),
          ),
          const SizedBox(height: 12),
          Text(
            'Share what you loved or what could be improved.',
            style: GoogleFonts.inter(
              fontSize: 14,
              color: GoOutsColors.bodyText,
              height: 1.4,
            ),
          ),
          const SizedBox(height: 16),
          Container(
            height: 180,
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(12),
              border: Border.all(color: GoOutsColors.outlineVariant.withValues(alpha: 0.5)),
            ),
            child: TextField(
              maxLines: null,
              decoration: InputDecoration(
                hintText: 'Write your review here...',
                hintStyle: GoogleFonts.inter(
                  color: GoOutsColors.bodyText.withValues(alpha: 0.5),
                  fontSize: 15,
                ),
                border: InputBorder.none,
              ),
            ),
          ),
          const SizedBox(height: 24),
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Icon(Icons.info_outline, color: GoOutsColors.bodyText, size: 20),
              const SizedBox(width: 12),
              Expanded(
                child: Text(
                  'Your review and your host\'s are published together on your profile and the listing page once both are submitted.',
                  style: GoogleFonts.inter(
                    fontSize: 13,
                    color: GoOutsColors.bodyText.withValues(alpha: 0.8),
                    height: 1.4,
                  ),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildSubmitButton() {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 24),
      child: ElevatedButton(
        onPressed: () {},
        style: ElevatedButton.styleFrom(
          backgroundColor: GoOutsColors.primaryBlue,
          minimumSize: const Size(double.infinity, 56),
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
          elevation: 0,
        ),
        child: Text(
          'Submit Review',
          style: GoogleFonts.inter(
            fontSize: 18,
            fontWeight: FontWeight.bold,
            color: Colors.white,
          ),
        ),
      ),
    );
  }

  Widget _buildBottomNavBar() {
    return Container(
      height: 80,
      decoration: const BoxDecoration(
        color: Colors.white,
        border: Border(top: BorderSide(color: GoOutsColors.dividerGray)),
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        children: [
          _buildNavItem(Icons.search, 'Search', false),
          _buildNavItem(Icons.calendar_today, 'Bookings', true),
          _buildNavItem(Icons.camera_alt, 'Deposit', false),
          _buildNavItem(Icons.gavel, 'Disputes', false),
          _buildNavItem(Icons.person, 'Profile', false),
        ],
      ),
    );
  }

  Widget _buildNavItem(IconData icon, String label, bool isActive) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        Icon(icon, color: isActive ? GoOutsColors.primaryBlue : GoOutsColors.bodyText),
        const SizedBox(height: 4),
        Text(
          label,
          style: GoogleFonts.inter(
            fontSize: 10,
            fontWeight: isActive ? FontWeight.bold : FontWeight.w500,
            color: isActive ? GoOutsColors.primaryBlue : GoOutsColors.bodyText,
          ),
        ),
      ],
    );
  }
}
