import 'dart:convert';

// ─────────────────────────────────────────────────────────────────────────────
//  The short booking reference a guest can read down a phone.
//
//  Written 27 August 2026: "manage to shorten the Reference number i think it
//  is generated by firebase see how we can manage this properly".
//
//  It was right. The screen printed `widget.bookingId`, the raw Firestore auto
//  id, which looks like LorC7MLDic9xjrXKq4t8. Twenty characters of mixed case
//  with no grouping. It overflowed the card, and nobody can read it aloud,
//  write it on a pad, or type it into a support form without getting it wrong.
//
//  ── ⚠ WHY THIS IS DERIVED AND NOT RANDOM ────────────────────────────────────
//
//  13_booking_confirmed_screen.dart carried this comment, and it was correct:
//
//      "The real document id, not a GOS-00000-X pattern invented for the
//       mockup. This is what support and the host both search on, so a guest
//       reading it down the phone has to be reading the same string that exists
//       in Firestore."
//
//  A prettier code that nobody can trace back to a booking is worse than an
//  ugly one that can. So this is NOT a random code:
//
//      reference = f(bookingId), and f is pure.
//
//  That buys three things at once:
//
//    · support can compute the reference from any booking id, offline, with no
//      lookup and no stored field
//    · createStayBooking writes the SAME value onto the document, using the
//      same algorithm, so the reverse direction is a single indexed equality
//      query on `reference`
//    · every booking made BEFORE the field existed still displays a correct
//      reference, because the client derives it rather than reading it. No
//      backfill, and if one is ever run the codes do not change
//
//  ── ⚠ IF YOU CHANGE THE ALGORITHM YOU CHANGE EVERY EXISTING REFERENCE ───────
//
//  Guests have these in emails and on notes. The JS half in stay_booking.js
//  must stay byte for byte identical. Change one, change both, and accept that
//  older references stop resolving.
//
//  ── COLLISIONS ──────────────────────────────────────────────────────────────
//
//  30 bits, so about 1.07 billion codes. At a few thousand bookings the odds of
//  any clash are negligible, and a clash is not dangerous in any case: support
//  scopes by customer, and the document id remains the actual key. The
//  reference is a convenience for humans, never an identifier the code trusts.
// ─────────────────────────────────────────────────────────────────────────────

/// Crockford base32: no I, L, O or U.
///
/// Those four are excluded because a person reading a code aloud or copying it
/// off a screen confuses I with 1, L with 1, O with 0, and U with V. Removing
/// them from the alphabet removes the ambiguity at the source rather than
/// asking support to guess which was meant.
const String _alphabet = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';

/// The reference for a booking, formatted `GOS-XXXXX-X`.
///
/// Deterministic. The same id always produces the same code, on any device, in
/// any build, and in the Cloud Function.
String stayBookingReference(String bookingId) {
  final String id = bookingId.trim();
  if (id.isEmpty) return '';

  // ── ⚠ FNV-1a 32 bit, AND IT IS DELIBERATELY NOT A CRYPTOGRAPHIC HASH. ──────
  //
  // This started as sha256 and was changed on the same day, because the HOST
  // app has to show the identical code and does not have the `crypto` package.
  // Three apps needing a dependency to print a booking number is the wrong
  // trade, and a pubspec change is one more thing to forget before a build.
  //
  // FNV-1a is nine lines, identical in Dart, JavaScript and anything else, and
  // needs nothing. It is not secure and does not need to be: the input is an
  // already unique Firestore id, the output is a label a human reads aloud, and
  // nothing in the system trusts it as an identifier.
  //
  // ⚠ JS MUST USE Math.imul FOR THE MULTIPLY. A plain `*` there exceeds the 53
  // bit safe integer range and silently returns a different number, which would
  // make the two halves disagree without either one erroring.
  int v = 0x811C9DC5;
  for (final int b in utf8.encode(id)) {
    v ^= b;
    v = (v * 0x01000193) & 0xFFFFFFFF;
  }
  // Keep the low 30, which is exactly six base32 digits.
  v &= 0x3FFFFFFF;

  final StringBuffer out = StringBuffer();
  for (int k = 5; k >= 0; k--) {
    out.write(_alphabet[(v >> (5 * k)) & 31]);
  }
  final String s = out.toString();

  // Grouped the way Stitch drew it, GOS-88219-X. The split is for reading, not
  // a checksum. Five characters is about the most a person holds in one glance.
  return 'GOS-${s.substring(0, 5)}-${s.substring(5)}';
}
